### ISSUE TITLE
Saving variant notes

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1016]
When I trying to save a note on the variant page, it does not save at all if I also choose 'add to public list'. If the latter option is not selected, it works fine-https://seqr.broadinstitute.org/project/R0380_cmg_gazda_wgs/saved_variants/family/F018914_gaz_432/Review

I was trying to save a note for the TRANK1 variant but could not save it when trying to do both.

**Comment by hanars** [comment]
This is fixed now
