### ISSUE TITLE
Genotype not showing

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1017]
https://seqr.broadinstitute.org/project/R0383_gazda_exomes/saved_variants/family/F018948_gaz_432/Review

<img width="1231" alt="Screen Shot 2019-09-02 at 10 35 31 AM" src="https://user-images.githubusercontent.com/37872186/64121627-67e98f80-cd6d-11e9-9fdb-ed7f141e1ffd.png">

**Comment by hanars** [comment]
This is fixed now
