### ISSUE TITLE
Manager having trouble adding pedigree information through phenotips

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#1021]
Jennifer Venneri, jmcevoyvenneri@ucsd.edu has been having trouble adding pedigrees through phenotips to the following families in https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/project_page

"I listed the Gleeson family ID number where this happened.  
4983, 7240, 7247,7255, 7257, 7274, 7388, 7569, 7620, 6729,6811, 6818, 6819, 6821, 6856.
We finished putting all the info into the other families."

Sam successfully loaded it into 6818, so it appears to be finicky by user and by family.

Here is the error Jennifer gets:

![image](https://user-images.githubusercontent.com/43212980/64564768-4ca7f280-d320-11e9-8192-2549242609ff.png)

**Comment by hanars** [comment]
These are all fixed

**Comment by katie-larkin** [comment]
The collaborator is seeing the same error with GLE_6819_2_1_D1.

https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/family_page/F028290_6819

**Comment by hanars** [comment]
Sorry guess I missed one. Its fixed now
