### ISSUE TITLE
Projects disappeared from SeqR

### ISSUE THREAD

**Issue by ThuongHa** [macarthur-lab/seqr#1034]
**Describe the bug**
Hi SeqR team,

All my projects have disappeared from SeqR like the aliens at Area 51. Please help.

Cheers,
Thuong

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org

**Scope of the bug**
See above and below. 

**Screenshots**
![Screenshot_2019-09-24 seqr home](https://user-images.githubusercontent.com/40529169/65472941-ef31ab00-deb4-11e9-865f-2c6606c10899.png)

**Comment by hanars** [comment]
You appear to have 2 seqr accounts, one at Thuong.Ha@unisa.edu.au which has access to all your projects and one at thuong.ha@adelaide.edu.au that does not. Try logging in with unisa account instead
