### ISSUE TITLE
Error while uploading HPO terms

### ISSUE THREAD

**Issue by Mohammedhusen** [macarthur-lab/seqr#1035]
**Describe the bug**
We are getting below error while uploading HPO term.

Error updating 953-F001: Unable to retrieve /rest/patients. response code = 500: Server Error

**Comment by hanars** [comment]
Can you please provide more context for this, including a link to the page where you are experiencing this issue

**Comment by hanars** [comment]
It sounds like you do not have phenotips running properly. It should be running on port 8080. When you go to http://localhost:8080/bin/login/XWiki/XWikiLogin you should see a login page for phenotips. If not you should try running `start_phenotips.sh` which should have been created during the local install process

**Comment by Mohammedhusen** [comment]
Thanks for your help on this.
Issues got solved after restarting start_phenotips.sh process.
