### ISSUE TITLE
IGV loading error

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1042]
https://seqr.broadinstitute.org/variant_search/results/6a287282ef2ea9b42093261d2b53e7d0?page=1&sort=xpos

IGV not loading for 3 of 4 individuals-
<img width="1073" alt="Screen Shot 2019-10-01 at 10 46 03 AM" src="https://user-images.githubusercontent.com/37872186/65973061-ba839d80-e438-11e9-8ce5-af5a40846d30.png">

**Comment by lynnpais** [comment]
Alysia noticed the same issue with a few other cases including RGP_465 and TGP_876.

**Comment by hanars** [comment]
@mike-w-wilson are you aware of these issues?

**Comment by mike-w-wilson** [comment]
This is now fixed.
