### ISSUE TITLE
IGV loading error

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1045]
https://seqr.broadinstitute.org/variant_search/results/803e2c0ce2a3e2fb41f40684443930cf?page=1&sort=xpos

<img width="1191" alt="Screen Shot 2019-10-09 at 10 40 30 AM" src="https://user-images.githubusercontent.com/37872186/66492483-7b7dc980-ea82-11e9-973f-d2fc28e302a4.png">

**Comment by mike-w-wilson** [comment]
This is now fixed.
