### ISSUE TITLE
Enable IGV/ show reads function

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1049]
The 'show reads' function does not seem to be around in these 3 cases, maybe more. 

https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/saved_variants/family/F013312_4665

https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/saved_variants/family/F013137_3622

https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/saved_variants/family/F013243_3073/Review

<img width="1183" alt="Screen Shot 2019-10-10 at 4 42 06 PM" src="https://user-images.githubusercontent.com/37872186/66604847-eb707a80-eb7c-11e9-8a0a-970bf04b4fab.png">

**Comment by mike-w-wilson** [comment]
This is now fixed.
