### ISSUE TITLE
no attribute 'SAMPLE_STATUS_LOADED'

### ISSUE THREAD

**Issue by jules-o** [macarthur-lab/seqr#1054]
Hi, sorry if this is a really basic question.

I've got seqr on a local install, Ubuntu 18.04. Hadn't used it for a few months then found various things not working after updates, so I reinstalled but kept the existing elasticsearch indexes and now everything seems to be working again except that when I try to search I get: 

search error: type object 'Sample' has no attribute 'SAMPLE_STATUS_LOADED'

What should I do?

**Comment by hanars** [comment]
That sounds like the code for your database is up to date but not the code for your server. I would go into the seqr directory and do a git pull to make sure you have the latest code

**Comment by jules-o** [comment]
Thanks hanars. Just tried git pull in the seqr directory again but it says already up to date and still getting the error.

**Comment by hanars** [comment]
Can you attach the stack trace from the server logs?

**Comment by jules-o** [comment]
[gunicorn.log](https://github.com/macarthur-lab/seqr/files/3736199/gunicorn.log)

**Comment by hanars** [comment]
Oh this is a bug on my end. I will get it fixed and let you know once its working again, although I'm currently at a conference for the next week so it may be a while. 

Also, this is coming up in code that is scheduled for deprecation in about 6 weeks. If you plan to keep updating seqr, you will need to re-load the data into elasticsearch, using the  `--use-nested-objects-for-vep --use-nested-objects-for-genotypes` args in your loading command. If you reload it now, it will also fix this bug for you so it might be worth just doing that now

**Comment by jules-o** [comment]
OK thank you... sorry to be stupid (not v familiar with elasticsearch) but is there a simple way to do that or do I have to load from scratch again through `gcloud_dataproc/submit.py`?

**Comment by hanars** [comment]
Not a stupid question, and yes it involves starting again from `gcloud_dataproc/submit.py` with the same arguments you used before plus the 2 new ones. You do not need to reomve anything from elasticsearch though, you will just add this new index in addition to the one you had

**Comment by jules-o** [comment]
Lol oh good :) Thank you, I will re-load the data now.

**Comment by jules-o** [comment]
Actually, before I do that: does the local install work with hail 0.2 yet? I know it had quite a way to go still a few months ago but if it is ready then I'm hoping it might let me load some files called by Starling, which don't work with v0.1.

**Comment by hanars** [comment]
This bug is fixed in the latest seqr code (although I would still recommend reloading)
