### ISSUE TITLE
Duplication of tags and notes across families + all families showing up on family pages

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1055]
This might be two separate problems. 
When looking at project saved variants OR family saved variants, all families with that variant are showing up (which shouldn't happen for the family page) and notes and tags are propagating across all families (overriding their own notes on the project page)  

Example of overriding tags and notes on the **project saved variants** page:
https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/saved_variants/Analyst%20high%20priority

Example of other families showing up on the **family saved variants**: 
https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/saved_variants/family/F012938_ogi287/Send%20for%20Sanger%20validation
https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/saved_variants/family/F012980_ogi1013/Known%20gene%20for%20phenotype

It looks like this is not project specific!

**Comment by hanars** [comment]
This is fixed now

**Comment by stephditroia** [comment]
This is my one big THANK YOU for fixing all these bugs while you are away at ASHG!! :)
