### ISSUE TITLE
Seqr giving Internal Service Errors

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#1062]
Navigating to any URL in seqr this morning is often giving Internal Service Errors instead of loading the page. It seems to be flickering every few seconds, as occasionally I have loaded the header of a project and then gotten a 404 for the remainder of the page.

In Slack Stephanie, KC, and Eliza have +1'd suggesting they are also experiencing this.

**Comment by ch-kr** [comment]
Not sure if this is related, but I'm currently getting 503 errors

**Comment by hanars** [comment]
I think this is fixed now, as as far as I know this has stopped happening. Please submit a new issue if this happens again
