### ISSUE TITLE
Walsh Lab Exomes tagged variants link broken

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1067]
None of the tagged variant links work for this project. Especially important is to view and download all the variants tagged as “send for Sanger" or "Sanger Troubleshooting".

Search and IGV are also broken at the moment, but I believe this is due to project reloading. 

https://seqr.broadinstitute.org/project/R0346_walsh_lab_exomes/project_page

**Comment by hanars** [comment]
The saved variants pages are now working again. For search, they can use old search from here: https://seqr.broadinstitute.org/project/walsh
Reads are a separate issue that will hopefully be resolved next week once I finish reloading the project and enable new search for them
