### ISSUE TITLE
Request to upgrade project to newer search interface. 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1077]
Hi Hana,

Can we have project Kang_v11 updated to the newer interface? It doesnt look like they will be getting new data soon, but have requested for it to be updated to allow cross-project searches. 

Thanks!

**Comment by hanars** [comment]
Unfortunately, we have been unable to reload this project because somehow only 56 of the expected 106 samples are in our callset. We have been looking for the rest of them, but no luck so far. I will let you know if we make any progress

**Comment by lynnpais** [comment]
Hi Hana, 

Any updates on this? The Kang group is unable to perform a search across their project. The deprecated page is no longer functional, so that's not an option either. Any suggestions for how they can perform a search?
<img width="1261" alt="Screen Shot 2019-11-14 at 8 28 41 AM" src="https://user-images.githubusercontent.com/37872186/68861064-c8277680-06b8-11ea-91cb-d80ecd567b78.png">

**Comment by lynnpais** [comment]
Hi Hana,

Can you pls share a link to the deprecated Search page for the Kang group? Thanks!

**Comment by hanars** [comment]
Hi Lynn, We are hoping to have this resolved before December 1 (although we can't be sure so please don't communicate that as a hard date). In the meantime, they can access the old project page here, and go to family pages/ searches and gene search from here:
https://seqr.broadinstitute.org/project/Kang_v11

**Comment by hanars** [comment]
Hi @lynnpais this is now resolved, they can do searches from the normal seqr page. Access to the old search pages will be turned off completely on Sunday, so if they are having any issues with the new search please let me know ASAP
