### ISSUE TITLE
Summary of diagnosis rate

### ISSUE THREAD

**Issue by monkollek** [macarthur-lab/seqr#108]
One critical thing that is missing and is very beneficial in terms of presentation slides and granting purpose is the diagnosis rate for a project/cohort. The information is there or could be there and summarized quite easily on the Project summary page. At the moment it can be generated but in an ad-hoc fashion, which is very annoying!

I'm suggesting four main categories:
1. Undiagnosed
2. Diagnosed with a known gene for that phenotype
3. Diagnosed with a known gene for a different phenotype 
4. Novel gene

**Comment by bw2** [comment]
This now appears on the new dashboard page (and will also be added to the project page)
