### ISSUE TITLE
Case Review Filtering Yields No Results

### ISSUE THREAD

**Issue by mdholl** [macarthur-lab/seqr#1085]
When filtering for Accepted cases in Case Review mode within the Rare Genomes Project_Genomes, no results appear. 

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/case_review

<img width="1310" alt="Screen Shot 2019-11-19 at 5 58 33 PM" src="https://user-images.githubusercontent.com/57968701/69194403-10022f80-0af7-11ea-9c51-23aececfae04.png">

**Comment by hanars** [comment]
Can you try refreshing the page and trying again? I'm seeing 471 accepted families

**Comment by mdholl** [comment]
I tried refreshing and it unfortunately didn't work

**Comment by hanars** [comment]
This might be best resolved in person - can you come by my desk with your laptop anytime today?

**Comment by mdholl** [comment]
Sorry - I was out of the office and didn't see this. Do you have time this morning or tomorrow morning?

**Comment by hanars** [comment]
I'm free the rest of the morning if you want to swing by, or later in the morning tomorrow

**Comment by hanars** [comment]
This should be fixed now. Try refreshing the page, and if hat doesn't work swing by my desk tomorrow

**Comment by mdholl** [comment]
It works! Thank you so much.
