### ISSUE TITLE
Staff access request

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#1086]
Not really a bug, but can you grant Sanna staff access to seqr so she can see all the projects: sgudmund@broadinstitute.org

Thanks!

**Comment by hanars** [comment]
Done! However, in the future when you are adding a new user to seqr that you know is going to be staff you can create them directly as a staff user here, rather than creating them by adding them to a project: https://seqr.broadinstitute.org/staff/create_user
