### ISSUE TITLE
Installation local step 6 : bug with Django version

### ISSUE THREAD

**Issue by bnouyou** [macarthur-lab/seqr#1088]
Hello,

I am doing the local installation, and in the step 6, I can see an error with the Django versions:
In the script:
`# install python dependencies`
`sudo $(which pip) install --upgrade --ignore-installed -r requirements.txt`

In the requirements, it seems that these versions are not compatible:
`Django==1.11.23                  # core server-side framework`
`django-hijack==2.1.3             # allows admins to login as other user`

This is the error message I have:
`ERROR: django-hijack 2.1.3 has requirement django<1.11,>=1.4, but you'll have django 1.11.23 which is incompatible.`
`ERROR: django-debug-toolbar-request-history 0.1.0 has requirement django-debug-toolbar>=2.0, but you'll have django-debug-toolbar 1.11 which is incompatible.`

**Comment by bw2** [comment]
@bnouyou  We used django-hijack for debugging, but it's not necessary for running seqr.
You should be able to just ignore this error.
