### ISSUE TITLE
issue in Publications on this discovery array field

### ISSUE THREAD

**Issue by WendyZhang05** [macarthur-lab/seqr#1093]
Hi,

I encounter an issue in **Publication on this discovery** field on any family page of Seqr 2.0 (our local instance). When I press **Add Publication** a new field is added at first fine, but when we press it the second time, a confirmation dialog was opened an unknown reason. If I click on Ok in confirmation dialog, a submit error mark will show up next to submit button. It looks like the click on Add publication button triggers form submission, which should not happen. 

![Screen Shot 2019-11-27 at 10 38 59 AM](https://user-images.githubusercontent.com/19737714/69737361-4563da00-1102-11ea-98e6-48b3c76d1373.png)

![Screen Shot 2019-11-27 at 10 39 31 AM](https://user-images.githubusercontent.com/19737714/69737373-498ff780-1102-11ea-82c9-be6ca08a411c.png)

**Comment by hanars** [comment]
That looks like you have a third empty publication so it is failing validation because you can't have a blank publication. If you click the x it will remove the blank publication and then it should be fine

**Comment by WendyZhang05** [comment]
in my attached example, the first line "test" is already there when I open this field. The second publication is added correctly with no issue, then I try to add a third one by clicking on Add Publication link again. This time, confirmation dialog shows up and error displayed on Submit button. I do not even have a chance to type the third publication.

**Comment by hanars** [comment]
Hmm yes this is a weird bug. If you hit "cancel" the first time it pops up, enter the publication, hit "submit" and then in the confirmation this time hit "ok" it should work. But thats def not ideal so I'll keep this open

**Comment by hanars** [comment]
This is fixed with the latest seqr code release

**Comment by WendyZhang05** [comment]
Thanks a lot! looks good for me now
