### ISSUE TITLE
HPO terms upload reads as csv but some HPO term descriptions use commas

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#1094]
When I download and re-upload phenotypes from existing projects, seqr occasionally runs into parsing errors when any HPO term in the series has a comma in the phenotype description.

Playing around with the downloads from the Scott Exome project and the Genome project I transferred phenotypes into, it looks like seqr will only include a comma if that was in the description of the upload. Is there a way to either have seqr simply not include any commas in phenotype descriptions when downloading current individual HPO terms or to have it only separate by semicolon?

**Comment by katie-larkin** [comment]
This is low priority, I just wanted it to be on your radar as a somewhat frustrating bug.

**Comment by hanars** [comment]
Is this still an issue, and if so could you link to a page where it is happening?

**Comment by katie-larkin** [comment]
I did a test in https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/project_page and it seems to give a weird warning about the part of the phenotype post-comma [test case included HP:0002342 (Intellectual disability, moderate) in the middle of several HPO terms for the individual], but seqr is no longer trying to parse the description post-comma as its own term and breaking everything after the point. Thanks for following up!
<img width="773" alt="VCGS Phenotypes" src="https://user-images.githubusercontent.com/43212980/89536026-45ee5d80-d7c5-11ea-9ff5-c31f5e9de7d3.PNG">
