### ISSUE TITLE
Matchbox not working to show matches

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#1114]
**Describe the bug**
Just FYI that we are entering genes in matchbox for the Manton Doose cohort and not getting any matches. We thought it was weird that several in a row had no matches so we tried genematcher and there are actually lots of matches for these genes so seems like matchbox isn’t working. @englandeleina is the one entering these. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0523_cmg_manton_doose_wes/family_page/F028624_man_0200/matchmaker_exchange
This has over a dozen matches in GeneMatcher

**Scope of the bug**
I haven't checked if this is other projects or isolated.

**Comment by hanars** [comment]
This was an issue with searching in genematcher that is now resolved
