### ISSUE TITLE
Readviz not working for this sample

### ISSUE THREAD

**Issue by englandeleina** [macarthur-lab/seqr#1117]
Reads are not showing up for this sample, but they seem to be working for other variants on other families in this project: (also @ch-kr )

https://seqr.broadinstitute.org/project/R0404_cmg_estonia_wes/saved_variants/family/F021501_hk081/Review

**Comment by hanars** [comment]
@ch-kr @mike-w-wilson it looks like read data was never added for that family

**Comment by mike-w-wilson** [comment]
This is now fixed along with reads for HK119.
