### ISSUE TITLE
Phenotips not updating for PIE_OGI3003_004589_D1

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#1119]
Attempting to enter phenotips for PIE_OGI3003_004589_D1, either individually or via bulk upload, yields the following error message:

Unable to retrieve /rest/patients/eid/I0076217_pie_ogi3003_004589_1. response code = 300: Multiple Choices

https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/family_page/F029413_ogi3003

**Comment by hanars** [comment]
This is fixed
