### ISSUE TITLE
Seqr Manifests not uploading to R0382_cmg_myoseq_exomes

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#1120]
Attempts to upload multiple manifests to the CMG_Myoseq_Exomes project is yielding the following error that is not giving me enough information to troubleshoot. I've tried copying the information on a fresh template to see if that was the problem but it's not working.

The error is: "Error while parsing file: Pedigree_Sample Manifest Revisions (47).xlsx. 'NoneType' object has no attribute 'startswith'"

**Comment by hanars** [comment]
Please attach the the file that is causing the error. If you prfer, you can open a ticket in the seqr-private repo and do it there

**Comment by hanars** [comment]
Also, in the future a link to the page is really helpful. Using the bug issue template will, in general, make sure you don't miss any of the information I need when you create the ticket

**Comment by katie-larkin** [comment]
Sorry about that!

Here's the file and the project page is https://seqr.broadinstitute.org/project/R0382_cmg_myoseq_exomes/project_page
[Pedigree_Sample Manifest Revisions (47).xlsx](https://github.com/macarthur-lab/seqr/files/4016629/Pedigree_Sample.Manifest.Revisions.47.xlsx)
