### ISSUE TITLE
GTex data

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1124]
Hi Hana,

There seems to be a discrepancy in the Gtex expression data from the main Gtex portal and the gene data displayed in seqr - https://seqr.broadinstitute.org/project/R0482_cmg_thaker_wes/saved_variants/variant/SV0048008_2037529233_r0482_cmg

For PPP1R16B, it seems as tho it is not expressed in the brain looking in seqr, but when you go to the main site, its expression is the highest in the brain. I know you mentioned yesterday that you are running the most recent version, so I am not sure what the issue is. Any thoughts?

**Comment by hanars** [comment]
Thanks for pointing this out! There is a bug on my end that is causing gex to show for the wrong gene sometimes. I will fix this ASAP

**Comment by hanars** [comment]
This is fixed now
