### ISSUE TITLE
Seqr's search for other allele in callset bug

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1127]
There appear to be 2 other alleles in the CMG callset- https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0065356_1749044067_f028688_r

However a search returns the message- Unable to load more than 10000 variants (15700 requested)

The variant itself is of poor quality. Not if this is causing the issue.

**Comment by hanars** [comment]
This is fixed now: https://seqr.broadinstitute.org/variant_search/results/ead1ae916607d83ab18feeeb183fb89c?page=1&sort=xpos
