### ISSUE TITLE
MME update submission issue

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1133]
After choosing 'update submission', even though I did not change any information in MME, several other matches showed up, but are not relevant to the gene. 

Any idea what is happening here- https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F027305_rgp_770/matchmaker_exchange ? I noticed this in one other case as well. 
<img width="1283" alt="Screen Shot 2020-01-16 at 8 00 18 PM" src="https://user-images.githubusercontent.com/37872186/72575571-dfdad100-389a-11ea-9182-a54f0d0e91f1.png">

Thanks for taking a look.

**Comment by hanars** [comment]
I have updated the logic for showing decipher submissions, and after hitting "search new matches" these bad matches are gone. If you have other submissions where you have matches like this you do not want, hitting "search" will clear them
