### ISSUE TITLE
Pedigree display bug

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1136]
In the saved variants view, it appears as though the mom is affected. The circle is colored in- https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F028218_rgp_1090

<img width="1210" alt="Screen Shot 2020-01-18 at 1 18 06 PM" src="https://user-images.githubusercontent.com/37872186/72668454-1c224480-39f5-11ea-8843-8fb84098c149.png">

**Comment by hanars** [comment]
This is fixed
