### ISSUE TITLE
Broken pedigrees

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1137]
All the pedigrees in this project seem to be broken- https://seqr-dev.broadinstitute.org/project/R0394_cmg_kang_lgmd_wes/project_page

<img width="1210" alt="Screen Shot 2020-01-20 at 10 33 02 AM" src="https://user-images.githubusercontent.com/37872186/72738752-40eef700-3b70-11ea-8b78-9a355c03ac85.png">

**Comment by hanars** [comment]
thats seqr-dev, not real seqr. pedigree images don't work on the dev environment
