### ISSUE TITLE
Gene search link not working

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1144]
Gene Search link has been returning a 400 error. Same error regardless of the gene and across multiple projects. 

Example: 
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F027744_rgp_955/Confident%20AR%20one%20hit

**Comment by hanars** [comment]
When I click on the gene search link it works fine, and takes me here: https://seqr.broadinstitute.org/variant_search/results/b2a1fbce13d406725b3d47a517320c94?page=1&sort=xpos

**Comment by stephditroia** [comment]
That link works for me and now gene search for HOGA1 works. However, gene
search for HOXB6 and CFTR (other genes with review tags for that family)
still give 400 error.

The urls that are returning 400 error for me:
https://seqr.broadinstitute.org/variant_search/results/5f0845cf19929ccb1aae8bf6d229fd60?page=1&sort=xpos
https://seqr.broadinstitute.org/variant_search/results/baf660cecff163f55d1ac28bcfa07467?page=1&sort=xpos

I also checked a different family/project and get the same result. Maybe
it's something about my settings?
I can do a workaround search for now, so this can wait until you get back
if it's not something obvious.


*Stephanie Parker DiTroia, PhD*
Clinical Genomic Variant Analyst
Broad Institute of MIT and Harvard
105 Broadway
Cambridge, MA 02142
sditroia@broadinstitute.org <alovgren@broadinstitute.org>

**Comment by hanars** [comment]
Hmm so for me those links both showed 400, but then when I clicked "gene search" on CFTR it took me to the same URL but this time it worked, and then for HOXB6 it took me to the same url and showed a 400 but when I refreshed that page it worked. And now both of those links work. I think it would be helpful for me if we could go over this in person sometime next week or when I get back

**Comment by hanars** [comment]
Can no longer replicate, but still should not 400 error when first click on link

**Comment by hanars** [comment]
Can no longer replicate 400 issue so closing this out
