### ISSUE TITLE
Selecting and going to the project page

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1146]
Historically, clicking on the case ID on the left hand side above every variant, would take you to the main family page. If you do that now, a screen appears and does not let you click the case ID. This is inconvenient as there is no other way to get back to the main family page and the saved variants. Would it be possible to restore that functionality? 

<img width="1347" alt="Screen Shot 2020-01-23 at 2 54 43 PM" src="https://user-images.githubusercontent.com/37872186/73018856-6e49d800-3df0-11ea-9ea2-b000aa62e5f9.png">

**Comment by hanars** [comment]
In the future, please follow the issue template. It prompts you for what to include, such as links which you forgot from this ticket. I know it feels tedious, but these things make my life much easier which in turns means I can fix things faster

**Comment by lynnpais** [comment]
Hi Hanna,

I almost always include the link, but I forgot this time. Sorry about that. Here's the link- https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F019668_rgp_95

When I try to click on the Family ID (highlighted in image 1), the family page window opens (see image 2). It completely covers the ID number and hence I cannot click it. Emily noticed it too, so I am sure this is a more widespread issue. It might be related to RGP only, as I did not see it in a CMG case.

Image 1
<img width="1233" alt="Image1" src="https://user-images.githubusercontent.com/37872186/73101242-45dbdf80-3ebd-11ea-91c0-f64af174f85f.png">

Image 2
<img width="1276" alt="Image2" src="https://user-images.githubusercontent.com/37872186/73101261-4e341a80-3ebd-11ea-8f77-e5dae912fa42.png">

**Comment by hanars** [comment]
This is fixed
