### ISSUE TITLE
Saved variants not showing

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1149]
HELP! Seqr won't display saved variants for me. It seems to be specific to my login and I have logged out and in already. Here is an example:

https://seqr.broadinstitute.org/project/R0456_cmg_walsh_exomes_ch/saved_variants/family/F023760_ch5200/Tier%202%20-%20Novel%20gene%20for%20known%20phenotype

What I see: 
![image](https://user-images.githubusercontent.com/44381119/73088800-ecff4d80-3ea2-11ea-9063-0e6e9338b6e5.png)

**Comment by stephditroia** [comment]
More info: I can see all saved variants for a family, but I can't filter for a specific tag (either by dropdown or clicking on bar)

**Comment by hanars** [comment]
Try clearing your local storage: https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/

**Comment by stephditroia** [comment]
That didn't seem to work. BUT I can see them on safari so I know it's a
browser issue. I'll keep troubleshooting.


*Stephanie Parker DiTroia, PhD*
Clinical Genomic Variant Analyst
Broad Institute of MIT and Harvard
105 Broadway
Cambridge, MA 02142
sditroia@broadinstitute.org <alovgren@broadinstitute.org>

**Comment by hanars** [comment]
Fixed locally by clearing local storage. Will prevent from happening again with https://github.com/macarthur-lab/seqr/issues/1155
