### ISSUE TITLE
Comp Het pair displaying wrong gene

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1163]
This compound het pair is under SPATA6L but the two variants (missense and synonymous) listed are in SLC1A1.  

https://seqr.broadinstitute.org/variant_search/variant/undefined/family/F027613_rgp_893

**Comment by hanars** [comment]
Sorry that link is broken, you provide a link to the search page?

**Comment by stephditroia** [comment]
https://seqr.broadinstitute.org/variant_search/results/365bfc8a7294c938a746f0985bd4de7b?page=1&sort=xpos

**Comment by hanars** [comment]
This is now showing the correct gene, thanks for letting me know!
