### ISSUE TITLE
Show tagged variants blank

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1165]
Good afternoon, 
When I click on the colored saved variant bar to display all tagged variants, the subsequent display page is blank.  I noticed this yesterday and it is still happening.

**Comment by hanars** [comment]
Please fill pout the entirety of the issue report template, including links and screenshots

**Comment by JenPartlow** [comment]
https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/family/F023507_mc17100

Example: Walsh Lab Microcephaly cohort family WAL_MC17100

I can't seem to put a screen shot in here. 

Thanks
Jen

**Comment by hanars** [comment]
I cannot recreate this bug, the page loads fine for me. Try clearing your local storage and see if that fixes the issue: 
https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/
<img width="25" alt="Screen Shot 2020-02-07 at 11 33 05 AM" src="https://user-images.githubusercontent.com/24598672/74047156-e04c2080-499d-11ea-85ed-9546b7083dfc.png">

**Comment by JenPartlow** [comment]
I checked my local storage and there is none to clear.  My colleague Abbe Lai has the same issue, while another in my office does not.  On further review, it seems it is the "Showing All saved variants" is not working but if I select "Show Review" variants from the drop down, it does display those select ones.  

I still can't seem to send you a screen shot here in git hub, I'll try responding in my email with them. 

Thank you
Jen

**Comment by JenPartlow** [comment]
I checked my local storage and there is none to clear.  My colleague Abbe Lai has the same issue, while another in my office does not.  On further review, it seems it is the "Showing All saved variants" is not working but if I select "Show Review" variants (or any other single tag) from the drop down, it does display those select ones.


[cid:image008.png@01D5DDB3.5DCE66F0][cid:image009.jpg@01D5DDB3.5DCE66F0]



[cid:image010.png@01D5DDB3.5DCE66F0][cid:image011.jpg@01D5DDB3.5DCE66F0]






Jennifer Neil Partlow, MS, LCGC
Genetic Counselor Research Coordinator  |  The Walsh Lab<http://www.walshlab.org/>
Boston Children’s Hospital<http://www.childrenshospital.org/>  |  Howard Hughes Medical Institute<https://www.hhmi.org/>
Mail: 300 Longwood Ave, BCH3150, Boston, MA, 02115
Courier: 3 Blackfan St, CLS15070, Boston Children’s Hospital, Boston, MA, 02115
T: 617-919-2865  |  F: 617-919-2300

**Comment by hanars** [comment]
Responding to an email with links does not work in github, it just sends `[cid:image008.png@01D5DDB3.5DCE66F0][cid:image009.jpg@01D5DDB3.5DCE66F0]`. At the bottom of the comment box on github on the website it says "Attach files by dragging & dropping, selecting or pasting them". Clicking there will allow you to add a screenshot.

Also, if you are using a supported browser with seqr you will have local storage. So either you are not correctly checking it, or you are not using a supported browser. Which browser and version one are you using?

**Comment by JenPartlow** [comment]
![allvars](https://user-images.githubusercontent.com/60754044/74056149-7177c300-49af-11ea-9b71-ac4868dbb99b.jpg)

![sangervars](https://user-images.githubusercontent.com/60754044/74056168-789ed100-49af-11ea-8674-f250c6948502.jpg)

I use chrome:

![storage](https://user-images.githubusercontent.com/60754044/74056474-17c3c880-49b0-11ea-96d6-c3555496c37d.jpg)

![localstorage](https://user-images.githubusercontent.com/60754044/74056487-1befe600-49b0-11ea-9a4b-bef6e925786b.jpg)

Not sure if the above worked but all the screen shots appear for me here in the preview tab.

**Comment by stephditroia** [comment]
Hey Hana - I am seeing this as well. It is not the same as before, when clearing my local storage worked. It seems to be isolated to 'All Saved' and 'CMG Discovery Tags'. 
 
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F026334_rgp_673
![image](https://user-images.githubusercontent.com/44381119/74057747-915cb600-49b2-11ea-96dc-86dd1c73433b.png)
![image](https://user-images.githubusercontent.com/44381119/74057766-9ae61e00-49b2-11ea-93bf-8fd098a9a5f1.png)

**Comment by hanars** [comment]
Okay, this should be fixed now. Sorry for all the back and forth while I was trying to recreate the issue. Also, Stephanie that page will still show 0 for discovery tags because that family has no discovery tags. But if you toggle back to "All Saved" the variants actually show up now
