### ISSUE TITLE
Inheritance based search and affected status

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1166]
Hello, 

A recent variant search in a family with two affected where the affecteds seem clearly labeled as such and data is loaded, produced the following message: 

"Inheritance based search is disabled in families with no affected individuals"

https://seqr.broadinstitute.org/variant_search/results/855c65a8c454dab7e03c5654fc2eeff7?page=1&sort=xpos

in Walsh Lab family WAL_PMG7400

**Comment by hanars** [comment]
While there are 2 affected individuals in this family, they do not have any data loaded. If you look next to the 2 unaffected individuals on the family page you will see a green dot indicating that a WES sample was loaded for that individual on 1/29/2020 but if you look next to the affected individuals you see no such indicator. Please reach out to the project coordinator to figure out why those samples are missing

**Comment by JenPartlow** [comment]
Thank you
