### ISSUE TITLE
seqr not loading/very slow

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1171]
Seqr is uncharacteristically slow/broken today.  This morning it was taking forever to load any page or perform a search, or it times out and I get a 504 error.  I don't have screen shots from then.  It just gave up loading my projects: 
![Noprojects](https://user-images.githubusercontent.com/60754044/74271682-4fe24880-4cdb-11ea-8352-105f805459f7.jpg)

**Comment by hanars** [comment]
seqr should now be working again. Sorry for the diruption
