### ISSUE TITLE
Error with bulk uploading HPO terms

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1172]
Seeing error ```Unable to retrieve /rest/patients. response code = 500: Server Error``` when bulk uploading HPO terms for families that lost phenotips. Making a ticket to be sure it isn't something bigger backend. 
https://seqr.broadinstitute.org/project/R0477_cmg_sankaran_genomes/project_page
![image](https://user-images.githubusercontent.com/44381119/74356191-ecfcba00-4d8b-11ea-981d-97c9bdcdcc3c.png)

**Comment by katie-larkin** [comment]
Bumping this as Julie from the Engle group and Vidhu in the Thaker team have also had errors.

Julie noted the same server error with bulk uploads and Vidhu didn't specify the error but was using phenotips interface.

**Comment by hanars** [comment]
This is fixed now. Let me know if anyone is still reporting issues
