### ISSUE TITLE
500 error HPO term loading

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1178]
Hi, I'm trying to bulk upload HPO terms for our CMG_Engle_WES cohort and am getting a 500 error (see attached screenshot). Thanks!

![Screen Shot 2020-02-13 at 9 30 29 AM](https://user-images.githubusercontent.com/41243189/74452595-47128380-4e4f-11ea-862c-3d410d712fc1.png)

**Comment by hanars** [comment]
This is now fixed
