### ISSUE TITLE
variant tags not showing

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1182]
Hi, I've saved a few variants just now but am not able to access them when I click on them later (in other words, can see that something was tagged in the family, but clicking on the tag doesn't load any variant page). E.g.:

https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/saved_variants/family/F029034_eng_awa/Known%20gene%20for%20phenotype

**Comment by hanars** [comment]
Hi Julie, this variant is loading fine for me. Can you attach screenshots of the issue you are seeing? Also, can you tell me if this link to that variant works for you: https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/saved_variants/variant/SV0066813_1239332405_f029034_e

**Comment by juliejurgens** [comment]
Hi Hana, no I'm not able to see the variant in the link you sent, so not sure what's up. Here's a screenshot of one of the variants. All tagged variant categories are doing the same thing where it says the number of variants with each type of tag, but doesn't show any of them? despite hitting the colored bar at the top a few times.


Thanks,

Julie

________________________________

**Comment by hanars** [comment]
Hi Julie, you need to add screenshots in the github web page, not via email. If you have successfully added it, it will be visible on that page

**Comment by juliejurgens** [comment]
![Screen Shot 2020-02-18 at 11 23 57 AM](https://user-images.githubusercontent.com/41243189/74766892-e1116c00-5253-11ea-9791-1ba6ba15a055.png)


Hi, here is the screenshot. This issue is currently happening for the CMG_WES, CMG_WGS, and WGS900 projects.

**Comment by juliejurgens** [comment]
Eleina also just mentioned that she's running into the same issue for our projects; not sure if it's also happening to her w/ other projects outside of ours.

**Comment by hanars** [comment]
Do you have the same issue in an incognito browser window? If not, try clearing your local storage:  https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/

**Comment by juliejurgens** [comment]
Incognito browser seems to work fine, as does regular chrome browser (was operating in safari), so this may be the issue. Thanks!

**Comment by hanars** [comment]
Okay, in general seqr is not supported in safari, only in chrome, so we recommend you only use that browser

**Comment by juliejurgens** [comment]
Gotcha, will definitely do from now on. Thank you for your help!
