### ISSUE TITLE
Setting AC on the variant search page

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1183]
Setting AC only seems to adjust the frequency in the 1000 Genomes Database, instead of all databases. 
<img width="1315" alt="Screen Shot 2020-02-18 at 12 02 37 PM" src="https://user-images.githubusercontent.com/37872186/74759723-3eeb8700-5247-11ea-96c1-aad83c6b4e8b.png">

https://seqr.broadinstitute.org/variant_search/results/fc8af7a0cdb87480a6801643b07d10fe?page=1&sort=xpos

**Comment by hanars** [comment]
Please use the issue template as it generates the automated tags I need. In the future I will not be accepting tickets not made through the template

**Comment by lynnpais** [comment]
<img width="441" alt="Screen Shot 2020-02-18 at 1 29 17 PM" src="https://user-images.githubusercontent.com/37872186/74766083-b2df5c80-5252-11ea-858e-6738bc207133.png">

**Comment by hanars** [comment]
@lynnpais this should be fixed but can you confirm?

**Comment by hanars** [comment]
Closing out, but feel free to reopen if you see this again
