### ISSUE TITLE
Compound heterozygous search with different search criteria for two variants

### ISSUE THREAD

**Issue by SanderEST** [macarthur-lab/seqr#1185]
**Is your feature request related to a problem? Please describe.**
In cases with no obvious candidates, I would like to search in non-coding space but would like to first do a recessive search where one of the variants has to be at least missense (moderate to high impact). 

**Describe the solution you'd like**
A recessive search where you could apply filters for two variants separately. Eg. "Moderate to high impact AND any rare coding variant", or "Moderate to high impact AND non-coding variant".

**Describe alternatives you've considered**
Currently, the strategy I use is to do a recessive search and sort on protein consequence. This works for prioritizing, but I would ideally want to restrict my search in a way that I would not see two non-coding compound heterozygous variants showing up.

**Comment by hanars** [comment]
This is already doable: If you apply the recessive/ compound het inheritance mode an "Annotations Secondary" panel will appear. You can set that to have a more lenient set of transcript consequences than your primary "Annotations" and that will return hits where at least one variant meets the stricter criteria specified in "Annotations" but the other can meet the looser criteria from "Annotations Secondary"

**Comment by SanderEST** [comment]
Thank you, I never noticed this! Very cool!
