### ISSUE TITLE
broken readvis/browser IGV for CMG_Walsh_Exomes_CH

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1187]
**Describe the bug**
Walsh group emailed about CH1000 browser IGV not working. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0456_cmg_walsh_exomes_ch/saved_variants/family/F023732_ch1000/Review

**Scope of the bug**
Other families spot-checked in this project were affected. 

**Screenshots**

**Comment by hanars** [comment]
@mike-w-wilson

**Comment by mike-w-wilson** [comment]
It looks like this data moved in terra. I tried reloading the crams but seqr notifies me the paths have not changed. I have reached out to the PMs. It likely moved into an anvil bucket which I cannot see inside so will have to wait for the terra metadata to update.

**Comment by mike-w-wilson** [comment]
@hanars, I just checked in the samples have been in anvil, is there any chance this is an issue with the fc-secure bucket access?

**Comment by hanars** [comment]
Yes sorry it was an issue with seqr's gcolud settings, this is fixed now
