### ISSUE TITLE
Add hg38 build to MME automated email text 

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1195]
**Is your feature request related to a problem? Please describe.**
Anne noticed the build is not included and would like it to be. 

*Describe the solution you'd like**
I would add it right behind the variant. 
"Our patient has a homozygous variant 15:78458565 T>C (hg38) and presents with..."

**Describe alternatives you've considered**

**Additional context**

**Comment by hanars** [comment]
Done
