### ISSUE TITLE
Readvis links broken for 'Pierce - Retinal Degeneration - CMG - Exomes' new samples

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1196]
**Describe the bug**
Latest samples have no readvis/browser IGV

**Link to page(s) where bug is occurring**
Pierce - Retinal Degeneration - CMG - Exomes
https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/project_page
example family: https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/saved_variants/family/F029244_ogi1581

**Scope of the bug**
Unsure, definitely all the latest samples.

**Comment by hanars** [comment]
Per @mike-w-wilson 's announcement when he loaded the data we do not have readviz ready for these samples: https://the-tgg.slack.com/archives/GA620K989/p1580309631000400

**Comment by stephditroia** [comment]
Oh wow. I thought they had passed the 'new samples missing readvis'
threshold. My bad.



*Stephanie Parker DiTroia, PhD*
Clinical Genomic Variant Analyst
Broad Institute of MIT and Harvard
105 Broadway
Cambridge, MA 02142
sditroia@broadinstitute.org <alovgren@broadinstitute.org>
