### ISSUE TITLE
Walsh_Exomes_PMG cohort tags

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1201]
Good afternoon, 
It appears that the "Sanger in Progress" tag is missing from tag options in our CMG_Walsh_Exomes_PMG cohort.  Can you kindly add that as soon as possible? 
Thank you
Jen

**Comment by hanars** [comment]
Added!

**Comment by JenPartlow** [comment]
Thanks for your quick action!


Jennifer Neil Partlow, MS, LCGC
Genetic Counselor Research Coordinator  |  The Walsh Lab<http://www.walshlab.org/>
Boston Children’s Hospital<http://www.childrenshospital.org/>  |  Howard Hughes Medical Institute<https://www.hhmi.org/>
Mail: 300 Longwood Ave, BCH3150, Boston, MA, 02115
Courier: 3 Blackfan St, CLS15070, Boston Children’s Hospital, Boston, MA, 02115
T: 617-919-2865  |  F: 617-919-2300
