### ISSUE TITLE
Browser IGV not available for proband in trio - WWS11000

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1202]
**Describe the bug**
Cannot see proband's reads for this trio. Reads of both parents are available. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/variant/SV0027456_1748676895_r0451_cmg

**Scope of the bug**
All variants in the family are missing proband IGV reads. WAL_WWS11000_WWS11001

**Comment by hanars** [comment]
@mike-w-wilson looks like readviz was never added for the proband?

**Comment by mike-w-wilson** [comment]
This sample is not in either of Walsh's Terra workspaces. I've reached out to the PM team.

**Comment by hanars** [comment]
Any updte on this?

**Comment by mike-w-wilson** [comment]
Sorry followed up with Katie back in March and forgot to post 
```
yeah, this can't deliver to Terra due to high chimera. that PDO as a whole looks terrible for chimera (28 failures on that alone) but it's from 2017 so no way GP can follow up on something that old... I can try asking DSP if something in a newer QC call might be causing it...
``` 
So the cram was never delivered.

**Comment by hanars** [comment]
Oh yeah if you look at that individual's sample QC you can see issues. So sounds like we might want to address this sample more broadly before trying to get read data
