### ISSUE TITLE
Unable to tag variant

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1204]
**Describe the bug**
Unable to tag MEMO1 variant

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/0a91084f68c123e666ad48747c8242d7?page=1&sort=xpos

**Scope of the bug**
Specific family

**Screenshots**
<img width="1196" alt="Screen Shot 2020-03-03 at 5 55 17 PM" src="https://user-images.githubusercontent.com/37872186/75827676-32534c80-5d78-11ea-8d59-bfd31676d428.png">

**Comment by hanars** [comment]
Fixed
