### ISSUE TITLE
Unable to retrieve list of tagged variants

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1205]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening

Hi, I'm getting a 504 error when attempting to retrieve a list of priority tagged variants from our WGS900 cohort (106 variants total). 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/Analyst%20high%20priority

**Scope of the bug**
I've tried for 2 projects (WGS900 and Engle CMG_WES). I'm able to retrieve the list of priority tagged variants for the CMG_WES project (105 variants) but not WGS900 (106 variants). 

**Screenshots**

![Screen Shot 2020-03-04 at 11 10 14 AM](https://user-images.githubusercontent.com/41243189/75899451-89edc880-5e09-11ea-803d-f0f9262bce0d.png)

**Comment by hanars** [comment]
This is fixed now
