### ISSUE TITLE
Why switched SavedVariant ForeignKey to ManyToMany model?

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/seqr#1206]
Hi, 

I was going over the new code changes and one thing is a bit unclear: why did you decide to switch from `ForeignKey` to `ManyToManyField`  here, in `VariantTag` model:

https://github.com/macarthur-lab/seqr/blob/master/seqr/models.py#L522

What does it allow you to achieve? Could you give a reference to several places in the new code that demonstrate the necessity of it?

Maybe its related, but I am also curious of why you decided to pass multiple variants now instead of just one when we edit saved variants?

Regards

**Comment by hanars** [comment]
This was changed to support saving compound het variants together. If you do a compound het search, you will see the results are returned with the relevant pairs displayed together and you can add tags/notes to both together.
