### ISSUE TITLE
list indices must be integers, not str

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1208]
**Describe the bug**
Upon attempted recessive or compound het searches using standard frequencies for a single family, I get the following error message: "list indices must be integers, not str"

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/33c300d78a93ada13bd67078caa5aa44?page=1&sort=xpos

**Scope of the bug**
seems to be occurring just in wgs900

**Screenshots**
![Screen Shot 2020-03-05 at 11 24 08 AM](https://user-images.githubusercontent.com/41243189/76002067-0a78fb80-5ed4-11ea-8a79-0be7ba4c0bed.png)

**Comment by hanars** [comment]
This is fixed now
