### ISSUE TITLE
More content on memory and cpu options in LOCAL_INSTALL.md step 5

### ISSUE THREAD

**Issue by dmcgoldrick** [macarthur-lab/seqr#1209]
When loading VCF into Seqr it is not immediately clear that the user might need to increase the 5G memory limits in the submit.py instructions/example in the readme. 

It sure would be helpful to newer users to mention that this is settable for larger datasets. I used options --driver-memory 30G and --executor-memory 30G for one real test - a little more content there could have saved a little angst. Is there a better way to specify the resource requirements? 

under the installation instructions step 5:
https://github.com/macarthur-lab/seqr/blob/master/deploy/LOCAL_INSTALL.md

python2.7 gcloud_dataproc/submit.py --run-locally hail_scripts/v01/load_dataset_to_es.py  --spark-home $SPARK_HOME --genome-version-version $GENOME_VERSION --project-guid $PROJECT_GUID --sample-type $SAMPLE_TYPE --dataset-type $DATASET_TYPE --skip-validation  --exclude-hgmd --vep-block-size 100 --es-block-size 10 --num-shards 1 --hail-version 0.1 --use-nested-objects-for-vep --use-nested-objects-for-genotypes $INPUT_VCF

... add if you can specify also "--driver-memory [fooG] and --executor-memory [barG]"

also fix typo "Go to the projet page" :-)

Thanks again for a great tool!
Daniel

**Comment by hanars** [comment]
We have updated our recommendations for local installs so these instructions no longer exist
