### ISSUE TITLE
Unable to perform custom search engle exome

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1210]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening
Unable to do custom inheritance in family AAO in engle exomes. Getting the following error: "DSL class 'None'does not exist in query."

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...
https://seqr.broadinstitute.org/variant_search/results/40a6af929db66ba7782979493d1a8034?page=1&sort=cadd

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?

Family AAO Engle Exome Project

**Screenshots**
![Screen Shot 2020-03-05 at 3 15 40 PM](https://user-images.githubusercontent.com/41243189/76022045-6784a980-5ef4-11ea-82fe-d0de9112a547.png)

**Comment by hanars** [comment]
It looks like you specified a custom affected status but did not specify an inheritance mode or expected allele counts. While this error is certainly very opaque and we should make it more descriptive, I don't think that is what you are intending. Here is a version of that search wth de novo specified, and it works fine: https://seqr.broadinstitute.org/variant_search/results/a4bd952e7a860c7264435832393549cd?page=1&sort=cadd

**Comment by juliejurgens** [comment]
Ah, apologies; my mistake. Thank you for your help!
