### ISSUE TITLE
"transcripts" error upon attempted retrieval of tagged variants

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1212]
**Describe the bug**
Hi Hana, I'm attempting to download a list of 29 novel gene/phenotype tagged variants from engle exome project and am getting an error reading, "transcripts."

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0378_engle_exome/saved_variants/Tier%201%20-%20Novel%20gene%20and%20phenotype

**Scope of the bug**

In engle exome project

**Screenshots**
![Screen Shot 2020-03-06 at 3 01 32 PM](https://user-images.githubusercontent.com/41243189/76118218-6a969d00-5fbb-11ea-8914-8e00097eb96b.png)

**Comment by hanars** [comment]
this is fixed now
