### ISSUE TITLE
Staff List ANVIL Metadata

### ISSUE THREAD

**Issue by shall48** [macarthur-lab/seqr#1232]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening

I am trying to access the seqr ANVIL metadata for CMG_Sankaran_Exomes, but when I try to download it, it gives me an error message. This information is for a grant, so it is of somewhat high priority.
**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?
The issue is in this one project
**Screenshots**

**Comment by hanars** [comment]
please provide a complete link to the page where the error is occurring

**Comment by shall48** [comment]
https://seqr.broadinstitute.org/api/staff/anvil/R0393_cmg_sankaran_exomes

**Comment by hanars** [comment]
This is fixed now
