### ISSUE TITLE
FATAL: database "seqrdb" does not exist

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#1240]
**Describe the bug**
Unable to log in to seqr because of the above fatal error: FATAL: database "seqrdb" does not exist

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/login

**Scope of the bug**
Within my login. not sure if others experiencing the same.

**Screenshots**
![Screen Shot 2020-04-07 at 9 21 55 AM](https://user-images.githubusercontent.com/41243189/78674306-6955da00-78b1-11ea-94fe-c9787e4c2c65.png)

**Comment by hanars** [comment]
seqr is now working again, thanks for letting me know!
