### ISSUE TITLE
Edit Collaborator

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1241]
Generally editing collaborators seems like a function that sometimes works for some and not others - meaning, I hover over the edit icon and sometimes I can click and other times I cannot.  Specifically right now I am trying to make "David Harris - david.harris2@childrens.harvard.edu" a manager in our CMG_Walsh_Exomes_PMG cohort but am unable to click on the pencil edit icon - it just doesn't let me click on it.  Can you resolve this or change him to a manager for me?  Thanks! Jen

![image](https://user-images.githubusercontent.com/60754044/78724442-7bf50100-78fb-11ea-881d-51441e80ba3c.png)

**Comment by hanars** [comment]
I have updated him and should have fixed the bug, let me know if this happens again

**Comment by JenPartlow** [comment]
?Thanks so much!


________________________________________________
Jennifer Partlow, MS, CGC
Licensed Genetic Counselor and Research Coordinator
The Walsh Lab, Boston Children's Hospital
jennifer.partlow@childrens.harvard.edu
T: 617-919-2865 F: 617-919-2300
www.walshlab.org
________________________________
