### ISSUE TITLE
Seqr reporting o/e as LOEUF

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1244]
**Describe the bug**
Seqr reporting o/e as LOEUF in LOF constrained genes.

Will this affect LOF constrained status in seqr? This example shows a gene listed as LOF constrained in seqr but not in gnomad. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/family/F023641_mc5100/MatchBox%20(MME)
https://gnomad.broadinstitute.org/gene/ENSG00000137804?dataset=gnomad_r2_1

**Scope of the bug**
Spot checked other LOF constrained genes and found the same issue.

**Comment by hanars** [comment]
Can you please explain more? When you hover the LOF constraint label/ click into the gene it shows both o/e and pLOF and they seem to match with those reported in gnomad...

**Comment by stephditroia** [comment]
For family MC5100, NUSAP1 LOF constraint label hover reports pLi: 0.04567 **louef: 0.3018**. gnomAD pLI = 0.05 o/e=0.3 and **louef = 0.6**. pLi is the same but .3 to .6 difference in louef. I think o/e is being reported as LOEUF in seqr. 

LOF constraint hover,  (**louef: 0.3018**, pLi: 0.04567): ![image](https://user-images.githubusercontent.com/44381119/79150780-5488b300-7d97-11ea-80ad-4d73e24ee32a.png)

**Comment by hanars** [comment]
You were right! I've fixed it, that gene now is reporting loeuf as 0.59

**Comment by stephditroia** [comment]
Hey Hana - Do you know what the threshold for a LOF CONSTR tag is?

**Comment by hanars** [comment]
Yes it is Loeuf <  0.35. For missense it is z-score > 3 or if it is one of the top 1000 constrained genes
