### ISSUE TITLE
Blank screen after variant tag display

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1257]
Good day, 
After clicking on most any Variant Tag group within any of our Walsh Lab cohorts to display all those variant tags, there is a spinning circle and then blank screen. 
Thanks for your help ~ Jen

![image](https://user-images.githubusercontent.com/60754044/79891152-997f9b80-83ce-11ea-88ab-a5c8a8c7a10f.png)

![image](https://user-images.githubusercontent.com/60754044/79891226-b025f280-83ce-11ea-8aab-b32b8797624e.png)

**Comment by hanars** [comment]
Thanks for letting me know. Please provide link(s) to the page(s) where the issue is occurring. Thank you

**Comment by JenPartlow** [comment]
Hi Hanars, 
It was happening to me in multiple places yesterday but seemed not to be a problem for Stephanie today- she tried it in our meeting together earlier.  

I just tried it again and they seem to be loading eventually now - I click on the two below for example, they try to open but then go to a blank screen.  Yesterday they weren't loading even after refreshing several times and going out and trying again.  Today they are working after refreshing once at least.  So I guess it is just being finicky and is not specific problem.  
Thanks!
Jen

https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/Sanger%20in%20progress

https://seqr.broadinstitute.org/project/R0532_cmg_walsh_exomes_pmg/saved_variants/Sanger%20in%20progress

**Comment by hanars** [comment]
Thanks for the update. Unfortunately theres not much I can do to fix it since it seems to be working now, so I'm going to close out this issue. However, feel free to reopen it if you notice it again
