### ISSUE TITLE
IGV not showing 1 family member

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1262]
Happy Friday! 
It seems like the probands' reads are not loading in IGV for these most all these variants tagged: 

https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/Send%20for%20Sanger%20validation

![image](https://user-images.githubusercontent.com/60754044/80261553-bd561200-8658-11ea-8905-f0e83e53507f.png)

Thanks!
Jen

**Comment by JenPartlow** [comment]
Proband is WAL_MC25800_MC25801

**Comment by hanars** [comment]
@mike-w-wilson do we have read data for the proband?

**Comment by mike-w-wilson** [comment]
I cannot find the sample in terra and let Katie know.

**Comment by mike-w-wilson** [comment]
Katie informed me IGV is not available for this sample due to high chimera rate after hg38 realignment.

**Comment by JenPartlow** [comment]
Thanks all
