### ISSUE TITLE
Unable to edit collaborator status

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1264]
Good morning, 
There are several of our project collaborators that I am unable to edit their status - in that I hover over the pencil/edit icon with my mouse on the project lage and it does not change to a hand to become "clickable".  Specifically, I am interested in being able to edit Ganeshwaran Mochida in all CMG_Walsh_Exome cohorts - the link and screenshot for the CMG_Walsh_Exome_PMG cohort are below for example.  However, there are several others that I cannot edit also and am not sure why there are some that I can and others  cannot. 
Thank you - Jen

https://seqr.broadinstitute.org/project/R0532_cmg_walsh_exomes_pmg/project_page

![image](https://user-images.githubusercontent.com/60754044/80382807-bd305f00-8870-11ea-9ee0-6c50fa407bc6.png)

**Comment by hanars** [comment]
Hi Jen,

Thanks for letting me know. This is incredibly difficult for me to debug as I am not seeing this issue. Do you know what browser people experiencing the problem are using? Can you confirm that the pencil icon is being shown to all of them? 

Thanks

**Comment by JenPartlow** [comment]
HI Hana
I am experiencing this problem, am using chrome and do see he pencil and trash icons for all collaborators, as in my screenshot.  Specifically on the CMG_Walsh_Exome_PMG cohort page, I cannot edit: 

Dilenny Gonzalez
Becky Andersen
Sattar Khoshkhoo
Edward Stronge
Ganeshwaran Mochida
Chris Walsh (PI)
myself

It is not always the same people in other cohorts.  I wondered if it was because some one else (ie another manager) added them, or the Broad added them when the cohort was released, and so I can't change them.  

I do wish to be able to edit all our users/Collaborators in each cohort, and there are some that need to be removed, since they no longer work with us but I can't delete them (in other cohorts).

**Comment by hanars** [comment]
Thanks, that was really helpful! I am now able to recreate your issue, and will hopefully have it fixed this week

**Comment by JenPartlow** [comment]
Many many thanks!

**Comment by hanars** [comment]
Hi Jen, this should all be working now. Let me now if you have any more issues

**Comment by JenPartlow** [comment]
perfect - thank you!
