### ISSUE TITLE
Phenomecentral matches on phenotype only 

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1267]
**Describe the bug**
Several phenomecentral matches in 2020 have been on phenotype only. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0455_cmg_walsh_exomes_lispac/family_page/F023710_pac2800/matchmaker_exchange

**Scope of the bug**
I am seeing this on other matchmaker submissions that have generic phenotypes. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/80403553-c3810400-888d-11ea-8788-8b7d92d63ba5.png)

**Comment by hanars** [comment]
We sadly can't control how other MME nodes choose to return matches. They have chosen to return matches that are phenotype=only for their own submssions that are phenotype only
