### ISSUE TITLE
Adding BAM paths on local on-prem install

### ISSUE THREAD

**Issue by samarthaFFM** [macarthur-lab/seqr#1271]
Hi @hanars and @bw2, 

I wish to get the IGV reads on my locally installed SEQR instance and as in the READVIZ instructions, create the .tsv file with the absolute path of the BAM file on my mounted drive along with the individual IDs. However I have the following issue - 

Error updating 01-067-01: /is3/js_prismes/tests/test_scratch/fam061-fam069/fam067/dna-seq-gatk-variant-calling-prismes_wes/recal/01-067-01-s47.bam url is a path but no host is specified (400)

I have also edited the settings.py file to the following - 

# Readviz
READ_VIZ_BAM_PATH = ''
READ_VIZ_CRAM_PATH = ''

Could you please help me resolve this? Thanks,

I also tried : file:///is3/js_prismes/tests/test_scratch/fam061-fam069/fam067/dna-seq-gatk-variant-calling-prismes_wes/recal/01-067-01-s47.bam

but it didnt work either.

**Comment by hanars** [comment]
READ_VIZ_BAM_PATH and READ_VIZ_CRAM_PATH are deprecated settings that are no longer used. Can you please make sure you are using the latest version of code from master?

**Comment by samarthaFFM** [comment]
Hi @hanars , 

I have Seqr v1.0 installed which is not current, is there a different way to use READVIZ in the latest version? I will get on to that, thanks.

**Comment by samarthaFFM** [comment]
Hi @hanars 

Before updating SEQR, is it still possible that I can use the old settings and configure a local bam path, I would really appreciate that, thanks.

**Comment by hanars** [comment]
Readviz does not work at all locally in that version. If you update to the latest version the absolute file paths you se in your first example should work

**Comment by samarthaFFM** [comment]
Ah okay, thank you, then I will get on to updating the Seqr instance then.

**Comment by samarthaFFM** [comment]
Thank you @hanars , I will have a look and try to gather a fix for my old version. Sorry about taking time on this!
