### ISSUE TITLE
Data for SSH_L_037 missing 

### ISSUE THREAD

**Issue by englandeleina** [macarthur-lab/seqr#1272]
**Describe the bug**
Conducting a seqr search for this family and seems data on one proband is missing

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0379_ogrady_wes/family_page/F021149_ssh_l

Example search:
https://seqr.broadinstitute.org/variant_search/results/73ed38beb52218f673a053ae6dc57114?page=1&sort=pathogenicity

**Scope of the bug**
Just this project

**Screenshots**

**Comment by hanars** [comment]
@mike-w-wilson do you know why that proband is missing?

**Comment by mike-w-wilson** [comment]
I looked in JIRA and the sample is not in the callset request. I'm guessing it failed some filter.
