### ISSUE TITLE
'Analysed By: +' and 'Assigned Analyst' functionality for non-managers

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1274]
**Is your feature request related to a problem? Please describe.**
Walsh group has requested non-managers to have ‘Analyzed by +’ and ‘Assigned Analyst’ functionality on the family page to help their workflows. 

**Describe the solution you'd like**
Editability of these features for all users. Stephanie has asked all CMG analysts and everyone agrees that this will be useful seqr-wide.

**Comment by hanars** [comment]
This is done now
