### ISSUE TITLE
Display of read depth and AB

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1313]
**Describe the bug**
AB and read depth not displayed in hom ref cases in VCGS exomes and genomes cohort. From KC, I learned that this was a Hail bug, but that we have now updated our version of hail. However, not having the GQ and read depth displayed when homozygous for the ref allele can impede analysis. We discussed this at a collaborator meeting and Anne suggested putting in a ticket to reload these 2 projects. This is not very high priority. Please let me know if you need to discuss in case this will be very time consuming or for another reason.

**Link to page(s) where bug is occurring**
Here's one example- https://seqr.broadinstitute.org/project/R0405_cmg_vcgs_genomes/saved_variants/variant/SV0022110_2189052944_r0405_cmg

**Scope of the bug**
Many cohorts affected, but request to fix the VCGS genomes and exomes cohorts only.

**Screenshots**
![Screen Shot 2020-06-02 at 2 28 29 PM](https://user-images.githubusercontent.com/37872186/83556120-58a29880-a4dd-11ea-8333-10c3f05b9dfd.png)

**Comment by hanars** [comment]
@ch-kr do you have any context on this?

**Comment by ch-kr** [comment]
There was an issue with homozygous reference genotypes being displayed as "NO CALL" last year, but that was fixed when we moved to the new pipeline/from hail 0.1 to hail 0.2. I actually don't see an issue with that family/screenshot. The GQ is being displayed for the homref calls, and the read depth is available in the hover over.

**Comment by lynnpais** [comment]
I'll speak to the collaborator and convey this. CLosing this issue for now.
