### ISSUE TITLE
Error loading IGV tracks

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1319]
**Describe the bug**
Error loading maternal IGV track for the COL4A1 variant in FAM174

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0064955_13110209409_f027917_

**Scope of the bug**
Case specific

**Screenshots**
![Screen Shot 2020-06-04 at 9 22 54 AM](https://user-images.githubusercontent.com/37872186/83762000-0a100e00-a645-11ea-9799-dcc7c5ee0c6f.png)

**Comment by hanars** [comment]
@mike-w-wilson the mother in this family (VCGS_FAM174_534_D1) does not appear to have IGV hooked up at all

**Comment by mike-w-wilson** [comment]
This is now loaded.
