### ISSUE TITLE
Ancestry information

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1320]
**Describe the bug**
Request to have ancestry info loaded

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/family_page/F029379_vcgs_fam259

**Scope of the bug**
Many cohorts do not have this yet. Above is one example from the VCGS cohort.

Anne suggested to put this ticket in as this info is very helpful in analysis. Thanks.

**Comment by hanars** [comment]
@mike-w-wilson do you know why we don't have QC pipeline output for this project/ family?

**Comment by lynnpais** [comment]
Any updates on this issue?

**Comment by hanars** [comment]
@mike-w-wilson were you able to find anything?

**Comment by mike-w-wilson** [comment]
This looks like it may be a renaming issue since this data was loaded back in 2019. The qc pipeline is currently being updated to use the most recent gnomad package so I can investigate this a bit more once those updates are in.

**Comment by hanars** [comment]
Ancestry info for that family is now properly loaded, so closing this out
