### ISSUE TITLE
Clicking on Submit button on Variant search page causes family dropdown disappear

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/seqr#1334]
**Describe the bug**
When we go to the variants search page and hit 'Submit' ProjectFamiliesField component just disappears.

<img width="1285" alt="Screen Shot 2020-06-05 at 5 04 22 PM" src="https://user-images.githubusercontent.com/5591700/83922633-a5d97100-a74e-11ea-92a9-079df82e63d8.png">

Upon reloading it reappears. Do you know whats' the possible issue is? Are you experiencing or ever experienced (if you don't have it now somehow) this bug? We find it very hard to debug.

**Comment by NLSVTN** [comment]
While debugging it happens that fields.map iteration is not going on with the disappearing element (name = "projectFamilies") here:

https://github.com/macarthur-lab/seqr/blob/master/ui/shared/components/form/ReduxFormWrapper.jsx#L79

2 renderings of the element happen. First time **fields** has length 1 and it is fine, second time the length is 0.

**Comment by hanars** [comment]
there is a known bug where the search criteria gets cleared form the ui when a search fails. I will be addressing it hopefully in the next couple weeks. The larger question is why your searches are failing at all. What is appearing on the page under the search button after you hit submit the first time? Are you seeing any network requests triggered by hitting submit?

**Comment by NLSVTN** [comment]
Searches are not failing, search results are returned. If we comment out line that loads the variants, the family dropdown still disappears:

https://github.com/macarthur-lab/seqr/blob/master/ui/shared/components/panel/search/VariantSearchResults.jsx#L176

**Comment by NLSVTN** [comment]
I figured out that the root cause function for the bug is **saveSearch** function in _./shared//components/panel/search/VariantSearchFormContainer.jsx_ which calls **history.push**. Commenting out **navigateSearch** in redux/rootReducer.js prevents the element to disappear:

https://github.com/macarthur-lab/seqr/blob/master/ui/redux/rootReducer.js#L238

So, then I looked into these 2 threads:

https://github.com/redux-form/redux-form/issues/2982
https://github.com/redux-form/redux-form/issues/603#issuecomment-295043224

And reasoned to just set **destroyOnUnmount={false}** here:

https://github.com/macarthur-lab/seqr/blob/5227cb8b1c69baa5ab38c3d7481ce8fc63cad880/ui/shared/components/panel/search/VariantSearchFormContainer.jsx#L16

Which fixed the behavior. I am not sure that its the best way of solving the issue, and whether it will cause any unexpected side effects, but here is where I am at right now.

**Comment by hanars** [comment]
Thanks for looking into this! I'm glad you were able to find a fix that works for you. I will try it out on my end and I will let you know what we end up doing

**Comment by NLSVTN** [comment]
Additional comment: to avoid stuck family selection bug (after you initialize family once, then go back, and click another family, family will not be correctly selected, but instead will be stuck from the first-time initialization) I added another property - **enableReinitialize={true}** - to the very same place:

```
enableReinitialize={true}

    <ReduxFormWrapper
      onSubmit={search}
      submitButtonText="Search"
      noModal
      destroyOnUnmount={false}
      enableReinitialize={true}
      {...formProps}
    >
      {children}
    </ReduxFormWrapper>
```

**Comment by hanars** [comment]
So my intuition is actually that the value in the store is updating unnecessarily to delete and then re-add the family, which is why this is unmounting and remounting. The solution is for the store not to do that update, rather than to change the unmount behavior. If the value never disappears, this shouldn't unmount at all. I have a somewhat related ticket to this on our end so I will look into solving them together and get a more robust fix up, although it may be a few weeks so you might want to use this in the meantime

**Comment by hanars** [comment]
I believe I have fixed the underlying issue here and the fix is now available on the master branch

**Comment by NLSVTN** [comment]
Hi, 

I am very curious about the changes you made to fix the issue. Could you point me to the commit or file(s) that were changed?

**Comment by hanars** [comment]
So it was just this one-liner in how the paging was set up: https://github.com/macarthur-lab/seqr/commit/743aaae78e98272322769a0771e317472e7889e7

**Comment by NLSVTN** [comment]
Thanks a lot!
