### ISSUE TITLE
Question : missing variant for individual ?

### ISSUE THREAD

**Issue by bnouyou** [macarthur-lab/seqr#1335]
Hello,

This is something that I don't understand about the utilisation of Seqr. 
I have a sample with a known variant (deletion of 3 nucleotides). When I do the "search variants" for this sample using the criteria of the gene name, I don't find this variant.
Whereas , if I do the "search variants" on the entire project (so all samples in the project), there I see this variant. But I have the impression that this variant is not "linked" to this individual. In Seqr interface I don't have the button on the right "go to the page for the indiidual variant".
What does it mean ?

Thank you in advance for your help.

**Comment by hanars** [comment]
It probably means that you are either a) applying filter criteria in that first search that you do not mean to (i.e including expected inheritance) or b) that variant exists for some samples in the project but not the sample you are expecting

Without screenshots and more details about the searches you are doing its hard to say more

**Comment by bnouyou** [comment]
I will send your a picture by email.
Thank you.

**Comment by bnouyou** [comment]
Finally found the reason why we don't see this variant. It is not missing, but not displayed in the variant search, because of bad quality.
Thank you for your help by email.
