### ISSUE TITLE
Missing IGV reads

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1336]
**Describe the bug**
No IGV reads for 3852-4-1a

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/22-38246061-G-A/family/F013170_3852

**Scope of the bug**
Case specific

**Screenshots**
![Screen Shot 2020-06-08 at 2 57 52 PM](https://user-images.githubusercontent.com/37872186/84069408-75851300-a998-11ea-9985-c59d5a29f66f.png)

**Comment by hanars** [comment]
@mike-w-wilson can you add?

**Comment by mike-w-wilson** [comment]
This is all set.
