### ISSUE TITLE
New error in multi-family search

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1367]
**Describe the bug**
I am seeing an oddly specific error message when searching across multiple families, like `064816_pie_ogi269_000576_1`. OGI269 is not included in the search where the error is happening. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/5cdc83dee5227a6db4b9aa0b47e24fdb?page=1&sort=xpos

**Scope of the bug**
I've personally seen this in the Pierce cohort (link above) and Jen told me about a similar error in the Walsh cohort (no link, but the error was reported as `I0076924_wal_mc9800_mc9804_d1`) 

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/87326276-83cacf80-c500-11ea-9135-451fc44c4f7c.png)

**Comment by hanars** [comment]
This is fixed, and should also be fixed for the walsh group
