### ISSUE TITLE
Recessive SV search

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1368]
**Describe the bug**
A CN=0 in the proband does not show if either parent is not CN=1. Another way to put it is, if the parents are not het, seqr does not show homozygous SV in the proband as it maybe a Mendelian violation. 

Typically, seqr shows all SNVs the proband is homozygous for, regardless of parental status. This is how we get the potential UDP/ parental del flag.

Seqr must also show all homozygous SV calls in the proband, regardless of the parental status. 

**Link to page(s) where bug is occurring**
SV example: https://seqr.broadinstitute.org/variant_search/variant/prefix_104962_DEL/family/F020347_fam44
Search page: https://seqr.broadinstitute.org/variant_search/results/1ac18d09e833d72f8f8821f657cc49a5?page=1&sort=xpos

**Scope of the bug**
Across all projects with the SV search enabled.

**Screenshots**
<img width="1196" alt="Screen Shot 2020-07-13 at 3 11 43 PM" src="https://user-images.githubusercontent.com/37872186/87343662-3b6cdb00-c51b-11ea-9300-884166d3dbed.png">

**Comment by hanars** [comment]
It appears there is a bug where seqr is incorrectly handling recessive search cases where the parents has CN of 2. This is a high priority bug and I will work on getting it fixed ASAP.  @englandeleina to add example of variant not correctly returning for recessive search where CN 0 in proband and 2 in both parents

**Comment by hanars** [comment]
As a not-great workaround, if you do a custom inheritance search and change the affected status of the unaffected parents to unknown, the variant will come back

**Comment by hanars** [comment]
Recessive search is now working as expected. The original search link you put in the ticket still isn't including the variant you expected, but thats because you applied a minimum QS of 100 and the parent has a QS of 41. If you lower the QS filter you will see the variant come back as recessive https://seqr.broadinstitute.org/variant_search/results/c128f32727f3c17749af6dfcc50b48a6?page=1&sort=xpos

**Comment by lynnpais** [comment]
Thanks Hana. Sorry for my delayed response.
