### ISSUE TITLE
SV search options

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1369]
**Is your feature request related to a problem? Please describe.**
I would like to be able to search for homozygous or heterozygous CNV, rather than just dels or dups in the proband.

**Describe the solution you'd like**
It's so great to have the SV data in seqr! To maximize search results/ diagnoses, it would be helpful if we could select the exact CN such CN=0 or 1 or 3, etc in the proband. This way, we can specifically look for homozygous CNV (highly prevalent in consanguineous populations) and even override the parental status which may not always be accurate.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
Can you explain a bit more how "search for homozygous or heterozygous CNV" differ from the recessive/ dominant search options available in seqr now?

**Comment by lynnpais** [comment]
Agree, it is similar. I had discussed briefly with the other analysts, but forget the exact reasoning right now. We can ignore this request for the time being.
