### ISSUE TITLE
Clicking last page in variant search does not work: too big size error

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/seqr#1378]
**Describe the bug**
When we do variant search and then click last page (it occurs when we have over 100 pages) it crashes with the error:

**Unable to load more than 10000 variants (107900 requested)**

This does not seem right because we are not requesting that many variants but just the last page with 100 variants.

**Link to page(s) where bug is occurring**
https://github.com/macarthur-lab/seqr/blob/2d0d81bedd199d0adcca812300a64306351d4cae/seqr/utils/elasticsearch/es_search.py#L916

**Comment by hanars** [comment]
If you are fetching the 100th page of 100 results you are fetching results 10000-10100 which is just more than seqrs underlying database to handle. Seqr is not designed for viewing tens of thousands of variants, it is designed for viewing search results and we limit that to less than 10000 results. You should really be applying more filters, or at least sorts, so you can access al the variants ou need in a smaller number of results

**Comment by NLSVTN** [comment]
Yeah, thats unintuitive from the user perspective and can cause perception of a bug.

**Comment by NLSVTN** [comment]
When requesting 100th page the app is actually fetching results 1-10100, not 10000-10100 (which would be the right way and would mean fetching only 100 results).

**Comment by hanars** [comment]
only for specific types of searches such as compound het searches where we need to post process the data
