### ISSUE TITLE
F023245_he_1400  Waiting for data?

### ISSUE THREAD

**Issue by JenPartlow** [macarthur-lab/seqr#1380]
Good day, 
The analysis status of this specific family is noted as "Waiting for Data", but there does appear to be data, as I am able to do a variant search.  That said there seem to be a lot of variants.  I was just wondering if the Analysis status colored square should be changed for this family or if indeed there is some data pending (or peculiar with the existing data)?

https://seqr.broadinstitute.org/project/R0346_walsh_lab_exomes/family_page/F023245_he_1400 

thanks
Jen

**Comment by stephditroia** [comment]
Hi Jen, 
I double-checked with our pm team and there is nothing in this family (or this project, for that matter) that is waiting for data. The analysis status automatically updates when new data is loaded, but for some unknown reason this family didn't get triggered. Feel free to manually change the analysis status to the appropriate setting. 
Cheers, 
Stephanie

**Comment by JenPartlow** [comment]
?I see  - thanks!!

Jen


________________________________________________
Jennifer Neil Partlow, MS, CGC
Licensed Genetic Counselor and Research Coordinator
The Walsh Lab, Boston Children's Hospital and HHMI
jennifer.partlow@childrens.harvard.edu
T: 617-919-2865 F: 617-919-2300
www.walshlab.org
________________________________

**Comment by stephditroia** [comment]
@hanars feel free to close this issue
