### ISSUE TITLE
Missing 'gene search' link in CMG_Fleming_WES

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1381]
**Describe the bug**
The gene search hyperlink next to the gene name is missing in the CMG_Fleming_WES cohort. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/98b121e39b92fe6ad1315ca5829d2ac6?page=1&sort=xpos

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/87983620-a6cc2500-caa6-11ea-802f-6a3f5a8d9dc6.png)

**Comment by hanars** [comment]
That link was only ever (supposed to be) available on the saved variants page, nt the search page. If yuo want to change that functionalty, feel free to pen a feature request ticket
