### ISSUE TITLE
Tagging pair vs individual for compound heterozygous variants seem to require additional filtering

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/seqr#1394]
**Describe the bug**
We can tag both pair and individual variants with the same tag when we get compound heterozygous variant pair. It seems like its not right and if we have a certain tag on a pair, then we need to prevent the user from creating the same tag on an individual variants in that pair; if we have a tag on an individual variant and we assign the same tag to the second variant in the pair - both individual tags should be shifted to combined upper section tags.

**Screenshots**
<img width="1225" alt="Screen Shot 2020-07-24 at 9 59 03 AM" src="https://user-images.githubusercontent.com/5591700/88399752-5bab5e00-cd95-11ea-8f1b-175f3b23adbe.png">

**Comment by hanars** [comment]
This is not a bug, it is a design choice - there are use cases where you would want a tag on a single variant separate from the paired variant, especially if you came across that variant through a non-compound het search. Morevover, just putting the same tag on two variants doesn't mean they should be considered a pair - imagine you are going through search results and happen to tag 2 unrelated variants for review and they suddenly are paired even though they have nothing to do with each other. 

I am sorry if you find the UX unintuitive, but the workaround here is to use the tagging as it is intended, i.e. tag the pair if you want to consider them together, and tag the individual variants if you don't

**Comment by NLSVTN** [comment]
I don't think that its right, and I am definitely not talking about tagging two unrelated variants. The pair is defined as pair by VarianTag -> saved_variants ManyToMany field. Individual tagging would not involve putting them under the same pair due to the way the model is structured. Each individually tagged variant would have 2 VariantTag models created with saved_variants field of length 1. Tagging by pair would create 1 VarianTag model with 2 saved variants in saved_variants model. So, we can clearly differentiate between the two cases. 

So, the model does not deny the individual or pair tagging. I am just saying then that if you have it tagged both individually AND by as a pair - that is unnecessary duplication of tags and seems like a mistake.

The UI is pretty good and intuitive I like. it. I am actually developing further parts for seqr, thats why asking, etc.

**Comment by NLSVTN** [comment]
If we have two unrelated variants and tag them with the same tag we would get two VariantTag models, so they would not be united as a pair. But if two related variants are tagged with the same tag - they should be put under the pair, right?
