### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by jaustrie** [macarthur-lab/seqr#1395]
**Describe the bug**
When I enter my credentials into seqr an error box with 401 pops up. I thought maybe my password was incorrect so I clicked on "forgot password" and I entered in my email address so that the password can be reset. But when I clicked on "submit" another error box with 400 popped up.
![seqr2](https://user-images.githubusercontent.com/68752198/88423134-4d6f3900-cdb9-11ea-9ed0-f5645a5a7a63.png)
 I never received an email. I've tried refreshing my email and checking the spam mailbox. I would like to be able to log into seqr. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/login

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?
![seqr](https://user-images.githubusercontent.com/68752198/88422827-d2a61e00-cdb8-11ea-8fd0-585095bdfeff.png)

**Screenshots**

**Comment by hanars** [comment]
Can you try logging in again?

**Comment by jaustrie** [comment]
Hi,

I just tried logging in again and received the same error message.


Best,
Jasmine

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by hanars** [comment]
I don't see you in our user database at all. Simply being a broad member does not grant you access to seqr - had you previously received an email to set up your acccount?

**Comment by jaustrie** [comment]
Hi,

I had account through my hospital email address and I assumed when I got my
broad credentials it would automatically transfer over, my mistake. I just
tried and I am able to access seqr using my hospital email address.


Thanks,
Jasmine

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
