### ISSUE TITLE
Can't log in 

### ISSUE THREAD

**Issue by anatopf** [macarthur-lab/seqr#1398]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?

**Screenshots**

**Comment by anatopf** [comment]
log in page gives error message

**Comment by hanars** [comment]
seqr's log in should be working again
