### ISSUE TITLE
IGV read support

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1405]
**Describe the bug**
Read data missing for Gazda exomes project. I checked a few cases and they don't have reads. 

**Link to page(s) where bug is occurring**
One example- https://seqr.broadinstitute.org/project/R0383_gazda_exomes/saved_variants/family/F018948_gaz_432/Review

**Scope of the bug**
Specific to the Gazda exomes project

**Screenshots**
<img width="1178" alt="Screen Shot 2020-07-30 at 10 00 12 AM" src="https://user-images.githubusercontent.com/37872186/88931980-7ecd8600-d24b-11ea-9bdc-3e0728d5101e.png">

**Comment by hanars** [comment]
@mike-w-wilson ?

**Comment by mike-w-wilson** [comment]
I've reloaded both the gazda workspaces I could find. https://app.terra.bio/#workspaces/anvil-datastorage/AnVIL_CMG_Broad_Blood_Gazda_WES and https://app.terra.bio/#workspaces/broad-genomics-data/CMG_Broad_Gazda_BloodDisease_WES . The second was not in airtable so it was missed. I'm not positive this accounts for all the samples and I have reached out to the PM team about the missing workspace/samples.

**Comment by mike-w-wilson** [comment]
These samples were recently repatiented and were redelivered. Some are likely to move again.
