### ISSUE TITLE
Error with recessive SV saved search

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#1418]
**Describe the bug**
`local variable 'total_results' referenced before assignment' error when using the Recessive SV saved search on the Walsh_PMG project. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/34188ca1b027ce01828964f0aba0975d?page=1&sort=xpos

**Scope of the bug**
Several Walsh analysts are running into this error. I have not run into it on other projects. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/89816132-fc2eab80-db13-11ea-8161-e9febeaf9a6b.png)

**Comment by ch-kr** [comment]
Ooh, same as the Perth project: https://github.com/macarthur-lab/seqr-private/issues/899

**Comment by stephditroia** [comment]
Oh, thanks for catching this duplicate KC.

**Comment by hanars** [comment]
This is fixed now. Turns out it was only an issue for searches with no results
