### ISSUE TITLE
Prioritizing Clinvar P/LP variants

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1445]
**Describe the bug**
Can our seqr searches prioritize variants reported to be pathogenic or likely pathogenic in Clinvar, ignoring all other parameters? It currently does not, if the variant is in one of the parents and are they unaffected. In the current example, the proband has an inherited pathogenic variant. It did not come up in a dominant or recessive search, but I came across it when I set it to 'in any affected'.  

I still need to find a 2nd hit, but that's up to me and is not a seqr issue. In general, this would be very important to identify single hits in a recessive gene, where the 2nd hit could be a CNV. Also, in cases where low penetrance/ variable expressivity. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0078143_2025323347_f027640_r

**Scope of the bug**
Case specific 

**Screenshots**
<img width="1203" alt="Screen Shot 2020-09-08 at 10 45 33 AM" src="https://user-images.githubusercontent.com/37872186/92491650-76f4f000-f1c0-11ea-96a2-2db5cd293f8c.png">

**Comment by hanars** [comment]
Hi Lynn,

This is a good description of a problem but I don't know what solution(s) you are proposing. You can already sort result by "Pathogenicity", so clearly sorting alone does not solve your issue. But aside from sorting I don't know what you would want in terms of "prioritization". Are you asking to be able to specify different pathogenicity criteria for second hits? Are you asking for a saved search to look for second hits?

**Comment by lynnpais** [comment]
Hi Hana,

I am suggesting that if a variant has a P/LP tag per ClinVar, it should
come up in a dominant search, irrespective of AF, parental status, etc.

In this case, the proband and family members are heterozygous for the
ClinVar pathogenic variant. I am asking it to be included in the dominant
search results, despite the fact that it is in the parents who are
unaffected. The fact that it is pathogenic should be enough. Does this
clear things up?

Thanks for considering.

**Comment by hanars** [comment]
I'm sorry, but if you are doing a dominant search I cannot allow variants to come up irrespective of parental status. That is a really unintuitive and confusing behavior that will potentially lead to lots of noise. 

This is a really substantial change to search behavior. I think this is the kind of thing I would want all the analysts to agree on and have a very clear expectation of how it should work before I can make this sort of change

**Comment by lynnpais** [comment]
Okay I understand. The analysts agree that it is important for these
variants to show. I'll discuss with them and Alysia, and get back to you
with suggestions.

Thanks,
Lynn

**Comment by anneodonnell** [comment]
We would have to be super careful if we wanted to add a search like this as it would expose a lot of misclassified variants and also really open us up to see secondary findings which most groups don't want to see. And I agree with Hana that it would be very confusing and counter-intuitive to have variants show up that don't follow the search inheritance. Couldn't we save a pathogenic variant search for all variants (or require the proband to have an alt allele if you are least want the proband to have the variant) that are ClinVar P/LP and actually probably relax the allele frequency a lot (to pick up ClinVar risk variants), and then be careful when we run that search.
