### ISSUE TITLE
Seqr search issue

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#1460]
**Describe the bug**
Unable to perform a search

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/252f6d253af72d60d5e5b338e4868973?page=1&sort=pathogenicity

**Scope of the bug**
Multiple families within this project including CR16, CR5, CR7

**Screenshots**
<img width="1184" alt="Screen Shot 2020-09-29 at 10 12 21 AM" src="https://user-images.githubusercontent.com/37872186/94570025-5e667b80-023c-11eb-9b88-106a31f721db.png">

**Comment by hanars** [comment]
this is fixed now
