### ISSUE TITLE
Tag genes that have ClinVar path/likely path variants in them

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#210]

**Comment by evalkanas** [comment]
Would it be difficult to indicate the phenotype(s) on hover or in the gene summary information? Might be a little redundant with OMIM, but also might have more info

**Comment by bw2** [comment]
@evalkanas As far as I know, the Clinvar phenotype descriptions come from OMIM. These appear in the Gene Summary view as 

![image](https://cloud.githubusercontent.com/assets/6240170/18038452/595c9af8-6d66-11e6-871a-eb1d379bc1bc.png)
(for DMD)

Are you thinking of another way to present this info?
