### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by dridk** [macarthur-lab/seqr#221]
Hi, 

Could you provide a screenshot of the web client ? I would like to see a a brief preview before installing it .

**Comment by AndrewSkelton** [comment]
There's visuals [here](https://commonfund.nih.gov/sites/default/files/KidsFirstDataResourceWorkshopSlidesJuly2016Part2.pdf)

**Comment by bw2** [comment]
Thanks @AndrewSkelton
