### ISSUE TITLE
Filtering Numbers not adding up? 

### ISSUE THREAD

**Issue by AndrewSkelton** [macarthur-lab/seqr#225]
This may well be down to my understanding, but I'm just trying to figure out what's going on here, someone more familiar with the code base may be able to explain or point me in the right direction... 

I've got a trio that I'm analysing, and searching for compound het + moderate to high impact + high quality. I had the console open when running the query and just noticed the following:

```bash
returning mendelian_variant_search page for PIDMaster FAM31. has_gene_search = False
 mendelian_variant_search for PIDMaster - search mode: standard_inheritance 
variant_filter: {'ref_freqs': [[u'1kg_wgs_phase3', 0.01], [u'1kg_wgs_phase3_popmax', 0.01], [u'exac_v3', 0.01], [u'exac_v3_popmax', 0.01]], 'so_annotations': [u'stop_gained', u'splice_donor_variant', u'splice_acceptor_variant', u'stop_lost', u'initiator_codon_variant', u'start_lost', u'missense_variant', u'protein_altering_variant', u'frameshift_variant', u'inframe_insertion', u'inframe_deletion']} 
inheritance_mode: compound_het 
allele_count_filter:  
quality_filter: {u'vcf_filter': u'pass', u'min_ab': 25, u'min_gq': 20} 
genotype_inheritance_filter:  
    returned_by_query: 767
    passes_variant_filter: 755
    passes_quality_filters: 275
done fetching 16 variants. Adding extra info..
done adding extra info to 16 variants. Sending response..
```

So I'm wondering where the 259 variants have gone between passing the quality filters, and grabbing extra information? Is it down to what individuals the filter is applied to? i.e., 259 is the number of variants passing everything, in all individuals, however 16 is the number of hits that fits with the affected individual?

**Comment by bw2** [comment]
In this case, because it's a compound het search, there's additional filtering that happens afterward where variants are grouped by gene and those that don't have a 2nd variant in the same gene are discarded. The main code for that is at https://github.com/macarthur-lab/seqr/blob/master/xbrowse/variant_search/family.py#L225

**Comment by AndrewSkelton** [comment]
That's great, thanks for the link!
