### ISSUE TITLE
dbNSFP/CADD Annotations are not not shown after VCF being annotated by VEP plugins 

### ISSUE THREAD

**Issue by huangk3** [macarthur-lab/seqr#232]
Hi,

I annotated my vcf using the following command:
perl ${variant_effect_predictor}/variant_effect_predictor.pl --everything --vcf --allele_number --no_stats --cache --offline --dir ${vep_cache} --force_overwrite --cache_version 81 --fasta ${ref}/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --assembly GRCh37 --tabix --plugin LoF,human_ancestor_fa:${ref}/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15 --plugin dbNSFP,${ref}/dbNSFP2.9.3.gz,Polyphen2_HVAR_pred,CADD_phred,SIFT_pred,FATHMM_pred,MutationTaster_pred,MetaSVM_pred,REVEL_score -i ${invcf} -o ${outvcf}

The annotated vcf looks like:
![screen shot 2017-05-04 at 10 24 12 am](https://cloud.githubusercontent.com/assets/11340748/25708631/0ff2f37c-30b5-11e7-80fb-1b7b2ce64e01.png)

Then I loaded the vcf into seqr, but the CADD score and dbNSFP annotations were not shown up.
![screen shot 2017-05-04 at 10 20 07 am](https://cloud.githubusercontent.com/assets/11340748/25708928/ecd8f458-30b5-11e7-9ee1-1be0b75ce180.png)

The seqr code was pulled from the repository a couple days ago. Thanks

**Comment by AndrewSkelton** [comment]
Hi, 

I'm seeing exactly the same issue, and can't seen to figure out why the annotations aren't showing up. like @huangk3 I cloned the repo a couple of days ago. Can any of the devs comment on this issue? Happy to provide more details on my setup / assist in debugging. 

Thanks, 

Andrew
