### ISSUE TITLE
Seqr Not using Annotation from VCF. 

### ISSUE THREAD

**Issue by AndrewSkelton** [macarthur-lab/seqr#245]
Hi, 

I've installed seqr using a mix of the centos install scripts and the Kubernetes config scripts. It appears that Seqr is not using the pre-annotated VCF to pull in annotation on the queries, but rather the dbNSFP database loaded in via `load_dbnsfp`. 

I don't believe I've missed any steps during initialisation, and my VEP annotated VCF is correct, according to the example command via the OSX legacy scripts. 

Can I get some clarification as to if this is by design or unintentional? 

**Setting up reference data:**
```
./manage.py load_resources
./manage.py load_reference
./manage.py update_omim #With API key
./manage.py update_gencode
./manage.py update_human_phenotype_ontology
```

**Add example project:**
```
./manage.py add_project 1kg
./manage.py load_project_dir /data/Software/data/projects/1kg
./manage.py generate_pedigree_images 1kg
./manage.py add_default_tags
./manage.py load_project 1kg
./manage.py load_project_datastore 1kg
```

Using the above commands, everything appears to work but doesn't pull in consequence predictions (polyphen, etc).

**Edit:**
 ~~After running `load_dbnsfp`, seqr adds the consequence prediction.~~ 
After running `load_dbnsfp` with dbNSFP 2.9.3, there's still no consequence prediction showing. The annotations I see missing are the things that should be pulled in by the annotated VCF. Additionally, this is observed on the 1KG toy dataset provided. The CADD scores are showing up after running `load_CADD`. 

So I'm not sure if I'm missing something here, if it's by design? - I thought that the idea was that Seqr used the annotations from the VCF file instead of relying on an instance of a local dbNSFP database. 

Any suggestions as to where I'm going wrong, or the cause? 

Thanks, 

Andrew

**Comment by bw2** [comment]
Hi Andrew, this looks like a bug. 
Let me look in to it..

**Comment by AndrewSkelton** [comment]
Hi @bw2 , Thanks a lot for acknowledging it! If there's anything I can do on my end to help figure things out, don't hesitate to ask!

**Comment by AndrewSkelton** [comment]
Interestingly, I tried out dbNSFP2.9 as recommended in the bundle, and it didn't work either. Read in fine using `load_dbnsfp`, but didn't populate the view. 

Also, the CQ field in my VEP(88) annotated VCF contained all of the expected fields (as required [here](https://github.com/macarthur-lab/seqr/blob/8eacc878a187e85993fb202abd1551d5fd123a79/xbrowse/annotation/annotator.py#L145)), but with a few additional fields, and I was wondering if this would cause an issue if they're in a different order? Or is there a dictionary somewhere to deal with that? - I don't think this is the root of the current bug, as the 1KG data is showing the same issue.

**Comment by AndrewSkelton** [comment]
@bw2 - A few modifications but that did the trick! Thanks a lot! The only thing that seems to be missing is the dbSNP rsID. Is that a quick fix? 

A couple of changes that might be worth considering:

* Strip the `">\n` from the initial parsed CQ column names, as different versions of VEP / caches will annotate in a different order. 
* For no reason whatsoever, the consequence predictions are delimited by `&` in my VEP output. Not sure how you'd make that generic other than checking the second character of the first populated entry longer than 2 characters maybe?

Thanks!
