### ISSUE TITLE
Allele balance filtering not working 

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#321]
de novo searching seems to be broken in the CMG_Estonia_WGS project - I think it's an issue with the allele balance filtering.

https://seqr.broadinstitute.org/project/Estonian_WGS/family/HK102/mendelian-variant-search#search/f616783f/results
The HIST1H1E de novo variant is the pathogenic variant in this case - good GQ and AB
If I search with AB <10% filtered, I get no variants
If I set AB to 0, then I get variants
but allele balance is 32% for this variant.

**Comment by bw2** [comment]
Fixed
