### ISSUE TITLE
gnomAD-beta gene page link in seqr

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#326]
Rather than a link to GTEX under each gene name, I'd love to have a link to the gene on gnomAD-beta. We have a GTEX link on the gene page already.

**Comment by anneodonnell** [comment]
![image](https://user-images.githubusercontent.com/10407888/37692316-282920ee-2c8e-11e8-8275-d3111d6f98aa.png)

**Comment by bw2** [comment]
What do you think about 
![image](https://user-images.githubusercontent.com/6240170/37714973-36616406-2cf1-11e8-95d1-dcb43aac0f6e.png)
