### ISSUE TITLE
Tag autosave

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#327]
Lynn thinks it would be nice if the tag link didn't require you to click the save link. I'm just passing it on in case this would be an easy change.

**Comment by hanars** [comment]
We added "shortcut" tags for review and exclude that don't require any additional clicking. For other tags, you still need to explicitly save, but it will warn you if you try to exit out without saving the changes you made. 

I'm going to close this issue as I feel like that resolves the problem. @lynnpais feel free to create a new ticket if you find that doesn't address your issue
