### ISSUE TITLE
Custom inheritance "2 or more alt alleles" filter not working as expected

### ISSUE THREAD

**Issue by oleraj** [macarthur-lab/seqr#334]
Hi team,

We noticed when  that we often see genes in the results of a custom inheritance "2 or more alt alleles" search with only a single variant.   Here are a couple examples (RNF19B and FOXO6 only have one variant each):

<img width="941" alt="screen shot 2018-03-23 at 2 31 12 pm" src="https://user-images.githubusercontent.com/10860409/37847336-e5e7e4ca-2ea6-11e8-99c2-4437d485279e.png">

It seems like there should be a second check after applying the filters to make sure that all of the genes still have 2 or more alt alleles passing filters, and if not to not report the (single) variant for that gene.

Thanks.

**Comment by hanars** [comment]
"2 or more alt alleles" refers to whether or a given individual has 2 copies of the alt allele for the specific variant in their own genome, i.e. if they are homozygous. It sounds like you are trying to search for genes which have multiple variants in them, which is not currently supported in seqr
