### ISSUE TITLE
make it easy to tag multiple variants with the same tag

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#339]
ideally same UI as gmail:

![image](https://user-images.githubusercontent.com/6240170/38118277-ae26d358-3387-11e8-8228-3c96a453d40c.png)

**Comment by hanars** [comment]
The "shortcut tags" for review and excluded in the new saved variant UI should accomplish the goal of this ticket if not the suggested implementation. Is that good enough for now, or do we want to revisit this idea and add it to the new UI as well?

**Comment by hanars** [comment]
Closing this out as I feel that the review and exclude shortcut tags are the only ones we would ever really want to bulk add. If we decide we need more/ different bulk edit capacity we can open a new ticket that aligns more with the new UI design
