### ISSUE TITLE
Multiple genes associated with variant

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#356]
When there are multiple genes annotated with the variant - for example, a variant is a missense in a gene but upstream of a gene and downstream of another variant - is there a way to highlight the gene that has the "worst" annotation - the annotation that is listed for the variant (which we can see if we click on the variant type but then I forget and start looking at the wrong gene sometimes).

**Comment by hanars** [comment]
@bw have you addressed this?
