### ISSUE TITLE
Dashboard page variant information

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#357]
If you are still supporting the variant page, it would be nice any variants where a discovery tag is tagged were listed somewhere on the project dashboard page. It might also be nice to be able to see how many of various tags are tagged if there was a way to show this without taking up too much space.

**Comment by hanars** [comment]
Hey @anneodonnell when you say "project dashboard page" do you mean the dashboard page with all the projects (https://seqr.broadinstitute.org/dashboard) or the dashboard page for a specific project (https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page)?

**Comment by anneodonnell** [comment]
I'd like to have some of the details from this page on the dashboard collapsed view page - specifically the gene name when a diagnosis is found and the brief clinical description. But I apparently meant the old Family Page - example below. I definitely have trouble remembering the page names.

https://seqr.broadinstitute.org/project/CMG_Estonia_WES/families


On Jun 19, 2018, at 5:49 PM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @anneodonnell<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_anneodonnell&d=DwMFaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=Wv3d42n1BSuPhalZ66lGyu-eOKlsBFMKyQVEAg1Jd8E&s=K0D8TvlYnpm7_oJAqToCIqLNf9fBOYK_Mdt8_RL-ioU&e=> when you say "project dashboard page" do you mean the dashboard page with all the projects (https://seqr.broadinstitute.org/dashboard<https://urldefense.proofpoint.com/v2/url?u=https-3A__seqr.broadinstitute.org_dashboard&d=DwMFaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=Wv3d42n1BSuPhalZ66lGyu-eOKlsBFMKyQVEAg1Jd8E&s=ItuyXybbDLuKqnZYYZJOyHuF37cbeMtOARMOrKUHDSc&e=>) or the dashboard page for a specific project (https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page<https://urldefense.proofpoint.com/v2/url?u=https-3A__seqr.broadinstitute.org_project_R0384-5Frare-5Fgenomes-5Fproject-5Fgen_project-5Fpage&d=DwMFaQ&c=qS4goWBT7poplM69zy_3xhKwEW14JZMSdioCoppxeFU&r=ak8ysc_9yK8rk3siEdJ1WFzU3KsXr3xkoceKxPPY3K9PbTmoR7jq0mejLGmw9Ytl&m=Wv3d42n1BSuPhalZ66lGyu-eOKlsBFMKyQVEAg1Jd8E&s=hF961xB2nTriI4pT6016oq7gQNJJDZ1ZhfLAmt5aazY&e=>)?

-
