### ISSUE TITLE
Formating suggestion: search method

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#363]
At the top of the variant search page, consider indenting type of recessive that are contained in recessive search (because collaborators sometimes get confused): 

Recessive
       Homozygous recessive
       Compound het
       X-linked recessive
Dominant
De novo dominant

![image](https://user-images.githubusercontent.com/10407888/38762113-9a82faae-3f56-11e8-84bc-67cea7208f95.png)

**Comment by zmcv** [comment]
A tooltip on hover that explains the parent/child categories might also be useful.
