### ISSUE TITLE
Create custom download for variants with KOMP tags

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#364]
We would like to be able to output from seqr all variants - including cohort, family info, date of tag - for each variant with a KOMP tag - to submit these every few months to the Knockout Mouse Project (KOMP). Having it download into the progress report format would be great - but across all projects and only variants with the KOMP tag and with the date the KOMP tag was added. We can download the entire list (it should never be huge) and just pick the ones that are new from the last download. I'd like to do this every month or two once we have a system in place.

**Comment by hanars** [comment]
Available at https://seqr.broadinstitute.org/staff/komp_export
