### ISSUE TITLE
Variant tag download link times out when there are a moderate number of variants

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#367]
Download times out for this list of 41 variants: https://seqr.broadinstitute.org/project/manton_orphan-diseases_cmg-samples_exomes_v1/variants/Send%2520for%2520Sanger%2520validation?download=csv

https://seqr.broadinstitute.org/project/manton_orphan-diseases_cmg-samples_exomes_v1/variants/Send%20for%20Sanger%20validation

![image](https://user-images.githubusercontent.com/10407888/38956454-a0138b14-4325-11e8-9493-42d9429f0169.png)

**Comment by hanars** [comment]
The new saved variants page now works for this: https://seqr.broadinstitute.org/project/R0303_cmg_manton_exomes/saved_variants/Send%20for%20Sanger%20validation
