### ISSUE TITLE
hg19 link is generated with hg38 coordinates

### ISSUE THREAD

**Issue by zmcv** [macarthur-lab/seqr#370]
When both hg38 and hg19 coordinates are given for a variant, the link to the hg38 coordinates is correct but the hg19 link is generated with the hg38 coordinates.

Example in KMT5C:
> chr19:55343800
> http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&highlight=hg38.chr19:55343800-55343800&position=chr19:55343790-55343810

> hg19: chr19:55855168 
> http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&highlight=hg19.chr19:55343800-55343800&position=chr19:55343790-55343810

**Comment by hanars** [comment]
Hey @zmcv could you add a link to a saved variant/ variant search page in seqr where you are seeing this
