### ISSUE TITLE
Add additional sorts for cases

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#377]
Hi, 

1. It would be incredibly useful for the Analysts to be able to sort cases by ((i) date data was loaded in seqr, (ii) cases analyzed, and (iii) pending analysis. Items ii and iii would depend on whether or not the Analyst used the, 'Analyzed By' tag.

~~2. Analyzed By tag- request to separate them in to two- one for collaborators (some of my collaborators have members in their teams who use this tag for tracking purposes) and another for the CMG Analyst.~~

**Comment by hanars** [comment]
Splitting part 2 of this request into its own ticket: https://github.com/macarthur-lab/seqr/issues/427
