### ISSUE TITLE
GeneSearch improvement

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#392]
Short term, would it be possible to hardcode some filters into GeneSearch? Filter status = PASS, GQ >= 20 and AB >= 5 would work. Right now most of the variants that come up in gene search are not PASS and it is too much to wade through. 

Longer term it would be nice to have options but I'll create a separate issue for this.

**Comment by hanars** [comment]
Will be solved as part of https://github.com/macarthur-lab/seqr/issues/393
