### ISSUE TITLE
kubernetes deployment fails because file is currently missing in repo

### ISSUE THREAD

**Issue by monkollek** [macarthur-lab/seqr#407]
On deployment the seqr pod remains in the ContainerCreating status when you type 
kubectl get pods

This is because the secret "gcloud-client-secrets" is missing. Upon inspection of the script 
https://github.com/macarthur-lab/seqr/blob/master/deploy/utils/deploy_utils.py#L613

The file deploy/secrets/shared/gcloud/client_secrets.json is currently missing in the repo and so the secret is never created 
https://github.com/macarthur-lab/seqr/blob/master/deploy/utils/deploy_utils.py#L615-L617

and volume cannot be mounted
https://github.com/macarthur-lab/seqr/blob/master/deploy/kubernetes/seqr/seqr.local.yaml#L56-L58

I have commented out the necessary lines in
https://github.com/macarthur-lab/seqr/blob/master/deploy/kubernetes/seqr/seqr.local.yaml
to get it to work

**Comment by bw2** [comment]
@monkollek We need to document this better (not sure where the best place is), but the local secrets are intended to be examples of the set of secrets files you need, and then people are supposed to create secrets files based on the details of their instance (eg. https certificates based on the domain name they're using, matchbox tokens, omim key, postmark mail service key, etc.)

**Comment by bw2** [comment]
@monkollek I need to test this, but when client_secrets.json isn't found, it might work to just create a dummy secret with the same name (gcloud-client-secrets) by running
```
kubectl create secret generic gcloud-client-secrets
```

**Comment by monkollek** [comment]
@bw2 thanks for fast response. You actually do have (minimal) documentation
https://github.com/macarthur-lab/seqr/blob/master/deploy/kubernetes/README.md

I was thinking at the least to edit it so it works even with dummy secrets as it's a lot better than the deployment not working.
