### ISSUE TITLE
UniProt link on gene page does not work

### ISSUE THREAD

**Issue by zmcv** [macarthur-lab/seqr#422]
The link to UniProt on the gene view page does not work. It generates a link of the format `http://www.uniprot.org/uniprot/[GENE]` (e.g., `http://www.uniprot.org/uniprot/TYR`), which results in a 404.

The generated link should go to the gene search page (`http://www.uniprot.org/uniprot/?query=TYR&sort=score`) or protein page (`http://www.uniprot.org/uniprot/P14679`).

**Comment by bw2** [comment]
Fixed by a54c7d7ad56720cd785de5d6cbb7cafadf62a639
