### ISSUE TITLE
RGP specific project fields

### ISSUE THREAD

**Issue by hanars** [macarthur-lab/seqr#431]
We are currently overloading the "family description" field in RGP with all the survey results. We actually want to be able to have a short description for these cases as well, so we should add another field to capture the long survey results

Additionally, we should have some sort of "assignee" field that allows people to mark who is currently working on a case within rgp and assign it over to others.

These seem pretty specific to RGP so we could try to add them in a way where they ony exist for that one project.  Much easier would be to just add them to all projects. A hybrid approach might be to add them to all projects but only show them to our internal users so we don't need to worry about collaborators getting confused 

cc: @bw2 @anneodonnell

**Comment by anneodonnell** [comment]
We decided to move the survey info into the notes field so we don’t need this anymore. Can be closed.
