### ISSUE TITLE
AR analysis error

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#464]
Hi there, I'm running an AR analysis for one of our families (https://seqr.broadinstitute.org/project/Engle_WGS_900/family/137/mendelian-variant-search) and getting an error message stating that too many variants are coming up in the search. The same happens if I try searching for compound heterozygous hits only.  Thanks very much for looking into this!

**Comment by hanars** [comment]
If you are getting too many results, I would recommend applying some additional filters (e.g. severity, frequency, quality) to narrow down the results to a manageable number

**Comment by juliejurgens** [comment]
Hi, thanks very much for your reply! I had this concern because I was using identical filters for months before this without having any issues, and now suddenly this error message has begun appearing. Is it possible that adding the manta calls to our dataset is just increasing the variant count to the point where we can't do standard AR analysis, and if so, is there a way around that?  Thanks!

**Comment by hanars** [comment]
Hi Julie, is this still an issue?
