### ISSUE TITLE
Update Edit Dataset form to remove source file path

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#478]
https://github.com/macarthur-lab/seqr/pull/477#pullrequestreview-138760867
removed dataset path validation steps because they require an updated client_secret.json for automatic gcloud auth. 

In retrospect, another (probably better & more accurate) option is to get rid of this field in the form and have the code look in the `index_operations_log` which gets updated by the seqr-hail pipeline when it finishes loading a dataset. 
index_operations_log has `index_name` and `source_file` fields (as well as dates, etc.)

**Comment by hanars** [comment]
We should use index metadata for this
