### ISSUE TITLE
X-linked searches should allow for het. male genotypes 

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#484]
![image](https://user-images.githubusercontent.com/6240170/43056166-a5ca06e0-8e08-11e8-86d8-c94cea5abed8.png)

Treat  G/G (father)    G/A (mother)    G/A (son)  as X-linked recessive to allow for genotyping error in male sex chromosomes. 
Show “WARNING: heterozygous male”

**Comment by bw2** [comment]
and we should only add the warning if the variant is outside the PAR region.

**Comment by hanars** [comment]
How do you determine if the variant is outside the PAR region?

**Comment by bw2** [comment]
The intervals are
```
GRCh37:
X: 60001-2699521
X:154931044-155260561
Y:10001-2649521
Y: 59034050-59363567
```
and
```
GRCh38:
X:10001-2781480
X:155701383-156030896
Y:10001-2781480
Y:56887903-57217416
```
taken from
https://raw.githubusercontent.com/hail-is/hail/master/src/main/resources/reference/grch37.json
https://raw.githubusercontent.com/hail-is/hail/master/src/main/resources/reference/grch38.json

Until we need them in other parts of the code, I'd just put them in client-side settings.
