### ISSUE TITLE
Gene search across project

### ISSUE THREAD

**Issue by brettpthomas** [macarthur-lab/seqr#50]
This is top application-level priority right now! Working on a hack in branch `project_gene_search`.

**Comment by bw2** [comment]
For now, perhaps we should just run `load_project_datastore` for all projects and create a link to `project/<project-id>/gene` from the project page.

**Comment by brettpthomas** [comment]
Sounds good! A few quick notes in case this helps frame the problem: 

- Lack of quality filters on this page really limit the utility 

- Some searches will be prohibitively slow in some projects, to the point that I think the server will grind to a halt if don't add some request timeout 

- You could save a *ton* of space + efficiency if you restrict the variants that are loaded here to only those that are annotated

**Comment by dgmacarthur** [comment]
Just wanted to follow up on this issue. This is definitely one of the most heavily requested features, and I just had a request (quite urgent) for the ability to search across multiple projects within a consortium (for instance, all of our muscle disease projects). I'd really like to make this a high priority - happy to meet to brainstorm this, or hash it out on Slack.

**Comment by bw2** [comment]
The 1st implementation of cross-project gene search has been live for a while on the gene search page, so will close this issue. Better filtering is needed.
