### ISSUE TITLE
seqr and phenotips

### ISSUE THREAD

**Issue by nvteja** [macarthur-lab/seqr#510]
Hello,

Are there any config files that I need to edit to get the phenotips integration to work? When I click on pdf icon or the edit icon next to "Phenotips" column for a sample, I get this error.

{
    "message": "Invalid phenotips_user_id: None", 
    "traceback": [
        "Traceback (most recent call last):", 
        "  File \"/usr/lib/python2.7/site-packages/django/core/handlers/base.py\", line 185, in _get_response", 
        "    response = wrapped_callback(request, *callback_args, **callback_kwargs)", 
        "  File \"/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py\", line 23, in _wrapped_view", 
        "    return view_func(request, *args, **kwargs)", 
        "  File \"/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view", 
        "    return view_func(*args, **kwargs)", 
        "  File \"/seqr/seqr_new/code/seqr/seqr/views/apis/phenotips_api.py\", line 337, in phenotips_edit_handler", 
        "    return _phenotips_view_handler(request, project_guid, individual_guid, url_template, permission_level=CAN_EDIT)", 
        "  File \"/usr/lib/python2.7/site-packages/django/contrib/auth/decorators.py\", line 23, in _wrapped_view", 
        "    return view_func(request, *args, **kwargs)", 
        "  File \"/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py\", line 58, in wrapped_view", 
        "    return view_func(*args, **kwargs)", 
        "  File \"/seqr/seqr_new/code/seqr/seqr/views/apis/phenotips_api.py\", line 298, in _phenotips_view_handler", 
        "    _create_patient_if_missing(project, individual)", 
        "  File \"/seqr/seqr_new/code/seqr/seqr/views/apis/phenotips_api.py\", line 71, in _create_patient_if_missing", 
        "    auth_tuple = _get_phenotips_uname_and_pwd_for_project(project.phenotips_user_id)", 
        "  File \"/seqr/seqr_new/code/seqr/seqr/views/apis/phenotips_api.py\", line 478, in _get_phenotips_uname_and_pwd_for_project", 
        "    raise ValueError(\"Invalid phenotips_user_id: \" + str(phenotips_user_id))", 
        "ValueError: Invalid phenotips_user_id: None", 
        ""
    ]
}

**Comment by hanars** [comment]
That should have been set up correctly when you created the project, but its possible depending on what version of the code you were on and which page you used to create the project there might have been a bug. Try running `python manage.py update_projects_in_new_schema` and see if that fixes it

**Comment by nvteja** [comment]
I added the project through command line 

./manage.py add_project <project name> 

and then added individuals, vcf files using the subsequent commands from the link https://github.com/macarthur-lab/seqr/tree/master/deploy/mac_osx

I will run the command you suggested and let you know if that fixed it or not.

Thanks,
Teja.

**Comment by nvteja** [comment]
When I tried the update_projects_in_new_schema this is what I get

python manage.py update_projects_in_new_schema
2018-08-02 13:01:48,881 INFO:  Processing all 3 projects
  0%|                                                                                                                                                                                                                                        | 0/3 [00:00<?, ? projects/s]Project: 661d_test
Setting Project.is_phenotips_enabled = False
Setting Project.is_phenotips_enabled = True

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/seqr/seqr_new/code/seqr/seqr/management/commands/update_projects_in_new_schema.py", line 127, in handle
    source_individual, new_family, new_project, connect_to_phenotips
  File "/seqr/seqr_new/code/seqr/seqr/management/commands/update_projects_in_new_schema.py", line 556, in transfer_individual
    _retrieve_and_update_individual_phenotips_data(new_project, new_individual)
  File "/seqr/seqr_new/code/seqr/seqr/management/commands/update_projects_in_new_schema.py", line 587, in _retrieve_and_update_individual_phenotips_data
    latest_phenotips_json = phenotips_api.get_patient_data(
AttributeError: 'module' object has no attribute 'get_patient_data'

**Comment by hanars** [comment]
It looks like your version of code is out of date. Please pull the latest version from master and run this again

**Comment by nvteja** [comment]
I pulled the latest commit (as of this morning) and got past the error above, but when I try to import json file from phenotips into seqr using ./manage.py  load_phenotips_from_json I get this error - even though the JSON in the json file is valid. 

Loading {u'clinicalStatus': {u'clinicalStatus': u'affected'},
 u'contact': {u'email': u'support@phenotips.org',
              u'institution': u'http://phenotips.org/',
              u'name': u'Administrator',
              u'user_id': u'Admin'},
 u'date': u'2018-08-07T18:17:12.000Z',
 u'date_of_birth': u'',
 u'date_of_death': u'',
 u'ethnicity': {u'maternal_ethnicity': [], u'paternal_ethnicity': []},
 u'external_id': u'661_TR0092',
 u'family_history': {},
 u'features': [{u'id': u'HP:0001321',
                u'label': u'Cerebellar hypoplasia',
                u'observed': u'yes',
                u'type': u'phenotype'},
               {u'id': u'HP:0006879',
                u'label': u'Pontocerebellar atrophy',
                u'observed': u'yes',
                u'type': u'phenotype'}],
 u'genes': [{u'gene': u'SIN3A'},
            {u'gene': u'MEF2C'},
            {u'gene': u'TAF1'},
            {u'gene': u'COL11A2'},
            {u'gene': u'RAI1'},
            {u'gene': u'GJA1'},
            {u'gene': u'ANKRD11'},
            {u'gene': u'RPS6KA3'},
            {u'gene': u'FGFR1'},
            {u'gene': u'CASK'}],
 u'id': u'P0000001',
 u'last_modification_date': u'2018-08-07T18:23:40.000Z',
 u'last_modified_by': u'Admin',
 u'life_status': u'alive',
 u'meta': {u'hgncRemote_version': u'2018-08-07T06:30:57.82Z',
           u'hgnc_version': u'2015-08-09T17:45:23.025Z',
           u'hpo_version': u'releases/2015-09-15',
           u'omim_version': u'2015-10-07T18:26:19.654Z',
           u'phenotips_version': u'1.2.6'},
 u'nonstandard_features': [],
 u'patient_name': {u'first_name': u'Test', u'last_name': u'Test'},
 u'prenatal_perinatal_history': {},
 u'prenatal_perinatal_phenotype': {u'negative_prenatal_phenotype': [],
                                   u'prenatal_phenotype': []},
 u'report_id': u'P0000001',
 u'reporter': u'Admin',
 u'sex': u'U',
 u'solved': {u'status': u'unsolved'},
 u'specificity': {u'date': u'2018-08-07T18:23:53.670Z',
                  u'score': 0.6649420570600796,
                  u'server': u'local-omim'}}
Patient external id: 20180807_175926_345703_661_TR0092
=====================================
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 72, in handle
    self.process_json_file(file_name, patient_id_to_indiv_id_mapping, project_id, is_test_only=options['test'])
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 93, in process_json_file
    self.process_single_patient_json_file(patient_json, patient_id_to_indiv_id_mapping, project_id, is_test_only=is_test_only)
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 128, in process_single_patient_json_file
    existing_patient_in_phenotips = json.loads(response.content)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by hanars** [comment]
This might be an authentication issue- make sure that your phenotips instance has an admin account with username Admin and password admin, or update the `load_phenotips_from_json` script to use credentials that exist for you

**Comment by nvteja** [comment]
Thank you. Our phenotips instance does have Admin account with admin password.

**Comment by nvteja** [comment]
ok, I was able to fix the error above my specifying the mapping file with phenotips internal patient ID in the second column, but now I keep getting "Extra data" error.. Here is the JSON file
```

{
   "id":"P0000003",
   "reporter":"Admin",
   "features":[
      {
         "id":"HP:0001321",
         "label":"Cerebellar hypoplasia",
         "type":"phenotype",
         "observed":"yes"
      },
      {
         "id":"HP:0006879",
         "label":"Pontocerebellar atrophy",
         "type":"phenotype",
         "observed":"yes"
      }
   ],
   "nonstandard_features":[

   ],
   "contact":{
      "user_id":"Admin",
      "name":"Administrator",
      "email":"support@phenotips.org",
      "institution":"http://phenotips.org/"
   },
   "report_id":"P0000003",
   "date":"2018-08-07T18:17:12.000Z",
   "last_modified_by":"Admin",
   "last_modification_date":"2018-08-07T18:23:40.000Z",
   "life_status":"alive",
   "ethnicity":{
      "maternal_ethnicity":[

      ],
      "paternal_ethnicity":[

      ]
   },
   "genes":[
      {
         "gene":"SIN3A"
      },
      {
         "gene":"MEF2C"
      },
      {
         "gene":"TAF1"
      },
      {
         "gene":"COL11A2"
      },
      {
         "gene":"RAI1"
      },
{
         "gene":"GJA1"
      },
      {
         "gene":"ANKRD11"
      },
      {
         "gene":"RPS6KA3"
      },
      {
         "gene":"FGFR1"
      },
      {
         "gene":"CASK"
      }
   ],
   "external_id":"661_TR0092",
   "sex":"U",
   "solved":{
      "status":"unsolved"
   },
   "date_of_death":"",
   "date_of_birth":"",
   "clinicalStatus":{
      "clinicalStatus":"affected"
   },
   "patient_name":{
      "first_name":"Test",
      "last_name":"Test"
   },
   "prenatal_perinatal_history":{

   },
   "meta":{
      "hgncRemote_version":"2018-08-07T06:30:57.82Z",
      "hgnc_version":"2015-08-09T17:45:23.025Z",
      "hpo_version":"releases/2015-09-15",
      "omim_version":"2015-10-07T18:26:19.654Z",
      "phenotips_version":"1.2.6"
   },
   "specificity":{
      "score":0.6649420570600796,
      "date":"2018-08-07T18:43:07.441Z",
      "server":"local-omim"
   },
   "family_history":{

   },
   "prenatal_perinatal_phenotype":{
      "prenatal_phenotype":[

      ],
 "negative_prenatal_phenotype":[

      ]
   }

```




Here is the exact error I get:

```
`Loading {u'clinicalStatus': {u'clinicalStatus': u'affected'},
 u'contact': {u'email': u'support@phenotips.org',
              u'institution': u'http://phenotips.org/',
              u'name': u'Administrator',
              u'user_id': u'Admin'},
 u'date': u'2018-08-07T18:17:12.000Z',
 u'date_of_birth': u'',
 u'date_of_death': u'',
 u'ethnicity': {u'maternal_ethnicity': [], u'paternal_ethnicity': []},
 u'external_id': u'661_TR0092',
 u'family_history': {},
 u'features': [{u'id': u'HP:0001321',
                u'label': u'Cerebellar hypoplasia',
                u'observed': u'yes',
                u'type': u'phenotype'},
               {u'id': u'HP:0006879',
                u'label': u'Pontocerebellar atrophy',
                u'observed': u'yes',
                u'type': u'phenotype'}],
 u'genes': [{u'gene': u'SIN3A'},
            {u'gene': u'MEF2C'},
            {u'gene': u'TAF1'},
            {u'gene': u'COL11A2'},
            {u'gene': u'RAI1'},
            {u'gene': u'GJA1'},
            {u'gene': u'ANKRD11'},
            {u'gene': u'RPS6KA3'},
            {u'gene': u'FGFR1'},
            {u'gene': u'CASK'}],
 u'id': u'P0000003',
 u'last_modification_date': u'2018-08-07T18:23:40.000Z',
 u'last_modified_by': u'Admin',
 u'life_status': u'alive',
 u'meta': {u'hgncRemote_version': u'2018-08-07T06:30:57.82Z',
           u'hgnc_version': u'2015-08-09T17:45:23.025Z',
           u'hpo_version': u'releases/2015-09-15',
           u'omim_version': u'2015-10-07T18:26:19.654Z',
           u'phenotips_version': u'1.2.6'},
 u'nonstandard_features': [],
 u'patient_name': {u'first_name': u'Test', u'last_name': u'Test'},
 u'prenatal_perinatal_history': {},
 u'prenatal_perinatal_phenotype': {u'negative_prenatal_phenotype': [],
                                   u'prenatal_phenotype': []},
 u'report_id': u'P0000003',
 u'reporter': u'Admin',
 u'sex': u'U',
 u'solved': {u'status': u'unsolved'},
 u'specificity': {u'date': u'2018-08-07T18:43:07.441Z',
                  u'score': 0.6649420570600796,
                  u'server': u'local-omim'}}
Patient external id: 20180809_124043_931348_661_TR0092
=====================================
Sample: 661_TR0092
feature: [{u'gene': u'SIN3A'}, {u'gene': u'MEF2C'}, {u'gene': u'TAF1'}, {u'gene': u'COL11A2'}, {u'gene': u'RAI1'}, {u'gene': u'GJA1'}, {u'gene': u'ANKRD11'}, {u'gene': u'RPS6KA3'}, {u'gene': u'FGFR1'}, {u'gene': u'CASK'}]
meta:
  our data: {u'hgnc_version': u'2015-08-09T17:45:23.025Z', u'hgncRemote_version': u'2018-08-09T04:38:03.237Z', u'hpo_version': u'releases/2015-09-15', u'phenotips_version': u'1.2.6', u'omim_version': u'2015-10-07T18:26:19.654Z'}
  their data:{u'hgnc_version': u'2015-08-09T17:45:23.025Z', u'hgncRemote_version': u'2018-08-07T06:30:57.82Z', u'hpo_version': u'releases/2015-09-15', u'phenotips_version': u'1.2.6', u'omim_version': u'2015-10-07T18:26:19.654Z'}
specificity:
  our data: {u'date': u'2018-08-09T15:18:27.131Z', u'score': 0.3459894480862141, u'server': u'local-omim'}
  their data:{u'date': u'2018-08-07T18:43:07.441Z', u'score': 0.6649420570600796, u'server': u'local-omim'}
reporter:
  our data: 661d_short
  their data:Admin
genes: [{u'gene': u'SIN3A'}, {u'gene': u'MEF2C'}, {u'gene': u'TAF1'}, {u'gene': u'COL11A2'}, {u'gene': u'RAI1'}, {u'gene': u'GJA1'}, {u'gene': u'ANKRD11'}, {u'gene': u'RPS6KA3'}, {u'gene': u'FGFR1'}, {u'gene': u'CASK'}]
contact:
  our data: {u'user_id': u'661d_short', u'name': u'661d short', u'email': u'harindra@broadinstitute.org'}
  their data:{u'user_id': u'Admin', u'name': u'Administrator', u'institution': u'http://phenotips.org/', u'email': u'support@phenotips.org'}
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 72, in handle
    self.process_json_file(file_name, patient_id_to_indiv_id_mapping, project_id, is_test_only=options['test'])
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 86, in process_json_file
    patient_json = json.load(json_file)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4 - line 2 column 1 (char 3 - 21)
`
```

I tried loading a miminal json file with most of the keys deleted except for ID, external_ID and features keys, but I still get the same error. 

Any suggestions?

Thank you!
Teja

**Comment by bw2** [comment]
Hi Teja, 
It looks like there's an issue with the json file format which causes python's built-in json parser to fail (`patient_json = json.load(json_file)`)
If you try running 
```
cat yourfile.json | python -m json.tool
```
it should give you the same error - which would mean the format issue is at the very beginning - on line 1 column 4

**Comment by nvteja** [comment]
okay, when I try the command above - I dont get the error. It just prints the json file. 
Also when I do json.load(<my json file's file handle>) in a python shell it loads the file without any issues.

**Comment by bw2** [comment]
Can you try
```
git checkout debug_load_phenotips_from_json
```
and running the script again? It should print the filename that it's processing.

**Comment by nvteja** [comment]
when I try git checkout debug_load_phenotips_from_json I get a `error: pathspec 'debug_load_phenotips_from_json' did not match any file(s) known to git.` error

**Comment by bw2** [comment]
do a ```git pull ``` first

**Comment by nvteja** [comment]
Same result 
'''git checkout debug_load_phenotips_from_json
M       settings.py
Already on 'debug_load_phenotips_from_json'
Your branch is up-to-date with 'origin/debug_load_phenotips_from_json'.
CCM-3603-1NML:seqr teja$ ./manage.py load_phenotips_from_json 661d.json mappings.txt 
Processing mappings.txt
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 72, in handle
    self.process_json_file(file_name, patient_id_to_indiv_id_mapping, project_id, is_test_only=options['test'])
  File "/Users/teja/Desktop/SEQR/code/seqr/xbrowse_server/base/management/commands/load_phenotips_from_json.py", line 87, in process_json_file
    patient_json = json.load(json_file)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4 - line 2 column 1 (char 3 - 21)'''

On the other hand, I was able to successfully link phenotips from seqr itself by running "add_projects_to_phenotips" and "add_individuals_to_phenotips" for my projects. Seqr is able to pull data directly from phenotips without the use of the "load_phenotips_from_json" command for now.

**Comment by bw2** [comment]
great thanks. The issue is that the command also needs a project id argument. If you run 
```./manage.py load_phenotips_from_json``` (without any args), it will print out the args it expects. 

The json parse error was happening because it was trying to parse `mappings.txt` as json.
You should be able to run it with
```
./manage.py load_phenotips_from_json --patient-id-mapping  mappings.txt  <project-id> 661d.json 
```

**Comment by nvteja** [comment]
Aah, that makes sense! Thank you so much.

Teja.
