### ISSUE TITLE
Adjust number of variants seen on variant page

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#516]
I'm often trying to find a variant that was discussed in a collaborator meeting but I don't remember what family it's in and I might just remember part of the gene name even. I like to be able to do a find on the variant review page but when only 25 variants are shown at a time, I often flip through 10 pages trying to find the thing and give up. I wish this page defaulted to 100 variants or otherwise I'd like to be able to change how many variants are seen on the page for when I'm in this situation.

**Comment by hanars** [comment]
There is now a "Variant per page" dropdown that allows you to select how many to show
