### ISSUE TITLE
Remove Unused Case Review Statuses 

### ISSUE THREAD

**Issue by gvannoy** [macarthur-lab/seqr#517]
The case review statuses: Not in Review, Withdrew, Ineligible, and Declined can be removed as they are not used and will not be used moving forward.

**Comment by anneodonnell** [comment]
Not in review was added for non-RGP projects that we sometimes added cases to a project that could bypass review. Unless it causes problems for RGP, might be better to leave for now. We haven’t been using it but that use case could arise again unless something else changed that negates this need.
