### ISSUE TITLE
Chromosome position, OMIM tag

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#523]
Hi,

https://seqr.broadinstitute.org/project/gleeson_cmg-samples_exomes_v1/family/3129/mendelian-variant-search#search/eaa2e5b3/results

The genes do not seem to be arranged by position. e.g. C12ORF65 is at the top and the other variant lower down in the list. 

Also, gene NDUFA4 has a disease association in OMIM, but is not showing up on the search view in seqr.

**Comment by hanars** [comment]
Hi Lynn,

Can you double check what option you have selected in the "sort by" dropdown on the top right of the results? I'm seeing C12ORF65  as the 4th and 5th variants and sort looks fine when I apply the "chrom/pos" sort

**Comment by lynnpais** [comment]
Hi Hana,

It works when you manually do it. However, the default is "chrom/pos" sort, but does not always display that way when you get your search results. It does work when you manually select it. See the attached pic. It says sorted by "chrom/pos" but in fact the one variant is 1st and other variant is in the 5th position. 

I've noticed this happening before. 
<img width="876" alt="screen shot 2018-08-06 at 10 13 47 am" src="https://user-images.githubusercontent.com/37872186/43723782-77fd8606-9966-11e8-8fe2-2250fbac46e5.png">

**Comment by lynnpais** [comment]
Sorry, wrong screen shot. Here's it is- 
<img width="1263" alt="screen shot 2018-08-06 at 10 47 19 am" src="https://user-images.githubusercontent.com/37872186/43723813-9135087e-9966-11e8-8ce6-3a17b1323f01.png">
