### ISSUE TITLE
Download table function not working

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#524]
Please see https://seqr.broadinstitute.org/project/R0383_gazda_exomes/project_page

Thank you, 
Lynn

**Comment by zmcv** [comment]
JS console output:
> Uncaught TypeError: Cannot read property 'display_name' of undefined
>     at constants.js:378
>     at Array.map (<anonymous>)
>     at Object.format (constants.js:378)
>     at selectors.js:277
>     at Array.map (<anonymous>)
>     at Object.processRow (selectors.js:275)
>     at ExportTableButton.jsx:41
>     at Array.map (<anonymous>)
>     at d (ExportTableButton.jsx:41)
>     at In (react-dom.production.min.js:173)
