### ISSUE TITLE
Request to add MGI link 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#531]
Can you please add the link to MGI to the other list of links? 

e.g. for the gene TUBG1, it would be ideal if we could be directed to the gene specific information http://www.informatics.jax.org/marker/MGI:101834

thank you.

**Comment by hanars** [comment]
Can use http://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt to get mapping (Human Marker Symbol | Human Entrez Gene ID | HomoloGene ID | Mouse Marker Symbol | MGI Marker Accession ID | High-level Mammalian Phenotype ID(space-delimited))

**Comment by hanars** [comment]
MGI links have been added
