### ISSUE TITLE
Parents lost after project split

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#543]
Hi,

When the Walsh_WES project was split into three, we seem to have 'lost' the data on the parents. All families now appear as proband only- https://seqr.broadinstitute.org/project/R0456_cmg_walsh_exomes_ch/project_page

This issue was raised earlier, but unfortunately not on GitHub cos we weren't using it as much then, so may have fallen off our radar. Anyway, hopefully we can sort this one out soon. 

Thanks a lot.

**Comment by hanars** [comment]
Duplicates https://github.com/macarthur-lab/seqr-private/issues/335
