### ISSUE TITLE
Clinvar classification not showing in seqr

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#549]
Hi, there are two SH3TC2 variants in a family in our cohort, each of which is classified as VUS by a single submitter in Clinvar. However, there's no clinvar tag/link coming up for these variants when I run a seqr search. The two variants are here:

https://seqr.broadinstitute.org/project/Engle_WGS_900/variants/VUS?family=79

Variation IDs in Clinvar are 476900 and 546985.

Thanks!
Julie

**Comment by hanars** [comment]
This is fixed now
