### ISSUE TITLE
Gene name not showing 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#552]
https://seqr.broadinstitute.org/project/R0447_non_cmg_kang_exomes/saved_variants/family/F023473_k1417

![screen shot 2018-08-16 at 9 00 52 am](https://user-images.githubusercontent.com/37872186/44209942-f2dff380-a132-11e8-9391-a9471e849e95.png)

**Comment by hanars** [comment]
This has been fixed
