### ISSUE TITLE
Population frequencies in VCF file

### ISSUE THREAD

**Issue by nvteja** [macarthur-lab/seqr#555]
Hello,

Sorry if this should have been obvious to spot, but could you please let me know which keys/headers in VCF file does SEQR read the 1KG and EXAC population frequencies from? The VCF file I am using has frequency headers as part of VEP CSQ string, but I dont think SEQR is reading frequencies from the VEP string as I see frequency as 0.0 for all variants in the variant page regardless of the frequency in the VCF file. Here is the VEP CSQ string that my VCF has
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|ALLELE_NUM|DISTANCE|STRAND|FLAGS|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|TSL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|REFSEQ_MATCH|SOURCE|GIVEN_REF|USED_REF|BAM_EDIT|GENE_PHENO|SIFT|PolyPhen|DOMAINS|HGVS_OFFSET|**_AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|AA_AF|EA_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|MAX_AF|MAX_AF_POPS_**|CLIN_SIG|SOMATIC|PHENO|PUBMED|MOTIF_NAME|MOTIF_POS|HIGH_INF_POS|MOTIF_SCORE_CHANGE|LoF|LoF_filter|LoF_flags|LoF_info|Polyphen2_HVAR_pred|CADD_phred|SIFT_pred|FATHMM_pred|MutationTaster_pred|MetaSVM_pred">

Thank you,
Teja.

**Comment by bw2** [comment]
Hi Teja, sorry I missed this before. seqr doesn't use these fields from the CSQ.  What version of seqr are you running? If you're interested in updating to use the latest version that's based on hail/elasticsearch, it annotates population allele frequencies from data files sitting in public google cloud storage.
