### ISSUE TITLE
variants not loading

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#564]
Hi, I've been using the new seqr page and sometimes have issues getting to the pages with my stored variants. As an example, for one of our families I tried clicking the bar with 4 saved variants that I'd tagged for Sanger validation, but got a blank page that never loaded and allowed me to see the variants: https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/family/F022006_194

Thank you for your help!

**Comment by hanars** [comment]
Hi Julie, thanks for your patience on this one. It is now resolved
