### ISSUE TITLE
Bugs with new seqr

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#565]
In the new seqr variant pages, the gene name sometimes doesn't show for tagged compound heterozygous variants. As an example, see the first 2 variants that pop up on this page with a "Sanger validated" tag:

https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/family/F022012_184

Also, if you click the "3 prime UTR variant" or "missense variant" link for the first two variants on that page (and some others on the same page farther down), the transcript information popup with all the annotation information is blank. 

Thanks for looking into this!

**Comment by hanars** [comment]
Hi Julie this should be fixed now. Let me know if you see this issue again
