### ISSUE TITLE
IGV for probing not loading

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#569]
Can we have the reads for the probing please
https://seqr.broadinstitute.org/project/R0380_cmg_gazda_wgs/saved_variants/family/F018919_gaz_447

**Comment by hanars** [comment]
@mike-w-wilson seqr is expecting a cram in `CMG_Gazda/RP-1466/WGS/447-3_01/v1/447-3_01.cram` but that doesn't seem to exist. Any idea where this file went? The other files for this family are there

**Comment by mike-w-wilson** [comment]
@hanars , seqr should be expecting a cram in `CMG_Gazda/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram` which is exist but I'm still seeing a invalid bam magic error. I just ran this again 
```bash-4.2$ PYTHONPATH=/mongo/code/xbrowse:/mongo/code/xbrowse-settings  python2.7 manage.py set_bam_paths CMG_Gazda /mongo/data/bam_paths/CMG_Gazda_crams.txt
Processing line: GAZ_431-1_01	CMG_Gazda/RP-1466/WGS/GAZ_431-1_A_2/v1/GAZ_431-1_A_2.cram

Processing line: GAZ_431-2_01	CMG_Gazda/RP-1466/WGS/431-2_A/v1/431-2_A.cram

Processing line: GAZ_431-3_01	CMG_Gazda/RP-1466/WGS/GAZ_431-3_A_2/v1/GAZ_431-3_A_2.cram

Processing line: GAZ_432-1_01	CMG_Gazda/RP-1466/WGS/432-1_A/v1/432-1_A.cram

Processing line: GAZ_432-2_01	CMG_Gazda/RP-1466/WGS/432-2_A/v2/432-2_A.cram

Processing line: GAZ_432-3_01	CMG_Gazda/RP-1466/WGS/432-3_A/v1/432-3_A.cram

Processing line: GAZ_437-1_01	CMG_Gazda/RP-1466/WGS/437-1_A/v1/437-1_A.cram

Processing line: GAZ_437-2_01	CMG_Gazda/RP-1466/WGS/437-2_A/v1/437-2_A.cram

Processing line: GAZ_437-3_01	CMG_Gazda/RP-1466/WGS/437-3_A/v1/437-3_A.cram

Processing line: GAZ_441-1_01	CMG_Gazda/RP-1466/WGS/441-1_A/v1/441-1_A.cram

Processing line: GAZ_441-1_02	CMG_Gazda/RP-1466/WGS/441-2_A/v1/441-2_A.cram

Processing line: GAZ_441-1_03	CMG_Gazda/RP-1466/WGS/441-3_A/v1/441-3_A.cram

Processing line: GAZ_447-2_01	CMG_Gazda/RP-1466/WGS/447-2_A/v1/447-2_A.cram

Processing line: GAZ_447-3_01	CMG_Gazda/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram

Processing line: GAZ_447-1_A_2	CMG_Gazda/RP-1466/WGS/GAZ_447-1_A_2/v1/GAZ_447-1_A_2.cram
```

**Comment by hanars** [comment]
So should we update seqr to use `MacArthurLab_CMG_Gazda_RareDisease_WGS_Mar2018/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram` for that sample or should we move the cram?

**Comment by mike-w-wilson** [comment]
So the cram has been moved to the firecloud workspace `MacArthurLab_CMG_Gazda_RareDisease_WGS` but within that workspace's data tab, the cram path  is still `MacArthurLab_CMG_Gazda_RareDisease_WGS_Mar2018/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram` . The workspace `MacArthurLab_CMG_Gazda_RareDisease_WGS_Mar2018` no longer exists.

**Comment by hanars** [comment]
Sorry, I'm a bit confused I'm still new to understanding how this file system works. What is a valid path to that cram that I can use in seqr?

**Comment by mike-w-wilson** [comment]
I'm not entirely sure so we may need @bw2 , but my understanding was the first directory in the path is the readviz mount followed by the third directory on from the cram path which is retrieved from the firecloud workspace's data tab download, column 10.  So for this case it would be the mount `CMG_Gazda` and then the cram file path `gs://fc-94cf3dc4-a539-4da2-9434-a15b98a5c1e2/MacArthurLab_CMG_Gazda_RareDisease_WGS_Mar2018/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram` with the first two directories cut off, so `/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram`. Then combine them to be `inmr_neuro_wgs/RP-1466/WGS/447-3_A_2/v1/447-3_A_2.cram`

**Comment by mike-w-wilson** [comment]
This cram is now loaded
