### ISSUE TITLE
can't tag variants in seqr

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#570]
Hi, I'm trying to tag a variant for review in this family but am unable to do so:

https://seqr.broadinstitute.org/project/Engle_WGS_900/family/61/mendelian-variant-search#search/eca88b60/results

Eleina had the same issue with a separate family earlier today as well.
Thanks!

**Comment by hanars** [comment]
Thanks for letting me know. This is fixed now
