### ISSUE TITLE
Same issue as 565

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#571]
Hi Hana, having the same issue as noted w/ ticket 565 for this family (gene name doesn't show up under variant tagged for sanger validation, and can't get to the transcript information if I click the link for missense variant): 

https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/family/F021960_2/Send%20for%20Sanger%20validation

Thank you!

**Comment by hanars** [comment]
Sorry, I only fixed it for the one family yesterday. It should now be fixed for the whole project
