### ISSUE TITLE
BUG-recessive&compound het searches not working properly

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#572]
I just did a search in this family for "recessive" hits and came up with 2 hits:
https://seqr.broadinstitute.org/project/Engle_Moebius/family/F83/mendelian-variant-search#search/d6bd1fd0/results

Then compound het search and got no hits:
https://seqr.broadinstitute.org/project/Engle_Moebius/family/F83/mendelian-variant-search#search/3d4fb6b6/results

Then custom search looking for genes w/ at least 1 allele in both affected individuals and -- for the unaffected parents:
https://seqr.broadinstitute.org/project/Engle_Moebius/family/F83/mendelian-variant-search#search/52b785df/results

The allele frequencies and type of variants search are the same in all 3 searches. On the custom page, search for KALRN and you'll see compound het variants in this gene (one inherited from mom, the other from dad) meeting the search parameters specified. Why does this come up in custom search but not AR or compound het search?

**Comment by hanars** [comment]
Hi Julie,

One of those compound het variants is "synonymous" which you have filtered out. If you allow synonymous variants then it comes up in AR and compound het searches: https://seqr.broadinstitute.org/project/Engle_Moebius/family/F83/mendelian-variant-search#search/d207e7bb/results

It looks like there is a bug with custom inheritance search such that it does not properly filter out variants based on annotation, which is why it was coming back there

**Comment by juliejurgens** [comment]
Hi Hana, so I think I figured out the problem here.

If I uncheck "synonymous" and "extended splice site" the variant labeled as synonymous still comes up under the custom search. But if I uncheck synonymous and regulatory region variant, it doesn't come up anymore:
https://seqr.broadinstitute.org/project/Engle_Moebius/family/F83/mendelian-variant-search#search/74e3bceb/results

So the variant is technically annotated as regulatory as well as synonymous, and just comes up w/ the synonymous label (maybe because a synonymous label technically would override regulatory in the hierarchy?)

So I think the issue may be that compound het searches aren't pulling up regulatory region variants properly?
