### ISSUE TITLE
Error message and pedigrees not showing when bulk uploading to seqr

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#575]
After bulk uploading an excel sheet to seqr, error message "Unexpected token < in JSON at position 0" appeared. Participants are all correctly sorted into families and have relations marked, but no pedigree is showing in family view.

![image](https://user-images.githubusercontent.com/43212980/45435075-c493fc00-b67d-11e8-9165-4e967a878e02.png)

**Comment by hanars** [comment]
This is fixed now. Also, in the future including a link to the page instead of/ in addition to screenshots would be helpful
