### ISSUE TITLE
no variants coming up for trio project

### ISSUE THREAD

**Issue by miriamudler** [macarthur-lab/seqr#576]
Here is the link to the project:
https://seqr.broadinstitute.org/project/udler_freeman_kathiresan/family/Lpx1/mendelian-variant-search#search/5495d92f/results

I had previously started working on this project and it seemed to work fine, but now I no longer see any variants when i perform analyses. 
Thanks!

**Comment by bw2** [comment]
@miriamudler there are UI improvements planned to avoid this issue, but you need to set This Callset AF = 1

**Comment by bw2** [comment]
![image](https://user-images.githubusercontent.com/6240170/45508856-fb444200-b763-11e8-8a1a-0e7b73b79ab4.png)
