### ISSUE TITLE
Missing UniProt summaries for genes

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#582]
Hi,

<img width="1231" alt="screen shot 2018-09-17 at 3 58 59 pm" src="https://user-images.githubusercontent.com/37872186/45647191-3c559280-ba93-11e8-8f59-b90693aa8720.png">

The UniProt gene description seems to be missing for all variants/genes- https://seqr.broadinstitute.org/project/cmg_walsh_exomes_microcephaly/family/MC30600/mendelian-variant-search#search/13197ccf/results

**Comment by bw2** [comment]
Fixed
