### ISSUE TITLE
Missing disease association 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#583]
The variant results page indicates that there is a OMIM phenotype associated, but this does not show up like it used to- https://seqr.broadinstitute.org/project/cmg_walsh_exomes_microcephaly/family/MC30600/mendelian-variant-search#search/336c7280/results
<img width="1216" alt="screen shot 2018-09-17 at 4 27 32 pm" src="https://user-images.githubusercontent.com/37872186/45648505-c4896700-ba96-11e8-891b-b77a5b024138.png">

**Comment by lynnpais** [comment]
<img width="1302" alt="screen shot 2018-09-17 at 4 29 15 pm" src="https://user-images.githubusercontent.com/37872186/45648536-d965fa80-ba96-11e8-9b71-471e0a01afb5.png">

**Comment by bw2** [comment]
Fixed
