### ISSUE TITLE
missing button to get to 2nd page of variants 

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#586]
Hi, I'm scrolling through the families on our project page, which says it's showing 194 of 270 families and want to get to page 2, but don't see a button to get to that:
https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/project_page

Thanks!
Julie

**Comment by hanars** [comment]
Hi Julie,

There is no paging. If it is showing you "X out of Y families" it is because you have applied a filter either by typing into the search box in the table header or by selecting one of the filters from the filter dropdown in the table header
