### ISSUE TITLE
Incorrect allele frequency in CMG callset

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#589]
<img width="1204" alt="screen shot 2018-09-20 at 2 55 44 pm" src="https://user-images.githubusercontent.com/37872186/45840746-d90f6e80-bce5-11e8-9b49-43d111284612.png">

For the COL5A2 variants, the probands are homozygous recessive, so allele count in our calmest should be at least 4, but its showing as 1. 

https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/family/F023585_mc30600/Review

**Comment by bw2** [comment]
going back to the source data, it's a multiallelic varinat (G > A,T) and the AC's are AC=1 for A and AC=4  for T, so it's showing AC from the other allele. Reloading this project is one way to fix it.

**Comment by bw2** [comment]
It was fixed in https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/53/files
