### ISSUE TITLE
Project page - Export table - exports .csv instead of .xls

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#594]
Attempting to export pedigree file from one project and import it into another, but ran into some minor usability issues:
Clicking on the project page > Download Table > ".xls" actually exports ".csv". It would be nice to go back to ".xls" partly because uploading a ".csv" to the bulk upload form returns "file type not supported".  Then, in case this is an easy fix, in the Edit Families & Indivduals form dropping in a .csv file or other invalid file doesn't show an error until you hit Apply.

**Comment by hanars** [comment]
This is now fixed, although this is in general a bad way to copy families between projects because it does not move phenotips etc
