### ISSUE TITLE
Variant search timeout

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#599]
A normal recessive search at 0.01 frequency is timing out https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/family_page/F020366_fam63

**Comment by hanars** [comment]
I'm not seeing an issue: https://seqr.broadinstitute.org/project/CMG_VCGS_Exomes/family/FAM63/mendelian-variant-search#search/82933219/results
