### ISSUE TITLE
Unable to edit matchbox contact emails

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#606]
<img width="929" alt="screen shot 2018-10-11 at 2 49 50 pm" src="https://user-images.githubusercontent.com/37872186/46828824-19549080-cd6a-11e8-9336-0bfa2c52b1f7.png">

https://seqr.broadinstitute.org/project/CMG_VCGS_Exomes/family/FAM36

The White group noted that they cannot add or edit emails in the MME submission page. It would also be good to have the Broad Mme address as a standard, and the option to add on others if required.

**Comment by hanars** [comment]
Will deal with the bug as part of this issue, created https://github.com/macarthur-lab/seqr/issues/607 to track adding the default

**Comment by hanars** [comment]
The bug with editing emails is now fixed
