### ISSUE TITLE
'Saved Variants' colored bar link broken

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#623]
Every time I try to view previously saved variants by clicking on the colored bar (either through the family page or project page) I am directed to a blank page. Happens consistently on Pierce-Retinal Degeneration-CMG-Exomes project. Unsure if consistent in other cohorts. 
Thanks, Stephanie

**Comment by hanars** [comment]
Hi, can you please include a link to a page where you are experiencing this problem? Probably best to do a family page

**Comment by stephditroia** [comment]
Hi Hana, this is happening on all family pages in this cohort. Here is an example link: https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/family_page/F023879_ogi1255
