### ISSUE TITLE
Moving families between seqr projects

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#629]
As mentioned to Hana in Slack, Ana Topf requested that the following families be moved from project CMG_Topf_CMS_WES to the newly created project CMG_Topf_EA-CMS_WES:

TOP_557 
TOP_715
TOP_BB3505 
TOP_567
TOP_763 
TOP_BB4023
TOP_372
TOP_321
 TOP_915
TOP_341  
TOP_410 
TOP_524  
TOP_403 
TOP_412
TOP_744 
TOP_855
TOP_500  
TOP_465  
TOP_294  
TOP_135 
TOP_378
TOP_793
TOP_922

Thanks a ton,
Katie

**Comment by hanars** [comment]
This is done now, let me know if there are any issues
