### ISSUE TITLE
transcript selection 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#631]
![screen shot 2018-10-29 at 9 50 20 pm](https://user-images.githubusercontent.com/37872186/47690581-faa52500-dbc4-11e8-8219-ae9e6d2c17f3.png)
 
https://seqr.broadinstitute.org/project/Rare_Genomes_Project/family/RGP_245/mendelian-variant-search#search/5ddc285f/results 

When running the above recessive search, there seems to be one hit in each the following genes- ANAPC10 and ABCE1, but its actually a recessive search so should have two hits. Looking at the transcripts, its choosing the splice variant in ANAPC10. This is the most deleterious effect, but the result does not display as recessive.

**Comment by hanars** [comment]
This will be resolved by https://github.com/macarthur-lab/seqr/issues/646
