### ISSUE TITLE
vep undefined symbol: Perl_Gthr_key_ptr

### ISSUE THREAD

**Issue by marbeno** [macarthur-lab/seqr#632]
Hi,
I recently installed seqr locally.
When I try to run vep, I get the following error
```
$ perl vep/variant_effect_predictor/variant_effect_predictor.pl`

perl: symbol lookup error: /media/DataHD/seqr/seqr/vep/ensembl-tools-release-85/scripts/variant_effect_predictor/Faidx.so: undefined symbol: Perl_Gthr_key_ptr
```
This kind of error seems related to conflicting perl/modules version, however the perl version is the one that got installed with seqr.

```
$ perl --version

This is perl 5, version 20, subversion 3 (v5.20.3) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)
```
Any suggestions?

**Comment by bw2** [comment]
Hi @marbeno the local install scripts have changed a lot recently.  Did you install  seqr using steps from https://github.com/macarthur-lab/seqr/blob/master/deploy/LOCAL_INSTALL.md? and if yes, how long ago? and on what operating system?

**Comment by marbeno** [comment]
Hi,
I did it following those steps, about a week ago on Ubuntu 16.04.

**Comment by bw2** [comment]
The install script uses perlbrew to install perl v5.20 and that error implies perl is pointing to the wrong versions of libraries.  

I would try running:

unset PERL5LIB
source ~/perl5/perlbrew/etc/bashrc

and then 
https://github.com/macarthur-lab/seqr/blob/master/deploy/install_local.step9.install_pipeline_runner.sh#L54-L61

**Comment by marbeno** [comment]
Hi,
thanks for you reply.
I did what you suggested. All dependencies where up to date, and I still got the error message.
