### ISSUE TITLE
Error uploading pedigree/sample manifest to seqr

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#649]
I received an error in the file header while trying to upload a pedigree/sample manifest spreadsheet into Seqr (image and spreadsheet both attached). This happened both with the original file as well as a fresh copy of the template with the sample information copied in.
[Pedigree%2FSample Manifest Revisions (8).xlsx](https://github.com/macarthur-lab/seqr/files/2567548/Pedigree.2FSample.Manifest.Revisions.8.xlsx)
![seqr upload error 11-9](https://user-images.githubusercontent.com/43212980/48289058-284b6300-e43c-11e8-84f0-e3ec38bbdb36.PNG)

**Comment by hanars** [comment]
This should work now
