### ISSUE TITLE
Gene information disappearing 

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#650]
Hey Hana, 

I have this strange bug where a variant loses all gene information if brought up through tags vs variant search. 

Variant search shows full information for variant chrM:7444 
https://seqr.broadinstitute.org/project/pierce_retinal-degeneration_cmg-samples_exomes_v1/family/OGI279/mendelian-variant-search#search/15404c0c/results

'Known gene for phenotype' tag list is missing all information for variant chrM:7444 
https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/saved_variants/family/F012975_ogi279/Known%20gene%20for%20phenotype

No rush, but was too out there to not report. 

Stephanie

**Comment by hanars** [comment]
Thanks for letting me know, this is fixed now
