### ISSUE TITLE
Genotype display 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#657]
Hello,

In a custom search, the parental genotype is being displayed as No Call, regardless of the actual genotype. I
![screen shot 2018-11-16 at 8 26 22 am](https://user-images.githubusercontent.com/37872186/48626748-b5cd0c80-e980-11e8-9807-f40194e65b15.png)
![screen shot 2018-11-16 at 8 25 31 am](https://user-images.githubusercontent.com/37872186/48626752-b82f6680-e980-11e8-8a45-c6d3bc2624aa.png)

f you set the custom search to heterozygous in the proband and --- for both parents, the results are displayed as No Call in the parents, even if the variant is actually in one of them.https://seqr.broadinstitute.org/project/CMG_VCGS_Exomes/family/VCGS_FAM116/mendelian-variant-search#search/99443d15/results

**Comment by hanars** [comment]
This is fixed now
