### ISSUE TITLE
Auto-generated merged pedigree file generating in wrong Excel format

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#660]
When uploading a merged pedigree/sample manifest file, the auto-generated Excel files are being generated as a .xls rather than .xlsx , preventing them from being able to upload into BSP and creating a warning message when opening in Excel. Manually re-saving the file as a .xlsx fixes the issue, but if you have the time to fix the file type in the script that would be great.

Thanks!

![xls error](https://user-images.githubusercontent.com/43212980/48849033-7f720180-ed73-11e8-8d21-f4eee00b3655.PNG)

**Comment by hanars** [comment]
@katie-larkin this should be fixed now, the files should be sent back as xlsx
