### ISSUE TITLE
Encountering 404 when attempting to carry out "Analysis Group Search" 

### ISSUE THREAD

**Issue by h-joshi** [macarthur-lab/seqr#662]
Dear Seqr team,
    These are the steps to reproduce

1) Create an Analysis group search with one family

2) Navigate into the analysis group

3) Click "Analysis Group Search" in top right hand corner

A 404 error is displayed at this point. I have also attached a screenshot illustrating what I did.
[Screenshots.docx](https://github.com/macarthur-lab/seqr/files/2606069/Screenshots.docx)

What could be causing this?

**Comment by hanars** [comment]
This is a bug that occurs when you create an Analysis Group that does not have a description. I will have this fixed by the end of the week, or if you would rather not wait you can get around this by creating a new Analysis Group where you enter something for the description

**Comment by hanars** [comment]
This is now fixed
