### ISSUE TITLE
IGV not leading 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#669]
I'm unable to load seqr IGV for this case- https://seqr.broadinstitute.org/project/R0405_cmg_vcgs_genomes/saved_variants/family/F022575_fam11

**Comment by hanars** [comment]
This is the same problem as https://github.com/macarthur-lab/seqr/issues/655 so I'm closing this issue so we can track this in one place

Katie will be giving updates in the #cmg_datadelivery slack channel (see https://macarthurlab.slack.com/archives/C573BQ1S9/p1543339034011500) and thats a good place to ask questions about these issues
