### ISSUE TITLE
Engle samples to be moved between Seqr projects

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#670]
Can the following samples all get moved between Seqr projects from https://seqr.broadinstitute.org/project/R0378_engle_exome/project_page to https://seqr.broadinstitute.org/project/R0498_cmg_engle_ext_wes/project_page?

CMS-001_17-452753
CMS-002_17-117711
CMS-003_17-461640
F125-001
F129_001
F129_002
F129_003
F132-001-2
F132-002-2
F132-003-2
F151_001
F151_002
F151_003
F155_001
F155_002
F155_003
F158_001
F158_002
F158-003-2
F159_001
F159_002
F159_003
F160-001
F160-002
F160-003
F161-001
F161-003
F166-001
F21-001-2
F21-002-2
F21-003-2
F3-001-2
F3-002-2
F3-003-2
F30-001-2
F30-002-2
F30-003-2
F32-002-2
F36-001
F36-002
F36-003
F37_001
F37_002
F37_003
F49_001
F49_002
F49_003
F5_001
F5_002
F5_003
F72_001

These samples are otherwise ready for Seqr upload, so priority would be appreciated. Thanks so much!

**Comment by hanars** [comment]
As a quick look, it appears that none of these individuals have any data loaded in seqr, including any phenotpis data. if that is the case, you should just delete them from the old project and upload them directly to the new project. If there are any samples in this list where there is any data in seqr, can you make a list just of those and I will move them

**Comment by katie-larkin** [comment]
Ok, that sounds good. Looking through I don't think any have data or phenotips, so you should be good. Thanks!
