### ISSUE TITLE
custom search not working properly?

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#674]
Hi Hana, I'm not sure if the custom search is working properly. Ipreviously found a variant in SKI in family 132 using custom search parameters:
https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/family/F021928_132

When I hit "rerun variant search" to see if I can detect the variant by custom search now, I don't get any results at all:
https://seqr.broadinstitute.org/project/Engle_WGS_900/family/132/mendelian-variant-search#search/5a6f3d0e/results
This also applies if I just do a custom search from scratch using the same parameters.

If I run a search for "all variants" in the SKI gene, I come up with the variant as before:
https://seqr.broadinstitute.org/project/Engle_WGS_900/family/132/mendelian-variant-search#search/3925c7ef/results

**Comment by hanars** [comment]
Hi Julie, this appears to be an issue with you quality filters. When I set them to 0 I see the variant you expect: https://seqr.broadinstitute.org/project/Engle_WGS_900/family/132/mendelian-variant-search#search/512192f6/results
