### ISSUE TITLE
Saved variants not showing

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#677]
No variants show in the new dashboard under any of the tags such as Review, Tier 1, etc. 

https://seqr.broadinstitute.org/project/R0394_cmg_kang_lgmd_wes/project_page

Katherine Chao also encountered the issue in another project. 

In the pic below, there should be 100 saved variants 

![screen shot 2018-12-12 at 1 55 58 pm](https://user-images.githubusercontent.com/37872186/49891916-b2109680-fe15-11e8-9649-072117d719fe.png)

**Comment by hanars** [comment]
thi sis fixed now
