### ISSUE TITLE
Search results breakdown by gene

### ISSUE THREAD

**Issue by hanars** [macarthur-lab/seqr#680]
The new search ui supports searching across multiple families/ analysis groups but there is no way to view a breakdown of the search on a per-gene basis, the results are just shown as the standard list of variants. We should add a way to drill into the search results to get this breakdown.  @anneodonnell and @alovgren  to fill in details of what information should be included

**Comment by alovgren** [comment]
Highlighting/tagging (or sort by) the high pLI and missense constrained genes as well as genes in OMIM that multiple families have a variant(s) in that match the search criteria

**Comment by alovgren** [comment]
the ability to hover over the family number to get phenotype information
