### ISSUE TITLE
Tag options missing

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#683]
Hi Hana, 

The ability to tag has disappeared in Greka_WGS. https://seqr.broadinstitute.org/project/greka_wgs/family/GRE_002/mendelian-variant-search#search/4b495777/results

Thanks. 
Stephanie

**Comment by hanars** [comment]
Sorry about that, this is fixed now

**Comment by stephditroia** [comment]
Thanks! Glad to have you back! :)



Stephanie Parker DiTroia, PhD
Clinical Genomic Variant Analyst
Broad Institute of MIT and Harvard
sditroia@broadinstitute.org <alovgren@broadinstitute.org>
