### ISSUE TITLE
ClinVar not matching seqr

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#684]
ClinVar has this variant as pathogenic (https://www.ncbi.nlm.nih.gov/clinvar/variation/279997/) but in seqr it's marked as a VUS
https://seqr.broadinstitute.org/project/R0420_engle_wgs_900/saved_variants/variant/SV0010085_75527833_r0420_engle

I'm not sure why there is a discrepancy but wanted to make a note of it. It looks like the ClinVar entry is from 11/2017.

**Comment by hanars** [comment]
If you look at that family, it's data was loaded on 11/15/17 and that clinvar record was updated on 11/29/17
