### ISSUE TITLE
Can't access saved variants

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#687]
Hi Hana, I have a problem that's been happening on and off for the last several months; Eleina's reported having this problem as well, so I know it's not just me. Sometimes when I try to access a saved variant for a family by clicking the colored bar in the upper R screen, it just gives me a blank page saying "showing 0 variants." This persists if I then click on one of the colored bars to access the variants of that particular category (eg "analyst high priority"). The only way I can access saved variants is to then go to the deprecated variant page, which shows me the variant and all its info. Because I can use this workaround, I haven't reported the issue for the last several months, even though it happens almost daily. Today for a brief time I couldn't even access the variant through the deprecated page, so I thought I should report just in case this is an issue in the future. Thank you for your help!

![screen shot 2019-01-11 at 9 35 14 am](https://user-images.githubusercontent.com/41243189/51040132-ac2ce300-1584-11e9-9a8e-43dd045acaf5.png)
![screen shot 2019-01-11 at 9 35 23 am](https://user-images.githubusercontent.com/41243189/51040140-b0f19700-1584-11e9-8fec-62bbe2f36717.png)
![screen shot 2019-01-11 at 9 35 49 am](https://user-images.githubusercontent.com/41243189/51040147-b353f100-1584-11e9-8fd0-8de8b1c0d3ca.png)

**Comment by hanars** [comment]
Hi Julie, 

This issue should now be fixed. If you see this in the future, please submit another issue specifying the family/s where you are seeing the problem. Also, in the future if you encounter a bug but have a workaround for it you should still submit an issue, just mention in the ticket that you have a workaround so I know its not so urgent. If you don't report things I don't know to fix them!
