### ISSUE TITLE
Display name for Individual ID - CMG Myoseq Exomes Project

### ISSUE THREAD

**Issue by Jchangster** [macarthur-lab/seqr#691]
[cmg_myoseq_exomes_individuals.xlsx](https://github.com/macarthur-lab/seqr/files/2770364/cmg_myoseq_exomes_individuals.xlsx)
https://seqr.broadinstitute.org/project/R0382_cmg_myoseq_exomes/project_page

**Comment by hanars** [comment]
This is fixed now. Can you create another ticket explaining what went wrong so I can make sure it doesn't happen next time?
