### ISSUE TITLE
gene not recognized

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#697]
Hi Hana, when I search for the gene CYFIP1 under the gene info page, I see an entry:

https://seqr.broadinstitute.org/gene_info/ENSG00000273749

When I search for variants in CYFIP1 on the family search page, I get an error that CYFIP1 isn't a recognized gene:

https://seqr.broadinstitute.org/project/Engle_WGS_900/family/109/mendelian-variant-search#search/b5b11a9a/results

Then when I search by ensembl gene ID ENSG00000273749, I get a result:
https://seqr.broadinstitute.org/project/Engle_WGS_900/family/109/mendelian-variant-search#search/b5b11a9a/results

Any ideas on what might be going on? I'm able to search other gene names fine (eg TLE4) just using that name and not the ensembl ID: 
https://seqr.broadinstitute.org/project/Engle_WGS_900/family/109/mendelian-variant-search#search/ff5e2412/results

Thanks!

**Comment by hanars** [comment]
Thanks for letting me know! this is fixed now
