### ISSUE TITLE
search error: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#701]
Hi Hana, I'm getting an error for this family when searching w/ AD inheritance MAF 0.001:

https://seqr.broadinstitute.org/project/Engle_Exome/family/AOL/mendelian-variant-search

search error: 'NoneType' object has no attribute 'split'

Thanks!
Julie

**Comment by hanars** [comment]
This is due to an issue with the latest callset breaking search for the old families. Discussed offline and are comfortable leaving these broken until the new callset is loaded
