### ISSUE TITLE
New seqr tag- feature request

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#703]
Hi,

The Walsh group requested for an additional 'Sanger - troubleshooting' tag. Anne has approved. 

Thanks.

**Comment by hanars** [comment]
Is this supposed to be added to all projects, or to a specific subset of projects, and if so which?

**Comment by lynnpais** [comment]
This is for the Walsh projects -
<img width="282" alt="screen shot 2019-01-29 at 11 36 42 am" src="https://user-images.githubusercontent.com/37872186/51923995-2f8a6900-23ba-11e9-959b-4a98599cb5e1.png">

However, if it is applied to all, there is no issue.

**Comment by hanars** [comment]
Confirmed with Anne that we want this to applied to all

**Comment by hanars** [comment]
This tag has been added to all projects
