### ISSUE TITLE
can't get to deprecated saved variants page

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#707]
Hi Hana, occasionally I can't see the allele balance/sequencing quality of saved variants in seqr, so I have to revert to the old version in order to see them. I'm now getting an error 500 when I attempt to do that with the variants in this family:

https://seqr.broadinstitute.org/project/Engle_WGS_900/saved-variants?family=200

Thank you!

**Comment by hanars** [comment]
Hi Julie, you should also submit issues when the new pages are not working

**Comment by hanars** [comment]
This is fixed now
