### ISSUE TITLE
search error: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#708]
Hi, getting this error when I try to do searches on families in our Engle_WGS_900 cohort: 

search error: slice indices must be integers or None or have an __index__ method

As an example:
https://seqr.broadinstitute.org/project/Engle_WGS_900/family/174/mendelian-variant-search

Thank you!

**Comment by hanars** [comment]
This is fixed now, thanks for letting me know!
