### ISSUE TITLE
Search by sample ID in edit individuals/family tag

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#710]
The edit families and edit individuals tab only features 12 entries per page and have no option to either search for an individual or skip pages beyond the first/last 5. With some seqr projects now totaling over 1000 individuals, it can be difficult to delete samples due to both large time spent scrolling and needing to confirm the correct sample is selected when most IDs are longer than the window. This makes it difficult to remove samples that fail relatedness checks or that will no longer be sequenced, leading to confusion on the analysts' end and occasionally trouble running family-based searches.

Can you please add a text box filter to these pages so we can skip to the specific family? We always confirm the exact ID ahead of time so it can require the exact string if that makes it easier on your end. A search feature that skips to the right page should also work, but if possible a filter would be ideal.

Please consider this a medium/high priority issue as Jaime has a number of Myoseq, Pierce, and other large cohorts with duplication/mix-up issues she cannot quickly resolve without one of these options.

**Comment by katie-larkin** [comment]
Most duplicate or mixed-up samples wind up being deleted from seqr. We could potentially move them into dummy families in the meantime if necessary and the search bug there is completely fixed, but that would just be a holdover until we can delete them.

I think we're all in agreement that bulk edit should never be an option for deleting samples, so fixing individual edit would be helpful for those cases.

This can definitely go behind seqr search updates and bugs in priority, but it's going to make at least Pierce and Myoseq ugly until fixed, so we'd like it within the quarter at least.

**Comment by hanars** [comment]
Ah, I forgot that theres no bulk delete functionality, which you correctly point is for the best. I'll prioritize accordingly

**Comment by hanars** [comment]
There is now a filter box at the bottom of the bulk edit forms that allows you to family by family_id/ individual_id respectively (@Jchangster fyi)

**Comment by Jchangster** [comment]
Thank you so much for this!! Really helpful feature
