### ISSUE TITLE
Moving individuals between projects (myoseq & cmg_myoseq)

### ISSUE THREAD

**Issue by Jchangster** [macarthur-lab/seqr#713]
Hi Hana,

There are a few individuals that should be moved from myoseq_v20 to cmg_myoseq and vice versa. I've attached a spreadsheet below for the designations. Let me know if you need any other info, many thanks!
[Moving Individuals btwn Myoseq projects.xlsx](https://github.com/macarthur-lab/seqr/files/2809950/Moving.Individuals.btwn.Myoseq.projects.xlsx)

Best,
Jaime

**Comment by hanars** [comment]
This is done. Let me know if you see any issues

**Comment by Jchangster** [comment]
Great, this looks all good to me, thanks!
