### ISSUE TITLE
Update gnomAD gene page links

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#714]
Variant links go to the right version but the gnomAD gene page links go to the beta browser still. Should go to https://gnomad.broadinstitute.org/

![image](https://user-images.githubusercontent.com/10407888/51949809-0db1d600-23fc-11e9-86b7-4c7733ddd243.png)

**Comment by hanars** [comment]
Duplicates https://github.com/macarthur-lab/seqr-private/issues/409
