### ISSUE TITLE
Search frequency not performing as expected 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#716]
https://seqr.broadinstitute.org/project/cmg_gleeson_wgs/family/4292/mendelian-variant-search#search/206c715f/results
![screen shot 2019-01-30 at 3 10 47 pm](https://user-images.githubusercontent.com/37872186/52009587-4d7ec900-24a1-11e9-8865-3bb84e7e3691.png)

This allele seems to way above the search frequency of 0%.

**Comment by hanars** [comment]
There is a bug where if you apply the hom/hemi filter the af filter does not get applied.

**Comment by hanars** [comment]
Nevermind, hom/hemi filters do not work with AF filters, if you want to use the hom/hemi filter you can also apply an ac filter. I'll change the UI so when you set the hom/hemi filter it becomes more obvious that the af filter is un-applied, but this is behaving as expected when you do not apply an af or ac filter

**Comment by lynnpais** [comment]
The analysts would really like to be able to adjust the AF AND how/hemi filter. Anne agrees that this is a n important feature to have.
