### ISSUE TITLE
IGV.js just added native .cram support. With the right gcs auth, we could replace IGV proxy/gcs-fuse with direct access to gs:// .cram paths from seqr api code.

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#719]
This should allow setting bam_file_path to `gs:// ... .cram` and querying that directly from the seqr api after validating request permissions - similar to the way seqr currently handles .bam proxying.

**Comment by hanars** [comment]
Duplicated by https://github.com/macarthur-lab/seqr-private/issues/617
