### ISSUE TITLE
how to get access to broad deployment

### ISSUE THREAD

**Issue by vjcitn** [macarthur-lab/seqr#722]
I am a broad associate.  I tried to log in at https://seqr.broadinstitute.org/login?next=/ with broad credentials but they were not recognized.  Do I need a special registration?  Thank you

**Comment by hanars** [comment]
Hi Vince, seqr requires it's own credentials for access, not your standard broad credentials. It is primarily used by the CMG (http://CMG.broadinstitute.org). If you are part of a group that currently uses seqr, you should ask them to add you to their project. If you are not and are also not part of the cmg but still need access to seqr, let me know and I can connect you with the appropriate people
