### ISSUE TITLE
Adding Kindreds still buggy. 

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#727]
I can add kindreds to 'Additional Unrelated Kindred w/ Causal Variants in Gene' by up and down arrows only and cannot see how many I am adding until I click submit. 

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0045175_876850885_r0384_rare

![kindreds copy](https://user-images.githubusercontent.com/44381119/52232217-f0608a00-2889-11e9-97ac-8d1b03cd2fee.jpeg)

**Comment by hanars** [comment]
This is fixed now
