### ISSUE TITLE
Submission to the Matchmaker Exchange

### ISSUE THREAD

**Issue by kounap** [macarthur-lab/seqr#730]
I cannot submit two cases to MME - OUN_HK135 and OUN_HK136. I have tried in last week and now again. It just freeze and not opened the choice of clinical features and gene data.

![mme](https://user-images.githubusercontent.com/45018438/52359958-e913ba80-2a08-11e9-8e21-d620d18694f1.jpg)

**Comment by hanars** [comment]
Hi Kati thanks for letting me know. This is fixed now
