### ISSUE TITLE
searches not working for Engle Exome family

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#731]
Hi Hana, we're having trouble getting searches to work for one of our families in the Engle Exome cohort. It's not coming up with any variants, even when I drop the variant quality filters dramatically or raise the allele frequency filters. It won't work with custom searches, all variant searches, or Mendelian inheritance searches. Thanks very much!

https://seqr.broadinstitute.org/project/Engle_Exome/family/KA/mendelian-variant-search#search/153d8d5c/results

**Comment by hanars** [comment]
Hi Julie, 

It looks like KA-09 was not included in the latest callset somehow. This means if you apply any gq/ ab filters or inheritance filters nothing will be returned. However, if  you do not apply any of those filters you do see results: https://seqr.broadinstitute.org/project/Engle_Exome/family/KA/mendelian-variant-search#search/504a3457/results

I have no idea why that sample is missing. That is a question for the PM team
