### ISSUE TITLE
Improve automatic/inconsistent display of rich text for notes 

### ISSUE THREAD

**Issue by hanars** [macarthur-lab/seqr#746]
@zmcv to provide examples

**Comment by stephditroia** [comment]
https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/family_page/F019053_ogi1518

**Comment by hanars** [comment]
Closing this out because this was related to inconsistent note formatting between old and new pages so no new issues will happen. Since there seem to be only a few examples of this and they can all be manually fixed through the ui there does not seem to be any need for an engineering fix
