### ISSUE TITLE
Match Maker Exchange not working for Greka_WGS project

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#749]
Hey Hana - mentioned this to you yesterday during the analyst meeting. "Submit to the Matchmaker Exchange" prompt will come up but will not allow me to submit. Specifically on Greka_WGS: family GRE_002. Thanks. 

https://seqr.broadinstitute.org/matchmaker/search/project/greka_wgs/family/GRE_002

**Comment by hanars** [comment]
This is fixed now
