### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#751]
Hello,

One of our collaborators, Safoora Syeda, is running into an Server Error. She says, "Its happening whenever I am searching for any genes in a family or in a cohort.

For example when I searched for a particular gene in a cohort https://seqr.broadinstitute.org/project/cmg_kang_lgmd_wes/gene/ENSG00000135486?selected_projects=Kang_v11

Also I am attaching a second type of error which I got for the above search."

![error2](https://user-images.githubusercontent.com/37872186/53098865-93540d80-34f2-11e9-9bdd-710fbdaa640e.PNG)

**Comment by hanars** [comment]
this is due to an issue with the data being removed. Mike is working on reloading it

**Comment by hanars** [comment]
This is fixed now, thanks for your patience
