### ISSUE TITLE
Can't add tags from variant search

### ISSUE THREAD

**Issue by jules-o** [macarthur-lab/seqr#752]
Hi, I'm running seqr as local install on Ubuntu 18.04, would like to add tags from variant search but the Add Tags popup doesn't actually list any tags. I can add notes OK and if I go to the Saved Variants page then I can add tags there, but not in the search results. 
Could that be fixed?

**Comment by hanars** [comment]
Run: ` ./manage.py loaddata variant_tag_types.json`

**Comment by jules-o** [comment]
Thanks hanars. I get: 
```
django.db.utils.IntegrityError: Problem installing fixture '/home/flutabex/seqr/seqr/fixtures/variant_tag_types.json': Could not load seqr.VariantTagType(pk=None): duplicate key value violates unique constraint "seqr_varianttagtype_guid_key"
DETAIL:  Key (guid)=(VTT_tier_1_novel_gene_and_phen) already exists.
```

**Comment by hanars** [comment]
Okay, run `./manage.py add_default_tags --all`

**Comment by jules-o** [comment]
That's done the trick :) Thank you!
