### ISSUE TITLE
Gleeson exomes project not loading

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#761]
All cases in the Gleeson exomes project don't seem to be loading. Here's one example- https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/family_page/F013041_5279
<img width="1317" alt="screen shot 2019-02-28 at 9 52 37 am" src="https://user-images.githubusercontent.com/37872186/53575027-b740d000-3b3e-11e9-9709-aa0126936f69.png">

**Comment by hanars** [comment]
This is working again
