### ISSUE TITLE
Change in individual status 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#762]
Hello,

The page won't save after making a change- https://seqr.broadinstitute.org/project/CMG_VCGS_Exomes/edit-individuals

<img width="1277" alt="screen shot 2019-02-28 at 10 15 01 am" src="https://user-images.githubusercontent.com/37872186/53576550-f4f32800-3b41-11e9-9512-2e2087b2e110.png">

**Comment by hanars** [comment]
Please do not use this page, it is deprecated. Use the "edit individuals" option on the new project page
