### ISSUE TITLE
Enable IGV reads

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#765]
Hi, the newer samples in the VCGS_exomes project do not have the show reads function on the new page. Here's one example- https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/family/F024835_vcgs_fam108/Review
<img width="1195" alt="screen shot 2019-02-28 at 2 05 21 pm" src="https://user-images.githubusercontent.com/37872186/53591405-e9aff480-3b61-11e9-9e23-8981cf1f8984.png">

**Comment by hanars** [comment]
This is fixed now
