### ISSUE TITLE
Add ability to sort variants in search results by SpliceAI score

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#767]
We are really trying to find a novel gene from RNA-seq data in the next 2 weeks to present at the GSP/CMG NIH meeting. It's high priority from Daniel - I'm trying to find variants and Jorge is looking at them in the RNA-seq data. Given we have Illumina's new splice tool, it would be really helpful if I could sort results by this SpliceAI score. This would be in the old search interface for now because of the time crunch (RNA-seq samples are scattered in different projects). Is this possible to get soon?

![image](https://user-images.githubusercontent.com/10407888/53655188-8388a780-3c1d-11e9-8673-becfab663acd.png)

**Comment by hanars** [comment]
I will add SpliceAi sorting to the old UI, and will add that as well as cadd and revel to the new search ui. This will only work in the most recently loaded projects that have that score

**Comment by hanars** [comment]
This is done now. You will want to make sure to sort with order "desc" so the worst variants end up at the top
