### ISSUE TITLE
CMG_Estonia_WGS - HK104

### ISSUE THREAD

**Issue by kounap** [macarthur-lab/seqr#774]
The search for the case HK104 in CMG_Estonia_WGS Project is not working.
I am adding screenshot. "See sait teatab" - the translation is "This site is saying".
![screenshot hk104](https://user-images.githubusercontent.com/45018438/54039056-fb138500-418f-11e9-8a13-1582eefee7a6.jpg)

**Comment by hanars** [comment]
@mike-w-wilson it looks like HK104-003_1 was in the callset loaded on 1/28/2019 but the other 2 individuals in the family were not, which is causing search to break

https://seqr.broadinstitute.org/project/R0332_cmg_estonia_wgs/family_page/F020250_hk104

**Comment by mike-w-wilson** [comment]
This looks like a case where the sample name was changed in seqr while the project was actively being loaded. I have asked the PMs to not rename any samples that are in the project loading queue.  I will have to reload the project.

**Comment by mike-w-wilson** [comment]
I reviewed this and the following samples were removed from the callset. 
HK015_0038
HK035_0090
HK048_0119
HK048_0120
HK104-001_1
HK104-002_1
HK032-0081_2
HK032-0081_3
I have reached out to the PMs to see why.

**Comment by mike-w-wilson** [comment]
It seems that all of these samples were flagged for elevated chimera but somehow were included in the callset back in October 2017. These samples should not have ever made it into seqr.

**Comment by hanars** [comment]
Reopening this as search is  still not working for those families. The solution is just (apparently) not to reload data

**Comment by mike-w-wilson** [comment]
Hi @kounap, the following samples were removed from our callset sometime between October 2017 and January 2019 for elevated chimera. 

HK015_0038
HK035_0090
HK048_0119
HK048_0120
HK104-001_1
HK104-002_1
HK032-0081_2
HK032-0081_3

Since those samples were previously loaded, search broke for the entire family. Katie Larkin removed  those samples from seqr with the exception of HK104-001_1 and HK048_0119 as those are probands with tagged variants. Search should now be working for the other three families.

**Comment by hanars** [comment]
@mike-w-wilson any update on the status of HK104 and HK048?

**Comment by mike-w-wilson** [comment]
No update. I'm not sure who makes the call on deleting those individuals since they have tagged variants.

**Comment by hanars** [comment]
@kounap what would you like us to do for those individuals? Or do you know who should make that call?

**Comment by katie-larkin** [comment]
@kounap last I heard on these individuals we were waiting to hear from your team if you have additional material you would like to resubmit for sequencing. If you do, we should try to keep the samples in for now and work on whether it's possible to transfer over variant tags or use them as a guide to restart analysis. If you will not be reattempting those individuals and would like us to delete them, we can do so now but would not be able to save tags or other information.

**Comment by kounap** [comment]
@katie-larkin We had an agreement with you that we will sequence these individuals again. We have already preparing DNA samples and try to get as much as possible new blood sampling and DNA extraction. We definitelt will have the DNA from all of the,. My colleagues in Estonia are doing the best in this matter and we are ready to send these DNA-s to you on May 7. Please send us the kit for these eight DNA-s.

**Comment by katie-larkin** [comment]
@kounap sounds great. In that case, we'll keep HK104 and HK048 in seqr until the data is ready.

@hanars and @mike-w-wilson, is there a way we will be able to copy some of the tagged variants or other data from these samples over to the new ones? I could rename the seqr entries to match the VCF ID of the upcoming replacement samples, but I'm not sure if that would do more harm or good in loading...

**Comment by hanars** [comment]
By far the easiest thing to do would be to leave the exiasting individuals in seqr alone and then we can either use those same sample IDs for the reloaded samples in the new VCF, or we can use different IDs in the VCF but map them to different IDs in seqr itself. But as long as we don't create new individuals in seqr, all the data and tags will be maintained

**Comment by hanars** [comment]
@katie-larkin any idea when the data will be ready for this one?

**Comment by katie-larkin** [comment]
Half of the samples failed again due to high chimera, the other half are currently running in the WGS callset.
https://broadinstitute.atlassian.net/browse/MACLAB-6486
