### ISSUE TITLE
IGV reads not loading

### ISSUE THREAD

**Issue by lecb** [macarthur-lab/seqr#791]
Hi,
Reads will not load for the newly loaded cmg_thaker_wes callset. When clicking reads, "error loading track data" appears. This seems to be affecting all samples in this callset.
Many thanks in advance!

**Comment by hanars** [comment]
@mike-w-wilson it looks like all the bams for this project got moved, when I look in the directory where they are suppsed to be I see all the files with `.bam@`, `.bai@`, and `.bam.bai@` extensions but none of the actual bams

**Comment by mike-w-wilson** [comment]
The server where all the bams are stored on-prem is currently down. This should be resolved once that comes back up.
