### ISSUE TITLE
Error loading IGV

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#794]
<img width="1329" alt="Screen Shot 2019-03-21 at 9 53 28 AM" src="https://user-images.githubusercontent.com/37872186/54756821-5e091100-4bbf-11e9-9545-e64da0f1961a.png">

https://seqr.broadinstitute.org/variant_search/results/15178c0436c85970046c187b5040c712?page=1&sort=xpos 

IGV not loading. Please see the reads for MITF. Thank you.

**Comment by hanars** [comment]
As Mike mentioned in the seqr channel yesterday, bams are unavailable for all internal exome projects. Please monitor there for updates

**Comment by hanars** [comment]
This is fixed now
