### ISSUE TITLE
Link to variant across callset

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#802]
On a search page, each variant has a description of its frequency in the CMG callset, eg. 3 alleles in the callset. It would be fantastic if we could click on this to identify which cases the other two alleles fall in. This is particularly useful in cases where a variant appears to be absent in exac/gnomad, but present in the CMG callset. It is fine if the link takes you to a search page, to locate all the variants in the CMG callset. Thanks so much!

**Comment by hanars** [comment]
Under the variant's position next to the "google" and "pubmed" links, there is now a "seqr" link. This will take you to a page that searches for that variant across all projects you have access to that have new search. It's not *exactly* searching within the callset, as it will also include variants in other callsets (as a main example, our callsets are either all genomes or all exomes but this will search across genome and exome projects)
