### ISSUE TITLE
Load WGS Data in Genome Project A

### ISSUE THREAD

**Issue by gvannoy** [macarthur-lab/seqr#815]
Genome Project A contains 5 previously sequenced RGP families (20 individuals). Please load the WGS data for these families: RGP_80, RGP_101, RGP_240, RGP_431, RGP_402.

This will be used by the ClinVar/Broad Course attendees on May 15-16. If it could be completed in the next two weeks to allow time for demoing before the course that would be ideal. Thanks!

**Comment by hanars** [comment]
Also loaded it to all the other genome projects
