### ISSUE TITLE
Cannot edit individual_ids for projects with no data

### ISSUE THREAD

**Issue by gvannoy** [macarthur-lab/seqr#823]
When editing family and individual names in Genome Project A, I got the attached error message when I tried to save. The families/individuals had originally been uploaded from a spreadsheet though bulk upload. I was able to delete the families and do a new bulk upload with corrected names to solve the problem, but this may be an issue for other users trying to manually edit family/individual names. 
[github error.docx](https://github.com/macarthur-lab/seqr/files/3108837/github.error.docx)

**Comment by hanars** [comment]
![upload_error](https://user-images.githubusercontent.com/24598672/56613070-de1dfe80-65e3-11e9-8619-f31448513648.png)
