### ISSUE TITLE
404 error with Walsh lab exomes

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#825]
https://seqr.broadinstitute.org/project/R0346_walsh_lab_exomes/project_page

![Screen Shot 2019-04-24 at 9 18 54 AM](https://user-images.githubusercontent.com/37872186/56662460-07856b80-6672-11e9-9888-8676a9bf3f1f.png)

**Comment by hanars** [comment]
This is fixed now

**Comment by mdfleming** [comment]
I'm having the same issue now with the Fleming lab exomes.  404 error when clicking on project.

<img width="1407" alt="Screen Shot 2019-04-24 at 12 35 38 PM" src="https://user-images.githubusercontent.com/49955895/56677380-6d7fec00-668e-11e9-839e-b188b51c02b7.png">

**Comment by hanars** [comment]
Thats not actually the same issue, please make a separate ticket. Also, in general, pleas eprovide links to all errors instead of/ in addition to screenshots
