### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by mdfleming** [macarthur-lab/seqr#827]
Data for Fleming lab won't load when i click on the link
<img width="1399" alt="Screen Shot 2019-04-24 at 12 55 54 PM" src="https://user-images.githubusercontent.com/49955895/56678299-58a45800-6690-11e9-8a1f-694033f255b8.png">

https://seqr.broadinstitute.org/project/R0496_cmg_fleming_wes/project_page

<img width="1407" alt="Screen Shot 2019-04-24 at 12 35 38 PM" src="https://user-images.githubusercontent.com/49955895/56677244-1712ad80-668e-11e9-8a22-0bfc91768faa.png">

**Comment by hanars** [comment]
This is fixed now. It appears someone improperly moved samples in between families and deleted family/s. In the future, all modifications to samples and families must go through our PM team

**Comment by mdfleming** [comment]
Thanks. M



Mark D. Fleming, MD, DPhil
S. Burt Wolbach Professor of Pathology
Harvard Medical School
Pathologist-in-Chief
Boston Children’s Hospital
Bader 139.1
300 Longwood Ave
Boston, MA 02115
Ph: 617-919-2664
Fax: 617-730-0168
