### ISSUE TITLE
Saved variants not showing 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#829]
https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/family/F023659_mc8000/Review

tagged variants aren’t being displayed when you click on the saved variants bar.  For example there are 6 variants tagged in MC8000 and when you click on the blue bar on the right of the family page, the resulting page is blank (for me at least)
<img width="1208" alt="Screen Shot 2019-04-25 at 10 34 53 AM" src="https://user-images.githubusercontent.com/37872186/56744055-cbbbd600-6745-11e9-9dc0-a47948d4c040.png">

**Comment by hanars** [comment]
This is fixed now
