### ISSUE TITLE
Variant search returning 401 and 504 messages

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#830]
I got this error yesterday as well as today for the same RGP case-https://seqr.broadinstitute.org/variant_search/results/b6db8197849d0251716f3945673d018c?page=1&sort=xpos
<img width="1201" alt="Screen Shot 2019-04-25 at 11 04 28 AM" src="https://user-images.githubusercontent.com/37872186/56746302-f019b180-6749-11e9-8ce0-efb9b5331d83.png">

**Comment by hanars** [comment]
resolved as part of https://github.com/macarthur-lab/seqr/issues/828
