### ISSUE TITLE
Cannot bulk upload individuals from current individuals template

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#833]
I'm trying to bulk upload to adjust individual IDs in samples without data and when I try to reupload from the current individuals template it gives an error that the 2nd row doesn't match the headers it's looking for.

I believe seqr may be confusing the current individuals template with the pedigree/manifest template.

**Comment by hanars** [comment]
Can you please include the file that is failing here and the name of the project where this is failing

**Comment by katie-larkin** [comment]
Hey, it looks like the problem was just with csv files. Once I saved the file as an xslx it wound up working?
[cmg_lerner-ellis_ext_wes_individuals (1) same id.xlsx](https://github.com/macarthur-lab/seqr/files/3132751/cmg_lerner-ellis_ext_wes_individuals.1.same.id.xlsx) in https://seqr.broadinstitute.org/project/R0493_cmg_lerner_ellis_ext_wes/project_page

**Comment by hanars** [comment]
probably there was a data field with a comma in it that wasn;' properly encoded in the csv. Marking this closed since it is working now
