### ISSUE TITLE
Visibility of default searches box

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#839]
I've have a number of people tell me that they did not see the default searches. Can it stand out more?

**Comment by hanars** [comment]
Sure. How about bringing it over to the left like this
<img width="1478" alt="Screen Shot 2019-05-02 at 5 38 36 PM" src="https://user-images.githubusercontent.com/24598672/57108569-300c0600-6d01-11e9-96ab-77d0807cf170.png">

**Comment by anneodonnell** [comment]
I think I like it on the left like that. I think the title should be different - "Saved Searches" and the drop down box be tinted red or something that stands out.

**Comment by hanars** [comment]
Hmm, red look like an error. What about something like this
<img width="1473" alt="Screen Shot 2019-05-02 at 5 57 39 PM" src="https://user-images.githubusercontent.com/24598672/57109564-ce00d000-6d03-11e9-9a61-f984b9fb1b10.png">

**Comment by anneodonnell** [comment]
Sure, that seems good. I might try making the dropdown box a bit bigger.
