### ISSUE TITLE
Unusual seqr error freezing search

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#840]
This is from Tiong Tan, one of our Australian collaborators. He just reloads the page and is able to avoid this but I wanted you to know it was happening. 

Here are the steps that result in a Seqr error:

1. Variant search (I did this in Fam117, but it happens with any family)
2. Click dropdown box for inheritance (I used Recessive, but happens for de novo/dominant too)
3. Open the Frequency "tab"
4. Click the up or down arrows in the AC or AF boxes (without touching any of the sliders)
5. White screen of death necessitating several clicks of Back Arrow or reset

I get this using Safari Mac OSX Mojave, and Lyndon gets it with Chrome on Win10

**Comment by hanars** [comment]
I am having trouble recreating this. There are also no up/down arrows for AF. Can you confirm exactly what he is clicking

**Comment by anneodonnell** [comment]
Hmm, I can't recreate it either but I saw it happen when I was visiting there. He also emailed me this morning saying  

"just found that the same bug happens if I try to move the slider bar at step 4 (without adjusting anything else in that tab).
Then when I try to click backwards to safety, I get this message:"
<img width="357" alt="image001" src="https://user-images.githubusercontent.com/10407888/57148029-cb9b8600-6d96-11e9-985f-9d363d39d385.png">

**Comment by hanars** [comment]
So one potential reason is we don't support safari, but he did say someone else was seeing it in chrome. Could you ask them to update to the latest version of chrome and see if it still happens?

**Comment by anneodonnell** [comment]
OK. I'm going to copy you on the email.

**Comment by hanars** [comment]
Has there been any update on this?

**Comment by anneodonnell** [comment]
I haven’t heard anything. Probably fine to close it.

On Jul 1, 2019, at 1:45 PM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:


Has there been any update on this?
