### ISSUE TITLE
AR-one hit tag download

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#845]
Is it possible to get a list or download of the AR-one hit tags in seqr? 

I'd be interested in project, family, gene, variant with tag and a link to the variant page for the family. This is a request I'll likely make from time to time for a side analysis project. 

I'm asking now because I have a meeting with Qingbo on Thursday where having this data would be handy but not essential. But I'm likely to ask for this type of data from time to time so some way I could access it would also be handy. It's not urgent (2 months would be reasonable to wait but sooner would also be nice and if it needs to be longer, I'd deal).

**Comment by hanars** [comment]
I will almost definitely not be able to get this to you this week. In the short term, you may want to consider downloading the discovery sheet, which includes all the variants with discovery tags in all the projects and has a column with inheritance mode so you could filter for AR

**Comment by anneodonnell** [comment]
I tried this but realized it's not a discovery tag (and these cases are unsolved so they won't have discovery tags so that doesn't work. It's not urgent (and this week's meeting happened), just helpful to be able to access in the future.

**Comment by hanars** [comment]
I've added a staff page for this: https://seqr.broadinstitute.org/staff/saved_variants/Confident%20AR%20one%20hit
