### ISSUE TITLE
Pedigree image

### ISSUE THREAD

**Issue by kounap** [macarthur-lab/seqr#846]
All pedigree images are missing in Estonian external exomes, CMG_Estonia_WES and CMG_Estonia_WGS projects. This is already for some weeks. In some cases they have appeared again, but presently they are missing in all cases.

**Comment by hanars** [comment]
This is fixed now

**Comment by kounap** [comment]
I am sorry, but I saw those pedigree images for some seconds and they disappeared again. The situation is the same. They are missing in all projects.

**Comment by hanars** [comment]
I see them fine. Can you check again?

**Comment by kounap** [comment]
Thank you! Now is finne.
