### ISSUE TITLE
Trying to see "saved variants" by clicking on tag doesn't work

### ISSUE THREAD

**Issue by erzampag** [macarthur-lab/seqr#847]
Hi,

I am in the Pierce Lab cohort and trying to download the table for saved variants tagged with "review". When I am on the page "Project >> Pierce - Retinal Degeneration - CMG - Exomes"and click on the Review tagged hyperlink, it should have 1525 variants, but none of them load. Also, one of the times I tried it 3 of them loaded all from a single family, but that's no longer happening. Not sure if I'm correctly assuming what should happen when I click the link.

Thanks,
- Erin

**Comment by hanars** [comment]
This is now fixed
