### ISSUE TITLE
TOPMED link not working well for specific variant

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#849]
The TOPMED page for variant- https://seqr.broadinstitute.org/project/R0365_cmg_scott_exomes/saved_variants/variant/SV0049448_x129299623_r0365_cmg

isn't loading all the data- https://bravo.sph.umich.edu/freeze3a/hg19/variant/X-129299623-C-T
<img width="1261" alt="Screen Shot 2019-05-08 at 11 21 17 AM" src="https://user-images.githubusercontent.com/37872186/57386926-6a532880-7183-11e9-8f68-88f443055a04.png">

**Comment by hanars** [comment]
thats an issue with topmed, not seqr
