### ISSUE TITLE
CMG_Scott_Exomes Phenotips Q

### ISSUE THREAD

**Issue by Jchangster** [macarthur-lab/seqr#855]
Hi Hana,

I think I might be coming across a bug in this project. When I use the filter "No Phenotypes Entered", I don't see any families that are missing phenotips entry. However, I've found a few families like PED095, that when I look at the affected individual, it is not showing phenotips data entered. The collaborator also let me know that all the phenotips have been entered, so thinking that perhaps there is a bug for a few of the families?

Thanks,
Jaime

**Comment by hanars** [comment]
This is fixed now
