### ISSUE TITLE
Deselected annotation filters not working?

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#858]
If I analyze this family for CHD5 variants using the "all" and moderate to high impact variant filters of high quality, I come up with this variant:
https://seqr.broadinstitute.org/variant_search/results/10ba901793c325f2d4694bcb0846ad28?page=1&sort=xpos

When I use the same filters, except deselect "moderate to high impact", I get nothing:
https://seqr.broadinstitute.org/variant_search/results/a40e870aa046d3398b70d44e659af878?page=1&sort=xpos

In previous versions of seqr, deselecting variant annotations enabled a search of all coding or noncoding variants in a gene or proximal regulatory variants annotated with that gene's name, so was a really comprehensive way of searching for noncoding 2nd hits in high-priority candidate genes. Is this no longer the case?

**Comment by hanars** [comment]
This is a bug, deselecting those should result in the behavior you describe, so thanks for pointing that out. However as an FYI, if you click the "gene search" link on the variant result next to your gene of interest, it will take you to search page with all the hits for that family in that gene: https://seqr.broadinstitute.org/variant_search/results/74b1dda7e86ac2f21757ac4055687bc1?page=1&sort=xpos

**Comment by hanars** [comment]
This is fixed now
