### ISSUE TITLE
AnVIL Metadata export date filter for RGP

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#863]
In terms of preparation for RGP being added to AnVIL, can you please add some flexibility in the AnVIL staff page download to let us pull samples that have been in seqr at least a month.

We still need the year-based filter for CMG samples, so you could either make a separate download for RGP or a way to select a date and download all samples in the project that have data on seqr since at least that date.

This doesn't need to finish until the tags part of this is ready.

**Comment by hanars** [comment]
What is "the tags part of this"?

**Comment by katie-larkin** [comment]
I don't know the details, but apparently Mel and Alysia need to work out RGP tagging to figure out which variants they want to be pulled and have you tailor it to that. That's all the details I know and figured they had already raised this to you before

**Comment by katie-larkin** [comment]
I still don't know about tags, but when you have time can you add just the custom date filter? We would like to start adding RGP data to AnVIL this week or next.

**Comment by hanars** [comment]
I added a datepicker so you can specify all samples loaded before that given date. By default, it still loads everything older than a year
