### ISSUE TITLE
Feature request (not urgent)

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#869]
Hi Hana, would it be possible to have a new tag added to our englewgs900, engle exome, and CMG genome datasets? It would be nice to have some sort of tag that just allows tagging variants with a different color that is visible from the main project page and as a part of the large grouping of "Variant tags" from the main project page as well, so I can flag which variants I've put through my functional pipeline in fish or cells. Thank you!

**Comment by hanars** [comment]
Hi Julie,

What would you like this tag to be called? What category would it be part of?

**Comment by juliejurgens** [comment]
Hi Hana, would it be possible to put it under the "collaboration" subheading of variant tags and call it "Functional Screen"? Thanks very much!

**Comment by hanars** [comment]
sure

**Comment by hanars** [comment]
These have been added to the 3 requested projects
