### ISSUE TITLE
recombine "Pathogenicity" and "Annotations" sections

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#871]
![image](https://user-images.githubusercontent.com/6240170/57796581-8a03c700-7716-11e9-89db-a9090e1f8f2c.png)
I'd vote for going back to having Clinvar/Hgmd and VEP filters in one section because
- the current UI requires a pretty long sentence to explain behavior "Note this filter will override any annotations filter (i.e variants will be returned if they have either the specified pathogenicity OR transcript consequence)". With a combined section, no explanation is necessary.
- I was getting a "This search returned too many compound heterozygous variants" error, and it took me ~ 30 seconds to understand/remember why selecting only "Pathogenic"  variants still returned too many results. It would be much easier to see that too many annotations were also selected if everything was in one section.

**Comment by hanars** [comment]
This will be part of overall search UI feedback round, blocking this on getting full feedback from the analysis team

**Comment by hanars** [comment]
We are going to leave these separate and change behavior to make this work the way analysts expect per https://github.com/macarthur-lab/seqr-private/issues/684
