### ISSUE TITLE
Cannot create new Project at Step Four

### ISSUE THREAD

**Issue by Toseph** [macarthur-lab/seqr#875]
I get the following error when trying to hit submit on "Create New Project" after giving it a project name & description. 

`error: column seqr_project.last_accessed_date does not exist LINE 1: ...ase_area", "seqr_project"."disable_staff"access",`

The deployment was installed using the local_install steps on a Centos7.6 host and using python2.7 (system default). 

Just to preface how I got to this point, since there were some steps that are not covered in the local_install guide, I'll cover my setup steps. Following the local install guide verbatim did not work for me. I ran into issues at the create super user step (pasted below). The guide also does not mention that perl-core needs to be yum installed prior to this run, and the list of python modules is not up to date given that many new python modules are built for python3 and not python2 (guide calls for python2.7), so you need to specify deprecated versions for pip to install so it works (I can provide my pip freeze list if needed).  
```
[root@seqr02 thasan]# cd ${SEQR_DIR}; python manage.py createsuperuser
SystemCheckError: System check identified some issues:

ERRORS:
?: (corsheaders.E013) Origin 'localhost:3000' in CORS_ORIGIN_WHITELIST is missing scheme or netloc
?: (corsheaders.E013) Origin 'localhost:8000' in CORS_ORIGIN_WHITELIST is missing scheme or netloc
```
To fix this error, I made sure to edit settings.py in the seqr folder and adjusted the position of django's and cor's middleware plugins. Additionally, I had to add "http://localhost:3000" and "http://localhost:8000" to the "CORS_ORIGIN_WHITELIST" since I get the above error if I ommit http in the whitelist url. Finally, I ran "python manage.py migrate" and then "python manage.py migrate --fake-initial". 

After these steps were done, I was able to create the super-user and use the ./start_server script to see the webpage and login. However, I believe the steps I did to migrate the session and relations did not properly migrate any database relations that should have been implemented. 

Going back to the original issue, when I now login and go to create a new project, I get the column error. Is there someone who understands Django better who can tell me how to create a new DB and link it to this seqr install so new projects can be created/used? 

```
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'seqr.utils.middleware.JsonErrorMiddleware',
]
```

**Comment by bw2** [comment]
Hi Toseph, it's not immediately clear to me what the solution is. We can try troubleshooting in this thread, but it might be easier/faster to work through it over on skype/hangouts. Would you be interested in that?

**Comment by Toseph** [comment]
Hey @bw2, I could host a webex for us if you are still able to do so and do a screen-share. 
We have a second VM setup that I can use to show you my install steps in live-time. 

I have some time available between 10am - 2pm tomorrow if that might work.

**Comment by Toseph** [comment]
![Screen Shot 2019-05-28 at 12 34 35 PM](https://user-images.githubusercontent.com/7651720/58495265-09e15680-8145-11e9-9400-9962b76638d4.png)

the attached screenshot shows specifically where the error is coming from while trying to create a project.

**Comment by Toseph** [comment]
I can also prepare to do this later in the week with you when you have time. 
Keep me posted, and thank you for taking a look at this issue!

**Comment by bw2** [comment]
Hi Toseph, sorry I didn't see your message earlier and thanks for the extra details. Let me see if I can reproduce the issue based on this and get back to you.  Everyone here will be out for the next 2 days, but if I can't reproduce it, lets try again next week.

**Comment by Toseph** [comment]
Thanks for the follow-up, let me know how it goes. 
I'll be available to do a webex all week next week.

**Comment by Toseph** [comment]
Hey @bw2, hope everyone had a good weekend! 
When you have time this week, let me know how the installation steps went on your end.

Not sure if I've already mentioned this, but we are deploying seqr to a centos7.6 VM.

**Comment by bw2** [comment]
@Toseph Thanks. I'm deploying a clean install now, and will let you know.

**Comment by bw2** [comment]
@Toseph if you go into your seqr/ install directory and run 
`python manage.py migrate`
does it print any errors?

**Comment by Toseph** [comment]
@bw2 I am currently not getting any errors after that step. In the `CORS_ORIGIN_WHITELIST` section, did you also have to add "http://" in front of localhost before running `python manage.py migrate`

This is what I see while running migrate:
`[root@seqr01 seqr]# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, base, breakpoint_search, contenttypes, gene_lists, guardian, reference_data, seqr, sessions
Running migrations:
  No migrations to apply.`

**Comment by bw2** [comment]
No we haven't had to change CORS_ORIGIN_WHITELIST.

**Comment by bw2** [comment]
It does seem like the database didn't get initialized correctly, which caused this error
![image](https://user-images.githubusercontent.com/6240170/58896045-35bf8780-86c3-11e9-9146-19291f84e2fa.png)

If you could try killing your seqr server and running 
```
psql -U postgres postgres -c "drop database seqrdb"
```
Then, to reinitialize the database, do the following steps again (which I recently rearranged to change when reference data is loaded):
https://github.com/macarthur-lab/seqr/blob/dev/deploy/install_local.step6.install_seqr.sh#L79-L97

It wil print some sql errors about tables already existing, etc. but these can be ignored.
After that completes, you will need to re-create the superuser.

**Comment by Toseph** [comment]
@bw2 , thanks for the update!
I'm going to re-run these steps and recreate the super-user and get back to you.

**Comment by Toseph** [comment]
The revised django steps did correct the database error, but now I am getting an http error (likely because I made edits under the CORS_WHITELIST section). I am going to re-run seqr deploy from scratch but this time I will not modify the CORS_WHITELIST or settings.py and see how it takes. 

For reference, 
<img width="930" alt="Screen Shot 2019-06-04 at 1 23 15 PM" src="https://user-images.githubusercontent.com/7651720/58899977-33156000-86cc-11e9-9146-dd421342905b.png">

**Comment by Toseph** [comment]
I was able to correct the error by removing reverting settings.py to their default entries and re-running the database drop/add steps. From there, the super user was made successfully, server started as intended, and I was able to create the project database. 

At this point the original error is settled so we can mark this as fixed. 
I would like to ask if you can point me to where I can find .fam files to do the bulk-upload for families. 

Ultimately, once this is done, I will be passing it off to one of our researchers who will be using seqr for their own projects.

**Comment by bw2** [comment]
Great! 
If you create a project in seqr and go to the project page, you can click 
"Edit Families & Individuals"
![image](https://user-images.githubusercontent.com/6240170/58962986-539bf380-877a-11e9-999c-b3b6d46c1c34.png)

There, if you click on the "Bulk Edit Individuals" tab, it has a link to download a template Excel or .tsv file that can be populated with individuals in .fam file format.

You can then drag-drop this file onto the yellow box in that tab to load the information into your seqr project.


![image](https://user-images.githubusercontent.com/6240170/58963070-86de8280-877a-11e9-9f79-7a3c3b01b5af.png)
