### ISSUE TITLE
Variant ref pop coverage mismatch between browser and seqr

### ISSUE THREAD

**Issue by anneodonnell** [macarthur-lab/seqr#876]
Region appears covered in gnomAD browser and TopMed browser but listed in seqr as in 0 out of 0 genomes for both of these databases. Not sure what is going on. 

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0048589_9121785273_r0384_rar

![image](https://user-images.githubusercontent.com/10407888/58270713-7381ef00-7d58-11e9-8e85-00988f037eca.png)

**Comment by hanars** [comment]
Seqr does not actually have coverage data for variants that are absent from reference databases, so showing "0 out of 0" is a bug. I have update seqr to no longer show it
