### ISSUE TITLE
OMIM tag

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#885]
This gene / condition is in OMIM, but I do not see the tag on the variant page- https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F022173_rgp_466

<img width="1271" alt="Screen Shot 2019-05-30 at 8 29 49 AM" src="https://user-images.githubusercontent.com/37872186/58632948-1d133400-82b5-11e9-9221-2ab086fffe23.png">

**Comment by anneodonnell** [comment]
I was just about to enter the same issue - it looks like OMIM tags are missing across several projects. Here was the example I was going to share: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0017811_3132675903_r0384_rar

https://www.omim.org/entry/610552?search=UBA5&highlight=uba5

**Comment by alovgren** [comment]
This appears to be a widespread problem.  I checked all cases tagged with KPG in RGP, Pierce, Sue White, and Sherr.  OMIM is missing on all of them.

**Comment by hanars** [comment]
OMIM is now restored, sorry for the issue
