### ISSUE TITLE
Refactor gene reference data storage

### ISSUE THREAD

**Issue by bw2** [macarthur-lab/seqr#888]
Some ideas
- move reference_data tables to separate database (instead of seqrdb) to simplify backup/restore
- maybe uses manage commands for fixtures  instead of psql dump to avoid key contraint errors on restore
- GTEx data is large and seems out of place in the sql database. Perhaps worth checking with GTEx browser developers if there's some url we can use to load their expression graph in an iframe instead of generating it ourselves.

**Comment by hanars** [comment]
We now use Gtex's ui component which fetches the data via API instead of storing it ourselves. The reference data is now stored in a separate postgres db, reference_data_db, which simplifies backups considerably
