### ISSUE TITLE
Error loading IGV track data

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#892]
https://seqr.broadinstitute.org/project/R0456_cmg_walsh_exomes_ch/saved_variants/family/F023752_ch3700/Known%20gene%20for%20phenotype

<img width="1200" alt="Screen Shot 2019-06-10 at 8 57 11 AM" src="https://user-images.githubusercontent.com/37872186/59196863-d26ba480-8b5d-11e9-8b38-a1ef2c54927b.png">

**Comment by hanars** [comment]
this is fixed now
