### ISSUE TITLE
Saved variant page, zygosity not showing

### ISSUE THREAD

**Issue by kbuj** [macarthur-lab/seqr#895]
Sometimes, the zygosity of a variant is not showing on the saved variant page. It's not always the case and I have not understood the pattern...

<img width="1275" alt="Screen Shot 2019-06-10 at 11 33 09 AM" src="https://user-images.githubusercontent.com/44209434/59213951-0954b100-8b84-11e9-95a3-6402a70475f2.png">

**Comment by hanars** [comment]
I have fixed this issue for the family you included here. If you know of other families where this is an issue, please feel free to make another ticket (its okay to include multiple families in one ticket). 

Also, in the future when you submit tickets it is helpful if you can also include a link to the page where you see the issue, as well as a screenshot
