### ISSUE TITLE
IGV not loading for project

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#897]
IGV track data not loading for ALL individuals in the VCGS_exomes project. 

Here is one example- https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/family/F020364_fam61
<img width="1226" alt="Screen Shot 2019-06-10 at 2 16 35 PM" src="https://user-images.githubusercontent.com/37872186/59216822-7ff4ad00-8b8a-11e9-8b2c-e3e4720b7dc2.png">

**Comment by lynnpais** [comment]
FYI- I am meeting with the White group tomorrow evening, it would be great to have this back up by then. It was down at our last meeting as well.

**Comment by hanars** [comment]
this is fixed now for all the families I tried. Please feel free to reopen and comment if there are any families that I missed
