### ISSUE TITLE
Gene search for cases with no proband data

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#901]
Gene search should ignore/ not return variants for cases with no proband data- https://seqr.broadinstitute.org/variant_search/results/d4051e0fc1cb2c1b8520ae8f5870010c?page=1&sort=xpos
<img width="1247" alt="Screen Shot 2019-06-12 at 1 09 07 PM" src="https://user-images.githubusercontent.com/37872186/59371582-6c288280-8d13-11e9-8779-def4281300d7.png">

**Comment by hanars** [comment]
This is fixed now
