### ISSUE TITLE
Seqr display of constaint metrics 

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#904]
Gene constraint needs to be reordered and fixed in seq. E.g.- https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0034406_173850875_r0358_cmg_

<img width="1135" alt="Screen Shot 2019-06-13 at 11 54 30 AM" src="https://user-images.githubusercontent.com/37872186/59447909-1a92fd00-8dd2-11e9-9cfa-92fa64bb2579.png">
<img width="1152" alt="Screen Shot 2019-06-13 at 11 54 58 AM" src="https://user-images.githubusercontent.com/37872186/59447915-1c5cc080-8dd2-11e9-8b2d-2dd61207f8b4.png">

**Comment by hanars** [comment]
Turns out this is not a bug, its just a strong discrepancy between pLI and LOUEF. I have created https://github.com/macarthur-lab/seqr-private/issues/607 to track changing seqr to use these newer, better scores
