### ISSUE TITLE
IGV not loading for case

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#905]
https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/variant/SV0054507_151767935_r0451_cmg_
<img width="1122" alt="Screen Shot 2019-06-17 at 2 06 52 PM" src="https://user-images.githubusercontent.com/37872186/59626169-387d9c00-9109-11e9-80fa-d581b995a2b1.png">

**Comment by hanars** [comment]
Can you try again? I'm seeing them loading now (although it is being slow)

**Comment by lynnpais** [comment]
When I follow the above link to the variant, it no longer directs you to the variant, but to all all the variants in the project. 

IGV is now loading, so the original issue has been resolved.

**Comment by hanars** [comment]
The link just has a typo: https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/saved_variants/variant/SV0054507_151767935_r0451_cmg_ works fine
