### ISSUE TITLE
504 then 500 error

### ISSUE THREAD

**Issue by juliejurgens** [macarthur-lab/seqr#909]
https://seqr.broadinstitute.org/variant_search/results/3a1d6a920351301c6300a33946bc4ec0?page=1&sort=xpos

Hi Hana,

Tried to run AR search with standard parameters except adding utr and a few noncoding annotations (in link attached) but got these errors. We routinely used these search parameters in the past for individual families and were able to get results, so not sure what's happening. Thanks!

**Comment by hanars** [comment]
Hi Julie,

Can you go to that link again and confirm your issue? I'm seeing a successful search results page with 111 variants

**Comment by juliejurgens** [comment]
Yes, seems to be working for me now too. It's been acting up in this way sporadically for the last several weeks now, so not sure what's happening. In any case, seems to be working for now. Thanks!
