### ISSUE TITLE
Missense constrained genes rank order not consistent with Zscore

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#913]
Missense constrained genes rank order not consistent with Zscore. Pls refer to genes ZNF709 and MARK 4 here-
<img width="1233" alt="Screen Shot 2019-06-20 at 10 58 43 AM" src="https://user-images.githubusercontent.com/37872186/59859390-9ea53180-934a-11e9-9650-248977805e6e.png">
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F019668_rgp_95/Review

The actual scores are correct, but do not seem to be ranked correctly.

**Comment by hanars** [comment]
This is now fixed
