### ISSUE TITLE
Failed to build seqr ui

### ISSUE THREAD

**Issue by SimonLi5601** [macarthur-lab/seqr#919]
I am building without using using minikube.
npm --version 6.5.0
node version v11.9.0
I was able to "npm install" to install the dependencies. I didn't have problem to run "npm run start" neither.
However, when it comes to "npm run build", I got the error below, I followed the reference below to install react-scripts@>=2.0.0, but it didn't solve the problem. 
```
> node scripts/build.js

NODE_PATH:  
Creating an optimized production build...
Node#moveTo was deprecated. Use Container#append.

WebpackCleanupPlugin: 1 file(s) deleted.
Failed to compile.

Failed to minify the code from this file: 

 	./node_modules/igv/dist/igv.esm.js:20093:44 

Read more here: http://bit.ly/2tRViJ9

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! seqr@0.2.0 build: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the seqr@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Do you have any suggestion? Thanks!

**Comment by hanars** [comment]
Hi Simon, we actually also see that error when we build the assets. I'm not entirely sure why, but it doesn't seem to cause any problems so i've just been ignoring it

**Comment by SimonLi5601** [comment]
Got it!  I noticed it generated a new app file, but wasn't sure it was completed. Thanks, Hanna.

**Comment by NLSVTN** [comment]
It may be corrected if webpack plugin is updated:

https://github.com/webpack-contrib/terser-webpack-plugin
https://github.com/mishoo/UglifyJS2/issues/659

On the line that gives the error there is 'async' keyword and it is not supported by old minification plugin.

**Comment by hanars** [comment]
this is fixed now
