### ISSUE TITLE
HPO term error message

### ISSUE THREAD

**Issue by Jchangster** [macarthur-lab/seqr#934]
Hi Hana,

I came across an error message (screenshot attached) when trying to copy/upload HPO terms for the same individuals from Estonian External Exomes project to CMG_Estonia_WGS project. It specifically noted the error for individual HK100-001_D1. I also attached the file I'm trying to upload. 
[cmg_estonia_wgs_hpo_terms.xlsx](https://github.com/macarthur-lab/seqr/files/3347183/cmg_estonia_wgs_hpo_terms.xlsx)

Jaime
![Screen Shot 2019-07-01 at 4 04 26 PM](https://user-images.githubusercontent.com/33735854/60463646-8c64a680-9c1a-11e9-809f-950cb146c717.png)

**Comment by hanars** [comment]
It looks like that HPO term is not valid and we grandfathered it in to the old project but you can no longer add invalid HPO terms. It looks like the id got updated: https://ncim-stage.nci.nih.gov/ncimbrowser/pages/concept_details.jsf?type=sources&code=C0424631&sab=HPO&sourcecode=HP:0001002&checkmultiplicity=true

I would edit the file to replace the invalid HPO id with the new valid one and try that

**Comment by Jchangster** [comment]
Great thanks, I replaced the invalid id with the new valid term, and it worked!
