### ISSUE TITLE
How to run existing tests info

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/seqr#935]
Hi,

I am trying to run tests just by './manage.py test' but it is writing me:

django.db.utils.OperationalError: FATAL:  database "seqr_test_db" does not exist

How do you usually run tests? Where could I read about the specifically test-related installations for seqr?

**Comment by hanars** [comment]
The command I use for running tests is `./manage.py test -p '*tests.py' seqr`

There is no documentation around test related installations. We really see unit tests as something for our internal developers to use to maintain code quality, and not as something the people who want to use our code should really be needing to work with.

**Comment by NLSVTN** [comment]
Yeah, the command is giving the same error. I guess I need to install somehow 'seqr_test_db'.

**Comment by hanars** [comment]
It might be a pythonpath issue. You can also try editing the DATABASES setting in settings.py
