### ISSUE TITLE
problems adding collaborator to the project

### ISSUE THREAD

**Issue by kbuj** [macarthur-lab/seqr#938]
Hi, 
I am an admin on our of the projects and I was trying to add Emily Brown from our lab to this project. it seems like it worked as she is added on the webpage but she never got the email to set up the account. We verified that the email I have entered is correct. I was wondering if someone could have a look at it.
https://seqr.broadinstitute.org/project/R0311_pierce_retinal_degenerat/project_page

**Comment by hanars** [comment]
Can you ask her to go to the "forgot my password" link when she tries to log into seqr and use that to reset her password?

**Comment by kbuj** [comment]
it worked, thanks!

**Comment by hanars** [comment]
great!
