### ISSUE TITLE
Link to Monarch down

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#939]
The link to Monarch for a gene on seqr does not seem to be working. It consistently says, "No Results Found". The issue is seen across several projects;
![Screen Shot 2019-07-05 at 9 33 28 AM](https://user-images.githubusercontent.com/37872186/60725846-12793980-9f08-11e9-8992-9dfdfe3618a1.png)
 here's one e.g.https://monarchinitiative.org/search/ENSG00000158055

**Comment by hanars** [comment]
This appears to be a problem with the monarch site itself, not the seqr link. I'll try again in a couple days to see if they've fixed the site and if the link is still a problem

**Comment by hanars** [comment]
This link works fine now, it was an issue with monarch
