### ISSUE TITLE
Project tags for gene search

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#940]
Hi Hana,

Here's a list of all seqr projects with the general cohort phenotype we'd like it to be associated with. Some projects are intentionally left blank as we don't feel they need to be tagged. 

Let me know if this is clear and all you need. 

Thanks a lot!

[Project_tags_AKLedits.xlsx](https://github.com/macarthur-lab/seqr/files/3369257/Project_tags_AKLedits.xlsx)

**Comment by hanars** [comment]
Hi Lynn, this all looks good to me. Thanks for getting this pulled together

**Comment by hanars** [comment]
I have added all of these categories, and a quick pass looks right to me
