### ISSUE TITLE
Gene search 504

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#949]
Hi Hana,

I tried running the new gene search function using the phenotype tags. Its great that we have them! I removed projects are not yet on the new seqr version. But I am unable to get it to work. Thoughts on where it may be slipping up? 

https://seqr.broadinstitute.org/variant_search/results/e71f6aac592dbf547db3e0f957eceabb?page=1&sort=xpos

<img width="1240" alt="Screen Shot 2019-07-12 at 11 19 24 AM" src="https://user-images.githubusercontent.com/37872186/61139241-f42ab500-a496-11e9-999b-09a7f7fbcc02.png">

**Comment by hanars** [comment]
Hi Lynn,

Thats not a gene search, thats just a standard inheritance search. That returns way too many variants for seqr to be able to handle- it doesn't even work on a single project let alone on 9 of them. If you want to do searches across so many families/ projects, I highly recommend you restrict yourself to gene lists. Also, sometimes removing gq and ab filters can help with performance

Best,
Hana

**Comment by lynnpais** [comment]
Thanks. The issue was I hit gene search for a specific gene but it took me to the regular search. I didn't realize then that no gene was entered. Makes total sense.

I re-tried this morning for a specific gene, but I get a 504 error. I'll post about it in a new ticket.
