### ISSUE TITLE
Variant search - sort by 'ClinVar'

### ISSUE THREAD

**Issue by stephditroia** [macarthur-lab/seqr#953]
Add 'ClinVar' as a sort by option. This was a useful option in older seqr search that might have been missed during the transition. 

https://seqr.broadinstitute.org/variant_search/results/9f39b918374d1f26de2c36b652bcd841?page=1&sort=in_omim

Thanks.

**Comment by hanars** [comment]
This sort still exists, its just called "Pathogenicity"

**Comment by stephditroia** [comment]
Duh. Thanks for clarifying. :)


Stephanie Parker DiTroia, PhD
Clinical Genomic Variant Analyst
Broad Institute of MIT and Harvard
sditroia@broadinstitute.org <alovgren@broadinstitute.org>
