### ISSUE TITLE
Uploading Pedigree/Manifest to seqr does not give automated email

### ISSUE THREAD

**Issue by katie-larkin** [macarthur-lab/seqr#957]
Previously, uploading a new pedigree/sample manifest to seqr resulted in an automated email sending with a copy of the uploaded manifest and a version translated into BSP's format so that could be uploaded directly. For the past few weeks we haven't received any of these emails, which means we need to create the BSP manifests on our own.

It's a couple of minutes per kit, so not high priority, but it would be nice to have it to both save time and as a confirmation.

Thanks!

**Comment by hanars** [comment]
Nevermind, I figured it out

**Comment by hanars** [comment]
This should be fixed now, let me know if you are still seeing an issue

**Comment by katie-larkin** [comment]
This just happened again with the attached file in https://seqr.broadinstitute.org/project/R0359_cmg_manton_genomes/project_page

[Copy of CMG_Manton_WGS_SK-3SDL_PedigreeSampleManifest.xlsx](https://github.com/macarthur-lab/seqr/files/3432798/Copy.of.CMG_Manton_WGS_SK-3SDL_PedigreeSampleManifest.xlsx)

**Comment by hanars** [comment]
okay, this should for real be fixed now
