### ISSUE TITLE
missing pedigree images for CMG_Estonia_WGS project

### ISSUE THREAD

**Issue by Jchangster** [macarthur-lab/seqr#968]
Hi Hana,

I've noticed for the newer entry of families in https://seqr.broadinstitute.org/project/R0332_cmg_estonia_wgs/project_page, they don't have the pedigree image generated, even though the child-parental relationships are correct. 
![Screen Shot 2019-07-23 at 2 43 46 PM](https://user-images.githubusercontent.com/33735854/61738439-4f428e80-ad58-11e9-99eb-af1b8926c1ae.png)
-Jaime

**Comment by hanars** [comment]
This is fixed now

**Comment by Jchangster** [comment]
great thank you!
