### ISSUE TITLE
Gene Search 504

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#970]
https://seqr.broadinstitute.org/variant_search/results/c07ddbe62812ab0430088b301bc4238f?page=1&sort=xpos

A 504 error when trying to look for additional variants in the gene, when following the gene search link by the gene on the variant page. 
![Screen Shot 2019-07-25 at 6 27 54 AM](https://user-images.githubusercontent.com/37872186/61867499-5b883200-aea5-11e9-842b-4c1639aec1c7.png)

**Comment by hanars** [comment]
This is fixed now
