### ISSUE TITLE
Genotype not showing

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#978]
Hi Hana,

The genotype does not seem to be showing for this case- https://seqr.broadinstitute.org/variant_search/results/1a49655a0eaddead346f3cbb3b95f01d?page=1&sort=xpos

Also, IGV is not loading. Would this need to be communicated to Mike instead?

![Screen Shot 2019-07-31 at 9 30 13 AM](https://user-images.githubusercontent.com/37872186/62215917-d229a180-b375-11e9-9c89-492caab6a4c2.png)

**Comment by hanars** [comment]
Hi Lynn, the genotyope is showing, it is showing as ref/ref because it appears you did not apply any inheritance filter. In addition to selecting the custom affected statuses, you have to select and inheritance mode

For IGV that is a separate issue. In general its good to check with me first, but in this case we should have @mike-w-wilson look into it

**Comment by mike-w-wilson** [comment]
@katie-larkin , do you know where these samples moved? I can't find them in terra.

**Comment by katie-larkin** [comment]
@mike-w-wilson , it's now in the AnVIL workspace gs://fc-secure-efe57a60-2421-405d-85f4-90d5af86e30b/CMG_Broad_Orphan_VCGS-White_WGS_all/RP-1307/WGS/VCGS_FAM22_69/v2/VCGS_FAM22_69.cram . It's a big problem that the metadata for Terra sometimes doesn't update when the sample is moved, so it appears to still be there with the cram missing.

**Comment by katie-larkin** [comment]
@mike-w-wilson, you should have access to these now in the AnVIL workspace here: fc-secure-efe57a60-2421-405d-85f4-90d5af86e30b
AnVIL google buckets use authorization domains, which our PM team currently doesn't have permissions to add people to and are slowly getting them. We should have that by early next week but please Slack me if you're having trouble with access

**Comment by hanars** [comment]
@mike-w-wilson have you been able to update this?

**Comment by mike-w-wilson** [comment]
No I can't see inside that bucket: 
`[15:00:44]wma13-a4c:~ 502 1 $ gsutil ls gs://fc-secure-efe57a60-2421-405d-85f4-90d5af86e30b/CMG_Broad_Orphan_VCGS-White_WGS_all
BadRequestException: 400 Bucket is requester pays bucket but no user project provided.` This is an issue with all anvil workspaces. I believe @katie-larkin is looking into it.

**Comment by mike-w-wilson** [comment]
This is now fixed.

**Comment by jbelsky** [comment]
hi @hanars, @katie-larkin, and @mike-w-wilson - not directly related to the Seqr, but I was wondering if either of you could provide insight into how you resolved the gsutil `BadRequestException: 400 Bucket is requester pays bucket but no user project provided.`  I am running into the same issue with gsutil on an AnVIL workspace (for GTEx v8), so any guidance would be much appreciated.  Thanks!

**Comment by hanars** [comment]
So we got around it but having the AnVIL team authorize us to use their project as the billing project for all our gsutil commands. You'd have to reach out to them to see if they'd be open to letting you do that as well

**Comment by katie-larkin** [comment]
Yes, AnVIL workspaces are required by the NIH to have the requester pay for access as well as computational charges on the workspace. Therefore you need to provide a billing project on all gsutil commands.

Either way reaching out to the AnVIL team will be helpful, but depending on the scope of youraccess requirements you may need to provide your own billing project and funding source.

**Comment by jbelsky** [comment]
@hanars and @katie-larkin - thanks for your prompt responses and suggestions!  I actually just heard back from the Broad, and my issue was that I was missing the `-u` parameter in `gsutil -u [billing-project] cp`.  Appreciate your help!
