### ISSUE TITLE
Variant appearing in TOPMED but not in TOPMED

### ISSUE THREAD

**Issue by lecb** [macarthur-lab/seqr#985]
For family TOP_BB1915_1, there is a variant tagged for analyst high priority in MTM1 (p.Pro585Ala). It shows in SEQR as in TOPMED (AC of 2) but when going to TOPMED the variant is absent. I wanted to draw your attention to this discrepancy. 

Thanks as ever for all your efforts!

**Comment by hanars** [comment]
This is a genome build issue, its not in the hg19 version of topmed, but seqr only has hg19 coordinates for that project. If you liftover the corrdinates to hg38 and search for that in topmed I see 2 hits: https://bravo.sph.umich.edu/freeze5/hg38/variant/X-150671536-C-G
