### ISSUE TITLE
Y chromosome coordinates in females

### ISSUE THREAD

**Issue by lynnpais** [macarthur-lab/seqr#995]
<img width="1237" alt="Screen Shot 2019-08-19 at 10 55 23 AM" src="https://user-images.githubusercontent.com/37872186/63275895-55049480-c270-11e9-863e-4ddc28859eb1.png">

Hi Hana, I think this is a mapping issue. It's coming up more frequently, I don't think I have seen it before. Not sure if it is a bug you need to address, but I thought i would bring it to your attention anyway.

**Comment by hanars** [comment]
@lynnpais has there been any update on this?

**Comment by lynnpais** [comment]
@hanars there's nothing I can on my end wrt this. It is a larger issue. Daniel said to bring it up at an analyst meeting. I'll discuss with Alysia . Please leave this ticket open for now. Thanks.
