### ISSUE TITLE
AWS VEP issue

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/seqr#997]
Hello,

We are trying to make VEP working (running the pipeline) on AWS and having a real trouble with it because there is not much of debug output that could point us any direction. The stack trace looks like the following:

Traceback (most recent call last):
  File "/home/hadoop/hail-elasticsearch-pipelines/hail_scripts/v01/load_dataset_to_es.py", line 899, in <module>
    run_pipeline()
  File "/home/hadoop/hail-elasticsearch-pipelines/hail_scripts/v01/load_dataset_to_es.py", line 866, in run_pipeline
    hc, vds = step0_init_and_run_vep(hc, vds, args)
  File "/home/hadoop/hail-elasticsearch-pipelines/hail_scripts/v01/load_dataset_to_es.py", line 162, in wrapper
    result = f(*args, **kwargs)
  File "/home/hadoop/hail-elasticsearch-pipelines/hail_scripts/v01/load_dataset_to_es.py", line 430, in step0_init_and_run_vep
    vds = run_vep(vds, genome_version=args.genome_version, block_size=args.vep_block_size)
  File "/home/hadoop/hail-elasticsearch-pipelines/hail_scripts/v01/utils/vds_utils.py", line 136, in run_vep
    vds = vds.vep(config="/vep/vep-gcloud-grch{}.properties".format(genome_version), root=root, block_size=block_size)
  File "<decorator-gen-464>", line 2, in vep
  File "/home/hadoop/hail-0.1-spark-2.0.2.zip/hail/java.py", line 121, in handle_py4j
hail.java.FatalError: HailException: vep command '/usr/bin/perl /vep/variant_effect_predictor/variant_effect_predictor.pl --format vcf --json --everything --allele_number --no_stats --cache --offline --dir /vep --fasta /vep/homo_sapiens/85_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --minimal --assembly GRCh37 --plugin LoF,human_ancestor_fa:/vep/loftee_data_grch37/loftee_data/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15 -o STDOUT' failed with non-zero exit status 2

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 9.0 failed 4 times, most recent failure: Lost task 1.3 in stage 9.0 (TID 2352, ip-172-31-48-222.ec2.internal): is.hail.utils.HailException: vep command '/usr/bin/perl /vep/variant_effect_predictor/variant_effect_predictor.pl --format vcf --json --everything --allele_number --no_stats --cache --offline --dir /vep --fasta /vep/homo_sapiens/85_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa --minimal --assembly GRCh37 --plugin LoF,human_ancestor_fa:/vep/loftee_data_grch37/loftee_data/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15 -o STDOUT' failed with non-zero exit status 2

Do you know what we could try or at least how to debug it? We verified that 'variant_effect_predictor.pl' is compiled correctly by running 'perl -c variant_effect_predictor.pl'. Then, sample.vcf is fine too, we checked it with vcftools validator. Hail seems to start and run fine until the line that runs vep is encountered.

**Comment by bw2** [comment]
ok, let us know if doesn't work on master.
